### ISSUE TITLE
[Admin] Add "Bubbler" weapon to the To-Do list.

### ISSUE THREAD

**Issue by EvilTelephone** [andwn/cave-story-md#10]
It's acquirable in the current build, but as expected it doesn't function yet.

**Comment by sikthehedgehog** [comment]
The weapon you get from Curly doesn't work either, for that matter. (screws you over if you don't know beforehand to not exchange your weapon)

**Comment by andwn** [comment]
Just to work around this I'll copy the polar star code into all the unfinished weapons temporarily. Really not sure what to do about level 3 bubbler. Just compounding 12-15 more sprites into an already sprite heavy game... Maybe give it more of a megaman leaf shield look. That's 4-6 sprites instead.

**Comment by sikthehedgehog** [comment]
How many _objects_ does it spawn?

**Comment by EvilTelephone** [comment]
3 or 4 sprites consisting of several small bubble graphics each might be a workaround.

**Comment by andwn** [comment]
That depends on what you mean by objects, because (player) bullets are their own structure that are not added to the object list but it's own array. The bullets orbit around the player then begin firing once there are 10 or so.

**Comment by sikthehedgehog** [comment]
Actual bullets in game logic rather than the sprites. If you meant each projectile has multiple sprites then that sounds feasible, if not you risk there being dissonance between what you can see and how the game actually interpretes it.

**Comment by andwn** [comment]
The bubbler still doesn't do anything, but it is in the TODO list so
