### ISSUE TITLE
Sisters Fight

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#102]
The dragons transition directly from their mouth-open state to their derp face state without being shot first.

They fly too close to the centre platform. It makes it hard to stand in the middle, but easy to spam from the bottom. The reverse should be true.

The dragons are still there after the defeat sequence flash.

Last of all the spawned save point after the fight cannot be interacted with.

**Comment by Leo40Git** [comment]
>The dragons are invulnerable in their normal state when they should always be shootable.

No? The entire gimmick of the fight is that you can only attack them when they're about to attack you.

**Comment by andwhyisit** [comment]
Turns out Leo40Git is right. Updating the OP.

**Comment by andwhyisit** [comment]
Just to note, when I suggested that the sisters were flying too close to the centre platform I meant too close above and below the platforms rather than being too close to the sides.

They still seem to transition to their derp face without being shot as well.

Here's an example of both issues in action:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/sistersaredoinitforthemselves_zpshcrb66bo.gif)

**Comment by andwn** [comment]
Something is definitely wrong with my sin/cos tables, both Sisters and Misery's rings are revolving in a diamond shape.

For the faces I probably forgot to reset a timer at zero when the state changes to the mouth opening.

**Comment by andwn** [comment]
And figured that out.... I messed up generating the table big time.

I had:
`table[i] = sin(i * 3.1415926 / 0x100) * 0x200 + 0.5;`
instead of:
`table[i] = sin(i * 3.1415926 / 0x80) * 0x200 + 0.5;`

Everything except the 4 straight sides were wrong values. 🤐
