### ISSUE TITLE
Plantation Sprite Weirdness

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#104]
Both jail 1 and 2 are missing bars.

Dragonfly sprites are broken.

The Mimiga on the bed in the rest area is invisible.

Quote isn't wearing the Mimiga Mask.

All spikes are invisible.

**Comment by andwhyisit** [comment]
The Mimiga on the bed is now both invisible and non-interactable. Something weird is going on there.

The Mimiga Mask still isn't showing. Though looking at your code it seems you are doing it somewhat wrong. The tsc command <EQ+0064 sets the equip flag for the Mimiga Mask and <EQ-0064 unsets it. The reason why it needs to be done this way as opposed to by checking if the item is held is because Quote will take off the Mimiga mask after giving Curly the Ma Pignon if he is wearing it and then will put it back on after Curly's extended exposition ends.

Here's the list of equip states:
01 00  0001  Booster v0.8 (ignored if v2.0 equipped)
02 00  0002  Map System (equipped means that you can press a shortcut button to bring up the map)
04 00  0004  Arms Barrier
08 00  0008  Turbocharge
10 00  0016  Curly's Air Tank
20 00  0032  Booster v2.0
40 00  0064  Mimiga Mask
80 00  0128  Whimsical Star
00 01  0256  Nikumaru Counter (equipped means that the timer starts counting)

All equipped states are independent of the item in question.

**Comment by andwn** [comment]
Well that explains why the save hacking doc said adding the mask item doesn't make you wear it...

**Comment by andwhyisit** [comment]
Confirmed as fixed.
