### ISSUE TITLE
Ma Pignon

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#109]
No sprites are visible and rocks don't fall during the fight.

**Comment by andwn** [comment]
Hol up some of the frames are still wrong

**Comment by andwhyisit** [comment]
Everything is working beautifully apart from one detail:
Ma Pignon is immune to missiles.

**Comment by andwn** [comment]
There is a big block of commented out NXEngine code to prevent Missile and Blade damage. Toroko + is also apparently supposed to be immune to missiles (she isn't right now).

**Comment by Leo40Git** [comment]
Toroko + isn't immune to Missile damage.

**Comment by andwn** [comment]
Welp, I will do something special just for ma pignon, unless there are any other enemies that are immune to missiles that way.

**Comment by andwhyisit** [comment]
Just Ma Pignon as far as I am aware.

**Comment by SkyTheLeafeon** [comment]
Has this been resolved?
