### ISSUE TITLE
[Crash/Error] Rare crash on killing enemies in Egg Corridor

### ISSUE THREAD

**Issue by EvilTelephone** [andwn/cave-story-md#11]
Has only happened a couple of times. This last time I believe I had just killed one of the flying guys.

![eggcorridorcrash](https://cloud.githubusercontent.com/assets/539616/16698580/f98fe3d0-451c-11e6-8dba-0234122e3f80.png)

**Comment by sikthehedgehog** [comment]
Sounds like #5 but that should be fixed? Make sure you're on the latest build (2016.07.02).

**Comment by EvilTelephone** [comment]
I'll double check, but I'm pretty certain I was using the 2016.07.02 build when this error occurred.

You're right, though, it sounds exactly like what was happening in #5.

**Comment by sikthehedgehog** [comment]
OK it seems the bug is still around in Egg Corridor (I gotta recheck Grasstown). May want to make thus issue a dup.

**Comment by EvilTelephone** [comment]
This appears to be an emulator specific occurrence. Killing the big green flyer in Egg Corridor while running the game on Genesis Plus GX (via RetroArch) will always result in the above error screen. In Kega Fusion I have not been able to recreate the error at all. Not sure which one is more "correct".

**Comment by sikthehedgehog** [comment]
Fusion doesn't emulate address errors, newer emulators do. Doing this in C is pretty hard though (the compiler always aligns everything for you), so I assume it's some invalid pointer somewhere?

**Comment by andwn** [comment]
Question: does this happen more often if you (quote) are colliding with the enemy or have stood on top of it? i very recently put in preliminary moving platform code that doesnt exactly work yet.

I'll test all these bugs on hardware when I'm home Monday.

**Comment by EvilTelephone** [comment]
> does this happen more often if you (quote) are colliding with the enemy or have stood on top of it?

Doesn't seem so. I ran through that section with the two big flyers a bunch of times and so far I haven't found much of a pattern.

1. Running through the level and immediately killing the first large flyer as soon as you see it will infrequently cause a crash. Getting hit and/or riding on top of enemies doesn't seem to change the frequency at which crashes occur.

2. Running through through the level and then running past the first large flyer, clearing the nearby enemies near the second large flyer, then running back and killing the first one will allow killing of the first large flyer with virtually zero chance of crashing. I don't recall actually ever crashing using this method in ~20 runs.

3. Going in the door near the two big flyers and coming back out will almost always lead to a crash when killing the first one. This is true whether or not all the nearby enemies have been killed or not.

My gut is telling me that it must have something to do with the number of objects either on screen or in memory to be processed in some way. One thing I haven't reliably tested yet is clearing out all the collectables and/or making sure there are no bouncing yellow experience triangles left behind anywhere.

**Comment by andwn** [comment]
Keeps happening to me on an everdrive when killing either of the large flying enemies. Their code isn't any different from other enemies so I can only make guesses at this point. Can probably figure this out easily once I get gdb working again.

**Comment by andwn** [comment]
I'm feeling pretty stupid right now

![Before](https://my.mixtape.moe/kqoxlp.png)

![After](https://my.mixtape.moe/rulyta.png)

**Comment by sikthehedgehog** [comment]
(・ω・`)
