### ISSUE TITLE
Misery: Infinite Object Spawning

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#113]
Misery's lightning attacks and bubble shields never expire. The game slows down like crazy because there are up to 7 new objects permanently placed on the screen for each of Misery's attack rounds. The whole fight is a race to see if Misery will expire before the game does.

**Comment by andwn** [comment]
This entire fight is pretty hilarious. The rings spread out way too far and revolve in a diamond shape. Can't wait to see how bad I messed up the doctor.

**Comment by andwn** [comment]
Update: Frenzied Doctor is pretty hard, especially when spawning the lag bats, there are so many that the sprites begin overwriting the background. Not bad.

**Comment by andwhyisit** [comment]
It's probably worth mentioning that during my holiday testing run I didn't get the machine gun, and given that the super missiles don't work at all when I got those my most powerful weapon in the second half of the game was the fireball. I had to get a bit creative with boss fights.

I took that bat slowdown to be a blessing. :P

**Comment by andwn** [comment]
> that Arthur comment from Chako after the fight turned all the Mimigas into circles.

That does it time to make a video

**Comment by andwn** [comment]
![fusion_2017-02-21_23-18-15](https://cloud.githubusercontent.com/assets/8164394/23197152/43abf5ee-f88c-11e6-9c68-4a801fa7a031.png)
IT'S PERFECT SHIP IT LIKE THIS

**Comment by andwhyisit** [comment]
👍

**Comment by andwhyisit** [comment]
The bat sprites seem to spazz out a little, and the bats themselves absorb damage like a giant sponge without dying.

That and the steps to the throne room that appear after the fight can't be stood on, but I can bump my head on them.

**Comment by andwhyisit** [comment]
While I am here I figured I might as well do a gag reel for undead core:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/undeadcoregagreel_zps7dcp5gjw.gif)

(the one without the player sprite is because a mini core pushed me into a wall)

Regarding the Misery fight, the only thing left is the falling blocks.

**Comment by andwn** [comment]
Before making the release, I tossed in code that spawns the Undead Core, but did not bother to test it since I was just going to let it be broken anyway lol. That sprite fuckup will definitely be a hard crash on an actual Genesis.

The hardest part of all this is going to be Sue's face graphic I bet.

**Comment by andwhyisit** [comment]
Sort of related, but there needs to be a ttl for the lightning orbs (or maybe have them auto-release after a set amount of time). I know this isn't something that is present in the original, but given the limited resources it is probably a good idea.
