### ISSUE TITLE
Outer wall H/V Trigger

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#115]
I don't seem to be falling to my death on the outer wall. I am literally standing on the bottom of the map. The H/V trigger that ensures my death seems to only be covering the first 10 tiles and then giving up after that.

There also needs to be some way for the player to fall off the map.

**Comment by andwhyisit** [comment]
Falling off the bottom of the map seems to be working, but the H/V Trigger is still broken, and I can't fall off the side of the map. You also need to make provisions for the player jumping off the top of the map as well (balcony).

I mean the "death after falling off the map" fallback works fine, but you really want those H/V Triggers to catch you first on the balcony given that the balcony has two non-death actions for jumping off the map that are triggered by H/V Triggers.

**Comment by andwn** [comment]
I'm going to have to do something special here. My engine has a limitation to the size of a collision box (each side is a single byte) so that explains the "10 tiles" thing. 

In Outer Wall and Balcony I will make them test player X/Y instead of collision (hopefully in a way that takes that upper right corner into account). In the other maps the logic should stay the same (stretch the collision box until hitting a wall). After doing this I can probably just remove the fallback.

**Comment by andwn** [comment]
![screenshot_2017-02-23_11-39-02](https://cloud.githubusercontent.com/assets/8164394/23268823/c3f8c26e-f9bc-11e6-802d-ff5027ecc972.png)
There we go, perfect

**Comment by andwn** [comment]
Rather than check which map you are on I made it check if the object is spawned outside the room. This seems to work properly except that upper right corner which tossed me in front of the house.

**Comment by andwhyisit** [comment]
Shouldn't they all test player X/Y?

Note the initial X/Y position of the H/V Trigger and the position of the player at the time.

If it is a vertical trigger then:
Check if the player's X position is less than the trigger. If so then run a check when the player's X position is equal to or greater than the X position of the H/V Trigger. If not then run a check when the player's X position is equal to or less than the X position of the H/V Trigger.

If it is a horizontal trigger then:
Check if the player's Y position is less than the trigger. If so then run a check when the player's Y position is equal to or greater than the Y position of the H/V Trigger. If not then run a check when the player's Y position is equal to or less than the Y position of the H/V Trigger.

If the player and trigger line up perfectly from the beginning or the check is validated then run the event.

Collision boxes seem like overkill here.

**Comment by andwn** [comment]
This would probably render Egg Corridor unbeatable, as well as make you skip Waterway entirely. I actually used to do this very similar to the way you described but set a width limit for the eggs and only activated X triggers if they were on screen. This still wasn't right, you could actually *miss* the trigger in Waterway and soft lock.

After getting frustrated I copied the NXEngine version (yes, that uses collision), which worked up until the OOB triggers became relevant. Anyway it mostly works now except that upper right corner which I will take care of after this next run through to make sure I didn't break anything else.

**Comment by andwn** [comment]
> On the balcony, scale it on the far right side of the map and you'll eventually reach a sign that says "THAT'S ALL, FOLKS!". If you jump into the clouds from there, it'll teleport you right next to the entrance to the throne room. If you go the slightest bit to the left and then go up into the clouds, it'll teleport you to the Prefab Building instead.

You know I'm not sure this was really intentional, there is no second trigger that does this I can find in Cave Editor, but the event 0212 has a <TRA to that position.

**Comment by andwhyisit** [comment]
If you are using collision boxes then maybe you could have them follow the player (centred) on their respective axis? Would that work.

Here's an example of what I mean:
![](http://s214.photobucket.com/user/andwhyisit/media/hvidea_zpsirhbwguv.gif)

The yellow pixel is the player, the blue pixels are tiles, and the red pixels are the H/V Trigger.

**Comment by andwn** [comment]
That could work but I already changed them to test XY if they are on the edge of the map :x

So actually what that person said is wrong, depending on the room you entered Balcony from the flag 1190, 1191, or 1192 is set. If you left the prefab house last that is where you will end up if you leave through the top of the screen. If you entered then left the throne room it will toss you there. Nothing positional, all flags.

```
#0090
<KEY<FL-1190<FL-1191<FL+1192<MNA<CMU0030<FAI0000<END
#0091
<KEY<FL+1190<FL-1191<FL-1192<MNA<CMU0030<FAI0001<END
#0092
<KEY<MNA<CMU0030<FAI0002<END
#0093
<KEY<MNA<CMU0030<FAI0003<END
#0094
<KEY<FL-1190<FL+1191<FL-1192<MNA<CMU0030<FAI0004<END

#0210
<PRI<FLJ1191:0211<FLJ1192:0212
<PRI<FAO0004<MYD0002<WAI0050<TRA0062:0095:0007:0074
#0211
<PRI<FAO0004<MYD0002<WAI0050<TRA0062:0095:0079:0073
#0212
<PRI<FAO0004<MYD0000<WAI0050<TRA0062:0095:0117:0062
```

**Comment by andwhyisit** [comment]
Explains why I could never reproduce more than one teleport location. I really need to clean up the secrets page.
