### ISSUE TITLE
wget and unzip are needed to build

### ISSUE THREAD

**Issue by r3muxd** [andwn/cave-story-md#116]
This might just be a bug in the Gendev fork, but if you don't have wget or unzip, the game fails to build. Found this one while trying to put it in Docker.

**Comment by andwn** [comment]
Might as well mention it, though the original gendev I forked from does not (it's meant for Ubuntu which has these out of the box, and frankly not including wget is heresy).

**Comment by r3muxd** [comment]
welp fixed that
