### ISSUE TITLE
Shootable Blocks Issue

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#119]
It seems that if you destroy shootable blocks that are offscreen then it destroys tiles at the other end of the screen.

![](http://i214.photobucket.com/albums/cc164/andwhyisit/shootabletiles_zpsphrqgujz.gif)

Tested on the NTSC build.

**Comment by andwn** [comment]
I accidentally made the range of the "on screen" check in block replace too far. So it made live replaces of off screen tiles resulting in... that.

It was recent to fix a nonsensical issue in the throne room.
![fusion_2017-02-22_19-45-07](https://cloud.githubusercontent.com/assets/8164394/23332964/074e9a58-fb51-11e6-9821-3811073f4ef4.png)
Even after fixing it, I still don't understand. Replacing blocks outside of the map somehow caused it.
