### ISSUE TITLE
Teleporters have an opaque sprite in front of the player

### ISSUE THREAD

**Issue by sikthehedgehog** [andwn/cave-story-md#12]
What subject says. Wasn't there in 2016.06.30 (where it looked fine), it's there in 2016.07.02. And it's even misplaced by a few pixels. I don't think the player is meant to become hidden by it?

**Comment by andwn** [comment]
I added the teleporter object's sprite just before i left and did not implement the animation yet

**Comment by andwn** [comment]
I hid the sprite. Will actually animate it later when I feel like it.
