### ISSUE TITLE
Fans

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#120]
When using the vertical fans in grasstown (while holding down A) I seem to be going two tiles higher than normal.

The fan leading to the grasstown hut should only go high enough to get to to the block on the right, but not the platform on the left.

**Comment by andwhyisit** [comment]
Here's a comparison...

Original:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/fanorig_zpszftybwwu.gif)

MD NTSC build:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/fanntsc_zpsj08dkmnt.gif)

The short arcs are without holding the jump button, and the long ones are while holding the button.

**Comment by andwn** [comment]
The Mannans are all also facing right I'm noticing.

**Comment by andwhyisit** [comment]
Almost there. The jump button boosted fan height needs to be reduced by one tile.

**Comment by andwhyisit** [comment]
Vertical fans are perfect. Thanks!

Unfortunately the horizontal fans need some tweaking. The length when holding down the jump button on a horizontal fan is one tile too long, however when not holding down the jump button everything else is correct.

**Comment by andwn** [comment]
Are you using the gap to reach the gum room as a reference? I increased the speed because it was impossible to reach. Though I made another recent change for the hitbox to be wider, maybe in combination those changes are too much. I' ll tweak the older change a bit.

**Comment by andwhyisit** [comment]
The horizontal fans are working nicely now. Marking as closed.
