### ISSUE TITLE
Happy 500 commits!

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#121]
There is a clear lack of celebration on your part. This must be rectified.  :p

**Comment by andwn** [comment]
I was gonna make a new release to celebrate but gonna delay it a bit until I replace all the level select data (I'm up to Plantation now).

Don't worry I'm sure we will be celebrating 200 issues soon enough!

**Comment by juef17** [comment]
Hey guys! I'm a lurker, but I figured this "issue" is a nice opportunity to write a bit. I read every single thing that's done here, and it's fascinating. Your work is amazing! Keep it up :)

**Comment by andwhyisit** [comment]
Celebration noted. I'll mark this issue as complete. :p
