### ISSUE TITLE
SML doesn't fire on 0 max ammo, <TAM is wrong

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#123]
In the Core warp, your Super Missile Launcher has 0 max ammo (this might happen in other warps, the Core warp is the only one I tested), meaning it _should_ have infinite ammo. What actually happens, however, is that you can't actually fire the Missile Launcher at all. Since the Super Missile Launcher and normal Missile Launcher currently use the same logic, this happens with the normal Missile Launcher too. 

Also, having a Super Missile Launcher with 0 max ammo should be impossible... but since <TAM (or more accurately, player_trade_weapon) is coded incorrectly, it happens anyway:
When the game does the "opened SML chest" event in Boulder Chamber, it calls <TAM with a 3rd parameter of 0. In the original game, calling <TAM with the 3rd parameter set to 0 causes the new weapon to inherit the old weapon's ammo and max ammo values. Here, it just sets the new weapon's ammo and max ammo to 0.

**Comment by andwn** [comment]
That should fix the logic. The saves still have the wrong values, will just modify it in a hex editor.

**Comment by andwhyisit** [comment]
In weapon_fire_missile() shouldn't you change _w->ammo--;_ to _if(w->ammo>0){w->ammo--;}_ or _if(w->maxammo!=0){w->ammo--;}_

**Comment by andwn** [comment]
Yes, though it will underflow instead of being negative. I'm sure the HUD would look just lovely after getting a missile expansion. Or maybe it will just say 100 forever.

**Comment by andwhyisit** [comment]
Still has the same problem...

Is this any better?

if(b == NULL) return;
if(w->ammo) w->ammo--;
else if(w->maxammo) return;

**Comment by andwn** [comment]
I just tried the Core save and it works fine???

**Comment by andwn** [comment]
oh thats what you meant...
