### ISSUE TITLE
Curly Holds Weapon With Her Teeth

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#126]
Curly holds the machine gun / polar star around 3 pixels too high in the Labyrinth when firing sideways. She also holds it sideways above her head when firing upwards.

**Comment by andwn** [comment]
I lowered the weapon but didn't notice the second thing.

and maybe I should push Curly in front of the gun when she is coming on screen.

**Comment by andwhyisit** [comment]
Here's what it looks like when Curly aims upwards:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/howtoshootupwards_zps0wgj2f7c.gif)

**Comment by andwhyisit** [comment]
..aaaand here is the polar star:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/polarstarhat_zpsplzyw86l.gif)

**Comment by andwn** [comment]
Oh that's why I didn't notice. The color (polar star) was wrong and I didn't re-test after changing it.

**Comment by andwhyisit** [comment]
You didn't talk to the old man in Viridian did you? Because Curly turned into a Missingno.

![](http://i214.photobucket.com/albums/cc164/andwhyisit/missingnocurly_zpsge5b7bkn.gif)
