### ISSUE TITLE
Booster 2.0 Preview Box is Empty

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#129]
![](http://i214.photobucket.com/albums/cc164/andwhyisit/airbooster_zpsbeoosuxx.gif)

Uhh... thanks Booster... I guess...

**Comment by andwn** [comment]
Good luck making it through Hell with that.

I don't know what it is about this room. It's had weird issues before like the <GIT window using tiles from the <YNJ window. There must be some edge case where the TSC does something before/after the <GIT messing it up.

**Comment by andwn** [comment]
![blastem_2017-03-02_21-56-02](https://cloud.githubusercontent.com/assets/8164394/23536485/32313b18-ff93-11e6-926a-1ba0fb19b461.png)
I have no explanation
