### ISSUE TITLE
Elevator in Egg Corridor has broken physics

### ISSUE THREAD

**Issue by sikthehedgehog** [andwn/cave-story-md#13]
Presumably unfinished platform physics, but still it makes that part pretty annoying. The player doesn't move with the elevator which makes it hard to use it to move across floors (and if you aren't lucky with your jumping, you can get stuck at the bottom of this room).

**Comment by andwn** [comment]
This is "fixed" but I noticed the player bouncing against walls oddly sometimes while the platform is moving so I want to take care of that before closing.

**Comment by andwn** [comment]
Shouldn't be happening anymore in this build

https://github.com/andwn/cave-story-md/releases/tag/SNAPSHOT-2016.07.16

**Comment by catskull** [comment]
I didn't experience this in the latest build.
