### ISSUE TITLE
Spike Framerects

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#130]
I was playing around with the unfinished Hell B1 to double-check the Booster, and the framerects for the large -127 spikes seem to be around 7 pixels too high when compared to the original game.

**Comment by andwn** [comment]
It's just the graphic is too high or the whole object itself (including collision)? Weird that so many objects have had this issue with the drawing point/offset although my numbers are straight from npc.tbl.

**Comment by andwhyisit** [comment]
The graphic is positioned exactly as it is in the original. The point of collision is too high.
