### ISSUE TITLE
Arms Barrier description doesn't fit in textbox

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#131]
![doukutsu_007](https://cloud.githubusercontent.com/assets/7997354/23551166/a253f8d8-001d-11e7-8a42-afafc5943e18.gif)
I'll just let the image speak for itself.

**Comment by andwn** [comment]
Just noticed something. Why does it not mention damage is halved? Did AGT leave that out? I should replace the whole thing.

**Comment by Leo40Git** [comment]
...wait, the thing halves damage? Yeah, apparently AGT _did_ leave that detail out.

**Comment by tilderain** [comment]
Does it really halve damage though? I tested it in the original and it didn't seem to change.

**Comment by andwn** [comment]
WELL..... why did I think it halved damage? I am going crazy after all.
