### ISSUE TITLE
Jail #2 and the Machine Gun

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#132]
The Machine Gun causes weird graphical flickering when it is fired in Jail No. 2.

Then this happened:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/getoutofjailfreecard_zpsbpbf7t2n.gif)

**Comment by andwn** [comment]
There isn't much I can do about the first part but I made the cages and mimigas never deactivate so they will stop unloading/reloading themselves.
