### ISSUE TITLE
Missing 16th credit illustration

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#143]
![credit16](https://cloud.githubusercontent.com/assets/7997354/23996944/1142133a-0a58-11e7-9bd4-867b37eeae32.png)
Extracted straight from Cave Story (well I converted it to PNG).

**Comment by andwn** [comment]
Ah thanks. How did you extract it anyway? I didn't exactly look that hard but didn't find a real way to do it other than figure out how to build NXEngine in windows.

**Comment by Leo40Git** [comment]
Your welcome. I used a program called [Resource Hacker](http://www.angusj.com/resourcehacker/) to extract it from the Cave Story executable.

**Comment by andwhyisit** [comment]
Resource Hacker is also how the org files are extracted as well.

**Comment by Leo40Git** [comment]
Well, the resource's been added, so I guess this issue isn't needed anymore.
