### ISSUE TITLE
Fuzz Core is Invincible

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#144]
Bullets seem to pass through the Fuzz core without causing damage.

Same for Shutter No.4. It is now impossible to make it past the core without using level select.

**Comment by andwn** [comment]
May as well use this as an excuse to fix the animation on shutter 4.

...I haven't touched it in a long time though how the hell did it get invincible.

**Comment by andwhyisit** [comment]
It could be something left over from your bullet collision rewrite from a while back maybe?
