### ISSUE TITLE
Arms Barrier should not halve damage

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#145]
The Arms Barrier halves damage, but it doesn't do so in the original game, nor in any remakes/ports to my knowledge.

**Comment by andwn** [comment]
Did you try it in a recent build because it hasn't halved damage for a week.

**Comment by Leo40Git** [comment]
So what the fuck does this piece of code in `player_inflict_damage` even *do*?
```c
// Halve damage applied to weapon energy if we have the arms barrier
if(playerEquipment & EQUIP_ARMSBARRIER) damage = (damage + 1) >> 1;```
