### ISSUE TITLE
Water Bug

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#147]
*fights core*

You have died. Want to retry? Y/N

![](http://i214.photobucket.com/albums/cc164/andwhyisit/checkoutthesesweetgills_zpsumhri8ym.gif)

**Comment by andwn** [comment]
I hate this background so much. Hopefully clearing the background tilemap every room load is enough to fix it.

**Comment by andwn** [comment]
I forgot I tagged the issue and did it again :ok_hand:
