### ISSUE TITLE
Palette Issues

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#148]
The robot in Egg Corridor 2 (to the left of the teleporter) is grey instead of blue, however it is blue in Egg Corridor 1.

The projectiles in the Core fight have mangled palettes.

**Comment by andwn** [comment]
They aren't spinning either. Not bad.

The robot is because the enemies in eggs2 need their own palette (their colors are too unique). The robots will have to be moved to one of the global palettes.
