### ISSUE TITLE
Map Button

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#149]
In the original game there was a shortcut button for the map. Can this be set to X in the md version?

**Comment by sikthehedgehog** [comment]
Wondering if Mode would make more sense here (I've seen a controller without Mode, though it was from a clone console and a bad idea in general).

Maybe control remapping would be a good idea. Will open a separate report for that.

**Comment by andwn** [comment]
The problem is more how it would have to clobber the stage, unless I cleared sprites and used sprites instead (but that's not how I did it in the menu, so I would have to rewrite it).

**Comment by sikthehedgehog** [comment]
Can't you just do the same thing you're already doing in the inventory? Like, invoke exactly the same code, except that just select the map immediately instead of waiting for the player to choose something.

**Comment by andwn** [comment]
Is #151 gonna be about the inventory drawing behind the map?

**Comment by andwhyisit** [comment]
Use the window plane, size it to the height of the map, and overlay the cutaway with solid black. Then just hide all other window plane elements while the map is active.

**Comment by andwn** [comment]
The window plane must always touch 3 sides of the screen

**Comment by andwn** [comment]
Oh i misread. Maybe surrounding with black is the only reasonable way..

**Comment by andwhyisit** [comment]
Actually you didn't misread. I didn't know about the 3 side requirement. 

Although I must agree with your misread misreading. Fullscreen black might be the way to go.

At least I am assuming that is what you meant.

**Comment by andwn** [comment]
I did think about this a bit more and want to try 2 things:

1. Clear window plane to transparency revealing the background, with the map in the center
2. Clear window plane to black so all you see is the map and maybe a "--MAP--". I think I forgot that in the inventory map, probably, maybe.

**Comment by sikthehedgehog** [comment]
Or just hide the level foreground and call it a quirk ;v

If you really want you can try showing/hiding the window plane with raster effects so it only hides the horizontal area where the map shows up (not being much worse than the textboxes), but that may be overkill.

**Comment by andwn** [comment]
We had the same idea at the same time. I hope that doesn't mean I am dragging you into my own insanity.

(I'm not messing with horizontal interrupts though)

**Comment by sikthehedgehog** [comment]
I just assumed that hiding the foreground was the obvious answer. The inventory is already doing it after all.

**Comment by andwhyisit** [comment]
Two issues with the map:
1. You should probably disable the water background while the map is active, since that is the one background that you don't want the player to know is a background.
2. Pressing the map button should exit the map if it is active.
