### ISSUE TITLE
Screwed up Blade graphics in Misery fight

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#151]
Pausing and unpausing the game seemed to fix the issue.

**Comment by andwhyisit** [comment]
Is this still an issue? I can't reproduce it.

**Comment by Leo40Git** [comment]
Probably not.

**Comment by andwn** [comment]
Weird, I didn't do anything to fix it. Though I did change how the Blade Lv3 slashes worked... or was one of the Lv1/Lv2/King sprites messed up?

This may or may not ever happen again but still curious.

**Comment by Leo40Git** [comment]
If I remember correctly, the Lv2 blade sprite was slightly messed up.
