### ISSUE TITLE
Glitched out sprites after using Map Button

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#158]
![doukutsu_008](https://cloud.githubusercontent.com/assets/7997354/24250765/a9b58c54-0fe0-11e7-8c33-6fd5bc434c4b.gif)
If it matters, I opened the map using the X button.

**Comment by Leo40Git** [comment]
_turns around_
![doukutsu_009](https://cloud.githubusercontent.com/assets/7997354/24250862/f73be55e-0fe0-11e7-8639-bb761e1114f5.gif)
...well then.

**Comment by Leo40Git** [comment]
![doukutsu_010](https://cloud.githubusercontent.com/assets/7997354/24250910/1c503f34-0fe1-11e7-8de5-a5d266dd5733.gif)
More glitchery.

**Comment by Leo40Git** [comment]
![doukutsu_011](https://cloud.githubusercontent.com/assets/7997354/24250961/3f57b5ac-0fe1-11e7-86ee-a4853b55ddf8.gif)
At least the door fixed itself, I guess...?

**Comment by Leo40Git** [comment]
[balcony but with fucked up sprites.zip](https://github.com/andwn/cave-story-md/files/864906/balcony.but.with.fucked.up.sprites.zip)
Save state.

**Comment by andwn** [comment]
This'll probably happen on any map that's large enough. Going to have the map find other places to stores tiles after it runs out of space.

Either that or have a few stock tiles of 8x8 solid/free to "compress" the space it uses. It would certainly fix Balcony if nothing else, most of that map is duplicate back tiles.

**Comment by Leo40Git** [comment]
1cd684a62cd6b4eaf6c9bfd188de64ad3276be50
woo
