### ISSUE TITLE
Double-Layered Water 

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#159]
It's your favourite water background at work again.

http://andwhyisit.bugsiteguardian.com/csmd/wetwater_zpst0knrgr7.gif

Exit the room and re-enter for this bug to occur. This only happens on the pal build and only in this room.

**Comment by andwn** [comment]
Gonna leave this until later, need to wait for my hair to grow back before I can rip it out again.

**Comment by andwn** [comment]
This one should be gone in 0.5.1
