### ISSUE TITLE
Reset button, loading save game tiles are not drawn

### ISSUE THREAD

**Issue by catskull** [andwn/cave-story-md#16]
I'm using a real Genesis with an everdrive. If I hit the reset button and load my save game, most tiles are not drawn. If I power off then back on, it works fine.

**Comment by catskull** [comment]
Update: after loading, I let it sit for about 10 minutes while I filled out this issue. Eventually the music stopped, then an address error screen showed up and the game crashed. I can attach an image if you'd like!

**Comment by andwn** [comment]
Looking good

![Screen](https://my.mixtape.moe/kjqxok.png)

Turns out SGDK doesn't clear memory on reset by default. I may have fixed it try [this](https://my.mixtape.moe/jicxxf.bin)

**Comment by andwn** [comment]
Github automatically closing things again..

**Comment by catskull** [comment]
Thanks, I'll try it asap.

**Comment by sikthehedgehog** [comment]
Note that problems with the Reset button usually also expose problems when the game ends and returns back to the title screen (where again the program returns back to the beginning but without reinitializing everything). May want to look into that as well.

**Comment by andwn** [comment]
It does crash if you return to the title screen and try to start the game again a couple times. I think I just need to add cleanup code to the end of game_main() because it is no doubt leaking or keeping values lingering at nonzero.

**Comment by catskull** [comment]
This is fixed in the latest release.

**Comment by andwn** [comment]
Good to know. I think the game will still crash returning to the title screen (like after you die and say No) so I'll piggyback the fix for that into this issue before closing.
