### ISSUE TITLE
(Muscle) Doctor Fight Problems

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#161]
![doukutsu_012](https://cloud.githubusercontent.com/assets/7997354/24251260/3485c96a-0fe2-11e7-8dea-c4c3e8cb325e.gif)
I beat him like 5 seconds after taking this screenshot.
If it isn't clear, the healthbar isn't actually showing damage; it was still full after I dealt some damage.

**Comment by Leo40Git** [comment]
![doukutsu_013](https://cloud.githubusercontent.com/assets/7997354/24251318/75e6f578-0fe2-11e7-9fbe-ee6603b1b2fe.gif)
And now the healthbar won't go away.

**Comment by andwn** [comment]
Most of the time when a clipping/teleportation effect is used in the real game I just blink the sprite for a couple seconds. For now I'll make Doctor blink longer and start commenting all the places where the clipping effect needs to be used.
