### ISSUE TITLE
Space Jump Shananigans

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#162]
![](http://i214.photobucket.com/albums/cc164/andwhyisit/csneededametroidspacejumpanyway_zpsumk8sdeq.gif)
I can jump on air willingly. A horizontal fan followed by a vertical fan seems to do it. From this point on I am permanently in "jump on air" mode until I restart the game. By the way, I am archiving this build for.. *ahem*.. reasons (Woooo! Space juuuuump!).

![](http://i214.photobucket.com/albums/cc164/andwhyisit/frenziedpuppeteer_zpsqmsqhqiy.gif)
Control of my y position is hijacked by the small frenzied mimiga.

Both builds tested on both counts.

**Comment by andwn** [comment]
https://github.com/andwn/cave-story-md/commit/5941646cdd9233ab893a5198a9e0a5efd7ca6143#diff-93fc2cf0d83bd6687357cdccab273a2cL216

:eyes:
