### ISSUE TITLE
Helicopter Blade Sprite Problems

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#163]
![heliblades](https://cloud.githubusercontent.com/assets/7997354/24252228/818dd9a2-0fe5-11e7-971e-e35f25ced8a3.gif)
Excuse my amateur recording.

**Comment by andwhyisit** [comment]
You beat me to it.

**Comment by Leo40Git** [comment]
1cd684a62cd6b4eaf6c9bfd188de64ad3276be50
