### ISSUE TITLE
Mimiga Mask Issue

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#165]
Seems like interacting with something while wearing the Mimiga Mask reverts you back to normal, at least until the interaction event ends and you move.

**Comment by andwn** [comment]
Was it an event that automatically moves the player (like the teleporter)? Those usually work by hiding the actual player and creating a player NPC in place..... which I haven't modified to account for the mask. Maybe that's it?

The problem with the teleporter in particular is this:
https://github.com/andwn/cave-story-md/blob/master/res/sprite/quotele.png

That's something that I'm just going to leave as is until writing a proper teleport effect.

**Comment by Leo40Git** [comment]
It happened when I was talking to Momorin and when I was using the downstairs/upstairs doors in the Hideout. I know for a fact that those 2 events don't create a player NPC.

**Comment by andwhyisit** [comment]
Obligatory gif evidence:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/missingmamask_zpsitmpsems.gif)

**Comment by andwn** [comment]
ooh, that's because of how I forced the looking down sprite when an event starts. Just have to check for the mask there.
