### ISSUE TITLE
Special bosses don't have HP bars

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#169]
Monster X and the Undead Core don't have HP bars. This probably applies to the rest of the special bosses (Omega, Core, Sisters, Heavy Press and Ball Ballos).

**Comment by andwhyisit** [comment]
That's odd. The Core did have a health bar when the health bar was first introduced. A regression maybe?

**Comment by Leo40Git** [comment]
Yeah no, this is unintentional. It happens because the variable that stores the boss entity for the HP bar is now different from the variable that stores the special boss entity and there's no code that sets the former to the latter.

**Comment by andwn** [comment]
It's because all the boss attributes have to be hard coded in, the "event" value isn't set by the script (and that is what <BSL looks for). Instead of looking up those numbers I will just check if bossEntity is non null.

**Comment by andwn** [comment]
clarification: by attributes I mean those set by npc.tbl or a PXE file

**Comment by Leo40Git** [comment]
![doukutsu002](https://cloud.githubusercontent.com/assets/7997354/24320629/132c45aa-114a-11e7-9c61-00b9a6f91394.png)
Uh...

**Comment by andwn** [comment]
![blastem_2017-03-25_10-46-01](https://cloud.githubusercontent.com/assets/8164394/24323171/4e0b7cd8-1148-11e7-94e6-4a7f3046b7e5.png)
not bad

**Comment by andwhyisit** [comment]
Defeat the Booster. Save the world. :P

**Comment by andwhyisit** [comment]
In any case with the Undead Core it may be best to prioritise special bosses over normal bosses as far as hp is concerned,  because both Misery and Sue can be classified as normal bosses.

**Comment by andwn** [comment]
They don't have an event number of 1000 so it isn't going to find them anyway...... actually:

```
<MS2Hwah-hah-hah...<MYD0002<NOD<WAI0100<CLR<BOA0015You're not leaving this
place alive!!<NOD<CLO
<BSL0000<BOA0020
<CMU0032
<MNP0420:0028:0018:0000<ANP0420:0020:0000<WAI0050
<ANP0400:0020:0000
<ANP0410:0020:0000
<END
```

Zero???

**Comment by andwhyisit** [comment]
Noted as fixed. This can be closed.
