### ISSUE TITLE
The red barrier in the Egg Corridor is not completely solid.

### ISSUE THREAD

**Issue by diggly** [andwn/cave-story-md#17]
You can walk right through the red barrier in the Egg Corridor by simply holding right during your invincibility frames after it hurts you. Normally you're supposed to turn the barrier off with the ID card before you can get past it.  
Emulator I used was the Genesis Plus GX core in RetroArch.

**Comment by andwn** [comment]
I messed up something while moving the collision code a while back, will try to fix this sometime today.

**Comment by andwn** [comment]
Should be fixed

https://github.com/andwn/cave-story-md/releases/tag/SNAPSHOT-2016.07.16

**Comment by diggly** [comment]
Looks fixed, I tested it again in the latest snapshot and it no longer happens

**Comment by andwn** [comment]
Ah good, thanks for confirming!
