### ISSUE TITLE
Doctor Removes All Entities

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#170]
After the doctor is defeated, and the "defeated the doctor" message shows, all entities disappear (bars, mimiga, everything).

This only happens in the pal build.

Also attempting to go through the exit at the top of the screen renders the player unable to stand on any surface unless he collides with a wall or ceiling first (then the effect goes away again).

**Comment by andwn** [comment]
wat. this didn't happen yesterday did it? I don't think I messed with anything specific to that room.

**Comment by andwhyisit** [comment]
I don't know when it would have happened. I haven't gone past misery in the pal build before now. For all I know it could have happened at any time, or maybe it was always like that.

**Comment by andwn** [comment]
![screenshot_2017-03-24_13-19-56](https://cloud.githubusercontent.com/assets/8164394/24305788/a4d4abd4-1094-11e7-9f09-b3446bb5d14a.png)

Did it happen before or after the stairs appeared? Did the Doctor die on screen?

There could be some nuance with <DNP or <CNP when the object is off screen (I thought I fixed that a long time ago though).

**Comment by andwhyisit** [comment]
Evidence from the nightly:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/wellletourselvesoutthanks_zpsjke4rpvp.gif)

It also happened when the doctor died on the left side of the screen.

Also a bit of y lock there during my second test too.

**Comment by andwhyisit** [comment]
In the latest nightly the game just freezes the moment the message box appears.

**Comment by andwn** [comment]
Local:
![blastem_2017-03-25_08-39-45](https://cloud.githubusercontent.com/assets/8164394/24322281/ada07066-1136-11e7-916f-f1fb3494b125.png)

Nightly:
![blastem_2017-03-25_08-43-20](https://cloud.githubusercontent.com/assets/8164394/24322295/297156c4-1137-11e7-992b-9fa1b63dce88.png)

Guess I can at least figure out why the player is floating up. I hope it's not because the game ran out of memory and stated overwriting the player's speed with something else.

I need to bother Mike about BlastEm cutting off the bottom in 240 mode.

**Comment by andwn** [comment]
Just got an address error locally mid fight. I think it's his burst attack that activates when you try to do close combat. Creates a whole lot of red dots, and those aren't just effects, they are full blown entities...

**Comment by andwhyisit** [comment]
I'm trying to build dot animations to replace the existing dot entities. I don't know if you will use them but I figured I might as well give it a go.

Here's one for the initial transformation:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/mdblood3_zps0vdzaokv.gif)

**Comment by andwn** [comment]
For now I toned down the particles and I can't get it to crash anymore at least. His "redsplode" attack and dying animation had to take the biggest cuts. I think having a combination of something pre-rendered like you just did, and actual red dots can make it look less disappointing while not causing lag or running out of memory. Another idea is something similar to how I handled the sprinkler but have a few different frames of 2, 3, or 4 dots.

Unrelated, running straight up to bosses and mashing the blade Lv1/2 makes things go a lot faster than I thought they would, damn.

**Comment by andwhyisit** [comment]
The Lv.2 Blade is only narrowly exceeded by super missiles in terms of damage per second. The downside is that you have to get right up close to whatever you attack. So it is a (terrible pun incoming) double-edged sword.

**Comment by andwhyisit** [comment]
**Redsplode is now done:**
![](http://i214.photobucket.com/albums/cc164/andwhyisit/mdblood6b_zpspsedvo4n.gif)

64x40px, 22 frames, 50 frames per second.

**Comment by andwhyisit** [comment]
I also can't reproduce this issue in the latest nightly, so your fix worked.

**Comment by andwhyisit** [comment]
Might as well close this.
