### ISSUE TITLE
Credits

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#173]
![doukutsu003](https://cloud.githubusercontent.com/assets/7997354/24320678/09f82796-114b-11e7-9f43-1c5551b871de.png)

**Comment by andwn** [comment]
Do I need to make a containment thread for the credits too?

**Comment by andwhyisit** [comment]
@Leo40Git: It's a bit early to start submitting bug reports for the credits when the credits are still a work in progress.

**Comment by Leo40Git** [comment]
...hm, maybe I should've waited until the credits rooms actually loaded correctly to submit this.

**Comment by andwn** [comment]
I don't know what you're talking about, everything looks fine to me

![blastem_2017-03-25_19-22-03](https://cloud.githubusercontent.com/assets/8164394/24327647/5ba5e214-11a4-11e7-83c1-3f14958aa704.png)

**Comment by andwhyisit** [comment]
The maps do load correctly now (and the credits are damn sexy I might add), however they do have a tendency to centre-align themselves (which is default behaviour for maps, but not for the credits).

A trick to get to the credits quickly:
1. Level-select.
2. Select "Sacred Grounds".
3. Investigate the bookshelf in the Prefab Building.
4. Select "yes" to the question about giving up.
5. You should now be on the Balcony.
6. Jump off with Sue as per normal.

**Comment by andwn** [comment]
Yeah I also forgot to put one of the maps through the tile optimizer along with its tileset so it's all messed up. 💣 At least it's fairly easy to fix.

That and the Fall map is pretty blank. The clouds must be NPCs instead of part of the map.

**Comment by Leo40Git** [comment]
Might as well turn this into a containment issue.

**Comment by Leo40Git** [comment]
![doukutsu004](https://cloud.githubusercontent.com/assets/7997354/24359222/5d47d3ca-130c-11e7-80b4-5262944ac6ba.png)
looking good

**Comment by andwn** [comment]
:+1:

**Comment by Leo40Git** [comment]
There's supposed to be an animation of Quote dropping and walking between credits rooms... but it isn't there.
It's spawned in the main credits room's TSC (map 0).

**Comment by Leo40Git** [comment]
Fading looks like it's to/from white, not black.

The Quote walking animation also shows up before the first credits room.

**Comment by SkyTheLeafeon** [comment]
Has this been resolved?
Also, @Leo40Git Those screenies are hilarious to look at imo. XD

**Comment by andwn** [comment]
Mostly but there are other problems with the credits

**Comment by SkyTheLeafeon** [comment]
I recall the characters being misaligned with the text in the credits, but I might be mistaken.

**Comment by andwn** [comment]
honestly it took a while to get them aligned the way they are now

**Comment by andwn** [comment]
the issues now are mostly just chako being blue and the clouds taking up too much space. would be nice if i could figure out why the characters at the end aren't spawning either

**Comment by Leo40Git** [comment]
The characters spawning at the end are part of map 0 (the credits map in the original game)'s TSC, *not* a part of the credits script itself, as well as setting and clearing the illustration and animating Quote falling and walking between the credits scenes.  
Which is why the credits in the original game are an overlay triggered by a TSC command and not a separate game state.

**Comment by andwn** [comment]
oh, it's because i never load map 0, but do run the script from it, so the objects from the pxe file are not there. may as well load them manually at this point

**Comment by andwn** [comment]
2 years later and I still didn't add that code to load 0.pxe, whoops

**Comment by Leo40Git** [comment]
better late than never

**Comment by andwn** [comment]
![image](https://user-images.githubusercontent.com/8164394/93155884-0de80d80-f6d5-11ea-8b8a-4f9e925b02dd.png)

**Comment by andwn** [comment]
Credits are "done". There is still a little weirdness with the fading but I'll let it be until someone bugs me about it.
