### ISSUE TITLE
Breakdown Sequence Breaks Game

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#177]
Obligatory gif:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/breakdownbreaksdown_zpsswtkvq91.gif)

I've only been able to reproduce this in the ntsc build, although it doesn't happen consistently.

**Comment by andwn** [comment]
Works locally. Can you get to Grasstown at all?

**Comment by andwn** [comment]
Better question if Grasstown works otherwise: Did you fight the bosses or use the Hell save?

**Comment by andwhyisit** [comment]
Fought the bosses.

Oh, and maybe this is relevant, but I held A to fast-forward through the pre-fight cutscenes and the red particles caused the lame to lag something severe. This doesn't happen if I let things play out at normal speed. Maybe it is related?

**Comment by andwn** [comment]
Just got it to happen but a bit farther in. Seems random, but only happens if I hold A. That is somehow causing a memory leak somewhere.

**Comment by andwn** [comment]
And now it isn't happening... what the hell.

**Comment by andwhyisit** [comment]
It isn't happening for me either. Fuck.

Welp, time to close this issue until this thing breaks again.
