### ISSUE TITLE
Toroko Shack AI seems off 

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#178]
Original:
http://andwhyisit.bugsiteguardian.com/csmd/sticksandstones_zpsaitbqugl.gif

MD Version:
http://andwhyisit.bugsiteguardian.com/csmd/sticksandstonesmd_zpszjninp8s.gif

**Comment by andwhyisit** [comment]
Also after being shot by the player and then getting up again afterwards Toroko will face away from the player when talking in the MD version.

**Comment by andwn** [comment]
I gotta double check what the script does here. I spent an hour trying to fix it and gave up about a year ago (the facing direction I mean).

**Comment by andwn** [comment]
The running area and facing direction should be fixed on 0.5.1
