### ISSUE TITLE
Egg Corridor warp causes address error

### ISSUE THREAD

**Issue by catskull** [andwn/cave-story-md#18]
On real hardware, attempting to warp to the Egg Corridor causes an address error 100% of the time.

![image](https://cloud.githubusercontent.com/assets/6233563/16880604/45eefa1c-4a73-11e6-8fce-1e353649b732.png)

**Comment by andwn** [comment]
Which version of the ROM is this? I've never encountered it on my Everdrive, but will try it again after I get home today.

**Comment by catskull** [comment]
I was using SNAPSHOT-2016.07.12. I'll try again with the new release and see if it's any better.

**Comment by catskull** [comment]
I tried the latest release, and it still happened. I started a new game and now I can warp just fine. Closing the issue.

**Comment by andwn** [comment]
I am thinking your SRAM may have gotten corrupted when i changed the header somehow (cave story stores warp locations in the save data). Or maybe not, it's a mystery.
