### ISSUE TITLE
Jumping Height

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#180]
Here's a jump in grasstown in the original PC game:
http://andwhyisit.bugsiteguardian.com/csmd/narrowvictory_zpsapko4at3.gif

And here's the same jump in the MD version:
http://andwhyisit.bugsiteguardian.com/csmd/icantthinkofabetterfilename_zpsymve4c6e.gif

The player seems to be jumping 4 pixels higher when the jump button is held while jumping in the MD version vs the original.

**Comment by andwhyisit** [comment]
Oh and while I am here the frog enemy only jumps once in the MD version.

**Comment by andwn** [comment]
Well this is a can of worms. If I lower the jump height you can't reach balrog or save booster, so I gotta play with other parts of the jumping physics...

**Comment by andwhyisit** [comment]
This may help:
http://www.cavestory.org/guides/kimitech/images/cmg/cmg_lyger2.png
http://www.cavestory.org/guides/kimitech/images/cmg/cmg_lyger3.png

**Comment by andwhyisit** [comment]
Welcome back btw.

**Comment by andwhyisit** [comment]
The jumping in the NTSC build is now perfect.

The PAL build on the other hand...

NTSC: http://andwhyisit.bugsiteguardian.com/csmd/ntscgrassgap.gif
PAL: http://andwhyisit.bugsiteguardian.com/csmd/palgrassgap.gif

NTSC: http://andwhyisit.bugsiteguardian.com/csmd/ntschorfan.gif
PAL: http://andwhyisit.bugsiteguardian.com/csmd/palhorfan.gif

NTSC: http://andwhyisit.bugsiteguardian.com/csmd/ntscbooster.gif
PAL: http://andwhyisit.bugsiteguardian.com/csmd/palbooster.gif

**Comment by SkyTheLeafeon** [comment]
Has this been resolved?

**Comment by andwn** [comment]
Should be

**Comment by SkyTheLeafeon** [comment]
Yeah. Jumps in the MD version (as of 0.5.1) seem to be exactly the same if not identical to jumps in the PC version.

**Comment by andwn** [comment]
Closing this old one, fixed a while ago
