### ISSUE TITLE
Address Error when exchanging the Blade with the Gun

### ISSUE THREAD

**Issue by EvilDragon** [andwn/cave-story-md#184]
After bringing the little man home, he offers to exchange the blade with his gun.

This crashes the game and leads to an Address Error (if you need any numbers from there, let me know, I can look them up).

Tested on a MegaDrive II, not an emulator.

**Comment by andwn** [comment]
I'm probably just messing up the graphic switching like I did at first for curly giving you the machine gun. Gonna take care of it once I have a bit of time.

**Comment by andwn** [comment]
This got fixed in 0.5.0. The issue was that the Nemesis tile loading routine was trying to get sprite tiles from the wrong place.
