### ISSUE TITLE
Can get stuck in a wall in Grasstown Hut

### ISSUE THREAD

**Issue by sikthehedgehog** [andwn/cave-story-md#189]
In the fight that shows up after taking the missile upgrade, got pushed into the wall by the rogue mimiga (making dust by jumping to show where I got stuck):

![blastem_20170616_235300](https://user-images.githubusercontent.com/880005/27249597-a2b4c26a-52ef-11e7-8063-941da59adc26.png)

Tested in the nightly.

**Comment by andwn** [comment]
It's still possible for enemies to push you into walls in the latest version, but I added an "emergency gtfo" logic that pushes Quote out of walls when his center point is within a wall.

Eventually I need to rewrite parts of the player collision to make per-pixel checks instead of per-frame.

**Comment by sikthehedgehog** [comment]
Doing it per pixel would probably kill performance, the current method is
probably the best.

I suppose you could do the per-pixel test when the engine suspects
something is wrong (e.g. when Quote goes into a wall when it clearly
shouldn't happen)

**Comment by andwn** [comment]
the maximum player speed is 3 pixels per second so it shouldn't be too bad.. but I guess I should be avoiding adding more lag as much as possible.

**Comment by andwn** [comment]
err per frame not second

**Comment by SkyTheLeafeon** [comment]
Yeah, this is still a problem.
I wonder if there will be a 0.5.2 or something due to all the bugs and mistakes we're running into at this point.
I even played through Cave Story Plus today and died in the Labyrinth, and all the way through, I spotted several differences that may or may not be present in the original game.

**Comment by andwn** [comment]
This existed before 0.5.0 though. And of course it's still a problem, I just said I didn't commit the fix yet a half hour ago.

**Comment by SkyTheLeafeon** [comment]
Correct. It's not like I'm illiterate or anything - I clearly saw that. (Not trying to be mean.)

**Comment by andwn** [comment]
Don't remember the specific commit but couldn't get the issue to happen today
