### ISSUE TITLE
The Nightly

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#192]
The nightly may be broken for a while while I update gendev and transition to the new Makefile.

**Comment by andwn** [comment]
you might want to hold on that. i'm thinking about getting rid of the new makefile.

i got too excited about not having to use custom stuff anymore, the new gendev actually has several problems, including not even installing into /opt correctly (it just... doesn't copy the files at all), and building nm without plugin support, so generating a symbol table is impossible with link time optimization.

**Comment by andwn** [comment]
I should just make a zip you can extract and not have to worry about building this once i get it actually working properly 🐸

**Comment by andwhyisit** [comment]
It kinda depends on files in gendev that are removed by "make clean". Plus the pal build isn't building correctly (it either is ntsc or has ntsc headers).

**Comment by andwn** [comment]
you `make clean` before `make pal` right?

**Comment by andwn** [comment]
oh good i passed "PAL" to everything except the header

**Comment by andwn** [comment]
Those 2 commits should fix it maybe. I can't test the "new" makefile right now but the old one is running 50fps again

**Comment by andwhyisit** [comment]
I use the ultimate make clean:
rm -rf ./cave-story-md

In any case I'm assuming that I need to reinstall the gendev fork again?

**Comment by andwhyisit** [comment]
Well the nightly seems to be working except symbol.txt isn't being included in the zip.

Where is symbol.txt located these days?

**Comment by andwn** [comment]
I was trying something with stripping the symbols in the release build but it didn't actually decrease the size of anything so I put it back.

**Comment by sikthehedgehog** [comment]
> including not even installing into /opt correctly (it just... doesn't copy the files at all)

`/opt` is one of those folders that require you to sudo to have write access.

**Comment by andwn** [comment]
It didn't work with sudo. There have been several commits since I tried, so maybe it is fixed. I'm leaning towards building my own toolchain though.

**Comment by andwhyisit** [comment]
Should I rework the nightly generator for marsdev?

**Comment by andwn** [comment]
It's not super stable yet but I'm more confident about it than the new gendev (which couldn't even generate a symbol table...), so next time you are bored [go for it](https://www.youtube.com/watch?v=MN_SR4z_40s). Got a tarball for x64 so less praying to whatever decides to make your builds not fail.

**Comment by andwhyisit** [comment]
I love that you named the thing after the Roman god of war.

**Comment by sikthehedgehog** [comment]
Mars is the codename for the 32X
http://segaretro.org/Planet_codenames

**Comment by andwn** [comment]
The irony is even though I made it with SH-2 support for 32x games I lost interest with the platform after finding out about the memory layout changes. Maybe one day

**Comment by andwhyisit** [comment]
# SUCCESS!
The nightly is finally working again.

**Comment by andwn** [comment]
![happaned](https://user-images.githubusercontent.com/8164394/31585848-b3e9905a-b196-11e7-9361-5c72ce910a63.png)

**Comment by SkyTheLeafeon** [comment]
Speaking of PAL - booted v0.5.1a in PAL emulation, and it's sounding 👌 (plus, it works just fine as well.)
