### ISSUE TITLE
Music Getting Stuck While Saving

### ISSUE THREAD

**Issue by TokyoScarab** [andwn/cave-story-md#194]
I played this last night on my twitch stream and am glad that this project is still alive!  I love all the work that has been done and can't wait for future builds to be released!  I beat the entire game and for the most part didn't have any issues except this one that only happened twice in my playthrough.  When I would go to save my game, sometimes the audio would hang up and would ignore any changes in music that should of happened (like going to another zone).  Resetting and loading my save fixed the problem but I thought I would just let you know that it's a thing that can sometimes happen.  The first time was at the first save spot in the game and the second place I don't remember.  I have a feeling it's probably just a conflict of altering the music on or off or an order of operations kinda thing since I saved a ton and it only happened twice.  Anyways, keep up the good work! :D

**Comment by andwn** [comment]
Thanks for the report. Were you playing the nightly or 0.4.0? I did make a change since 0.4.0 that is meant to prevent the CPU that controls the sound cards from locking up while SRAM is being accessed.

**Comment by TokyoScarab** [comment]
No problem! :D  I was playing the 0.4.0 release.  You do nightly builds of this?  Are those just kept in the master?

**Comment by andwn** [comment]
It's in the readme. cavestory.org has automatic builds set up.

http://www.cavestory.org/md/nightly.zip

There is one for PAL as well. I don't test the whole game before I commit though, just before making releases, so random things may be broken.

**Comment by SkyTheLeafeon** [comment]
That link doesn't work.

**Comment by andwn** [comment]
Go tell Andwhy to install `libpng-devel` and it'll work tomorrow.

**Comment by andwn** [comment]
Actually maybe mentioning works on this website

test test @andwhyisit

**Comment by andwn** [comment]
And here is a possibly buggy 15 minutes ago build to hold you over [doukutsu.zip](https://github.com/andwn/cave-story-md/files/1765388/doukutsu.zip)

**Comment by andwn** [comment]
I built mdtiler for CentOS and included it in the repo and that somehow fixed it. Anyway that's not related to the original issue which should also be fixed. At least the music hanging hasn't happened to me since (would happen in Kega most often).
