### ISSUE TITLE
Crash jumping down in main city

### ISSUE THREAD

**Issue by hadess** [andwn/cave-story-md#195]
I didn't go to Sand Island yet, just navigated around the main city.

This is using the stable 0.4 version on real hardware (using an Everdrive).

![img_2105](https://user-images.githubusercontent.com/769861/29898884-865bbe32-8de8-11e7-8ae0-b976393d5b00.JPG)

(Let me know if those reports against 0.4 aren't useful)

**Comment by andwn** [comment]
This is why I put stable in quotes. Main City is Mimiga Village?

**Comment by hadess** [comment]
> This is why I put stable in quotes.

Oh, I don't mind. The game is absolutely great, so it keeps me going back to it :)

>Main City is Mimiga Village?

Yes, that's the one (first time I ever play Cave Story, so I'm not into the lore yet)

**Comment by Leo40Git** [comment]
Map names show up when you enter areas. You should probably read them.
Also, Sand Island is Sand Zone.

**Comment by hadess** [comment]
> Map names show up when you enter areas. You should probably read them.
> Also, Sand Island is Sand Zone.

This is a pretty passive-aggressive comment. I hope that's not what was intended.

**Comment by Leo40Git** [comment]
Whoops, that was definitely not intended!

**Comment by SkyTheLeafeon** [comment]
0.4.0 is pretty weird at times, for sure.

**Comment by andwn** [comment]
It's been a long time and while I don't know what caused this (or how to reproduce) I'm pretty confident it's not going to happen in 0.6.0
