### ISSUE TITLE
OOM when trying to go to Grasstown

### ISSUE THREAD

**Issue by hadess** [andwn/cave-story-md#196]
On real hardware (using an Everdrive), with v0.4. I went to Sand Island, back to the town, saw what they were up to outside, went back in Arthur's house and tried to teleport to Grasstown.

![img_2106](https://user-images.githubusercontent.com/769861/29898927-c675d44e-8de8-11e7-9765-59c2b99716af.JPG)

**Comment by andwn** [comment]
This should be fixed in the nightly but it happened in a different spot before (door between village and farm).

**Comment by hadess** [comment]
Feel free to close in that case.

**Comment by andwn** [comment]
Kept this open for a while cause I wasn't 100% sure, but seems nobody else ran into this.
