### ISSUE TITLE
Arthur's house teleport menu get stuck selecting Sand Zone

### ISSUE THREAD

**Issue by lfantoniosi** [andwn/cave-story-md#199]
On nightly build or 0.4.0 when selecting Sand Zone, Labyrinth is already shown but the game hangs after selecting any destination. Noticed similar problem when accessing the teleport menu after Egg Zone, the Grasstown was shown even before the computer being connected to it.

Repro: use Pre-sand zone savegame. Try to get to Sand Zone. Labyrinth will be available, but the selected zone is always the next one selected and the game hangs.

**Comment by andwn** [comment]
Same as #191. I think the teleporter variables just need to be cleared before loading

**Comment by andwn** [comment]
Aaand that was it... but here is a memory I would like to share.
![blastem_2017-09-02_11-17-49](https://user-images.githubusercontent.com/8164394/29996767-2749b708-8fca-11e7-8433-c98d85050a37.png)

**Comment by lfantoniosi** [comment]
I got the September 2 nightly version and I can't still get into sand zone or any other teleport destination. Check this save game from the officials
[arthur's place to sand zone.gens.srm.zip](https://github.com/andwn/cave-story-md/files/1272652/arthur.s.place.to.sand.zone.gens.srm.zip)

**Comment by andwn** [comment]
I just fixed it today. The nightly doesn't roll over for another 5-6 hours.

**Comment by lfantoniosi** [comment]
I just got Sep 3 nightly build. Same problem with the teleport. It shows Labyrinth where it wasn't supposed to be available (only Sand zone has been unlocked) and any choice lead to a hung, it always shows the choice + 1.

**Comment by andwn** [comment]
Are you using prof2sram per chance? That tool messes up the teleports. I would recommend using the level select instead since prof2sram is going to become useless once I change the save format to support multiple saves.

**Comment by andwn** [comment]
This for real shouldn't be possible anymore in 0.5.x and prof2sram is dead now so closing
