### ISSUE TITLE
iSuckAtThisGameSHIT cheat improvement

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#202]
The iSuckAtThisGameSHIT cheat should probably prevent ammo-consuming weapons from consuming ammo.

**Comment by SkyTheLeafeon** [comment]
How does that cheat work?

**Comment by Leo40Git** [comment]
iSuckAtThisGameSHIT (or by a proper name, "god mode") is a debugging cheat andwn made because he sucks at Cave Story, hence the name. Prevents damage (excluding insta-death spikes) and gives infinite ammo.

**Comment by SkyTheLeafeon** [comment]
How do you turn it on?

**Comment by Leo40Git** [comment]
Two words: Konami Code.

**Comment by SkyTheLeafeon** [comment]
Up, Up, Down, Down, Left, Right, Left, Right, B, A?

**Comment by SkyTheLeafeon** [comment]
...Tested it in "0.5.0b" - a ROM that fixed the issue with the config screen regarding its cursor (it was missing).

I was right.
It kinda feels like playing as Ballos - the player is unstoppable instead!
I'd imagine that'd make Hell a lot easier as well.

**Comment by SkyTheLeafeon** [comment]
Check issue #210 if you don't get what I mean by 0.5.0b.
