### ISSUE TITLE
Multilang game

### ISSUE THREAD

**Issue by Darknior** [andwn/cave-story-md#207]
Hi

Do you think at the end, when all will be done, you will try and take time to add a langage menu selection like on some (EUROPE) (En,Fr,De,It,Sp) genesis games ?

http://www.mobygames.com/game/genesis/smurfs_
![92897-the-smurfs-genesis-screenshot-language-select](https://user-images.githubusercontent.com/3703317/36197824-326c3034-1175-11e8-898c-1c3c4669f355.jpg)

Many translation like FRENCH are already done on the officiel site.

http://www.cavestory.org/download/cave-story.php

It can be cool if we can use them on your MD port.
Thanks a lot

**Comment by andwn** [comment]
There is ENG/JP currently. Someone else was asking about Russian too. If I can make space or split the ROM per 3-4 languages maybe.

**Comment by Darknior** [comment]
Ok thanks a lot :)
For my part with friends we ask you for French :p 
But if you limit to 4 languages, already with JAP and US, maybe FR :p ... think that in the world many countries speak SPANISH too !

**Comment by SkyTheLeafeon** [comment]
There is a setting under Config that's supposed to change the language to Japanese, but it doesn't seem to do anything.

**Comment by Caio99BR** [comment]
[Just a suggestion, you can ignore now if you desire]

It could be better make a tutorial to `HOW-TO TRANSLATE` or something like it. With this people can make and test things apart and PR just the translation core files (and future make something to split ROM per language).

[Anyway it's just a suggestion, sorry for poor english too]

**Comment by andwn** [comment]
I spent some time over the last few weeks revamping the pipeline to get a bunch of European/Latin languages in the game. When 0.7.0 is released (soon) it'll have French, Spanish and a few more languages. The catch is I use a mapper to fit them that some emulators might not support properly. Before the release I'll make a containment issue thread for problems that come up with translated text because I'm expecting some.

But for now this one is getting closed.

**Comment by bootleg714** [comment]
Is 0.7.0 only going to add language support or will there other fixes added as well? Thanks.

**Comment by andwn** [comment]
There are other changes. Is there... something in particular you had in mind when you asked?

**Comment by bootleg714** [comment]
Nope nothing in particular. I was just curious. I'm going to re-program my eeprom and was going to do 0.6.0 but I'll just wait for 0.7.0. I appreciate all your hard work on this.

**Comment by andwn** [comment]
It's probably not gonna be for a week or 2 because i wanted to fix a few other things (mainly the credits).

Does that eeprom do >4MB? It'll still work if not just, only English and Japanese.

**Comment by bootleg714** [comment]
Yup, the eeprom does up to 4MB games. I use a 27c322 Chip.
