### ISSUE TITLE
Rideable critters

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#209]
Normal critters only do damage when you're "crushed" by them, but they should be damaging from all sides. This also means you can ride them.

**Comment by andwn** [comment]
I've been messing with the player's hurt box. It seems enemies without either "solid" flag hurt the player in a smaller, centered hitbox instead of the usual one. Critters do have a "solid" flag though so something ain't right

**Comment by andwn** [comment]
0.5.1
