### ISSUE TITLE
You can clip through the ground in some places

### ISSUE THREAD

**Issue by diggly** [andwn/cave-story-md#21]
I noticed in Mimiga Village if you walk slowly in certain spots you will fall through the ground.

![clipping](https://cloud.githubusercontent.com/assets/3948320/16898256/fb853622-4b84-11e6-8e5a-9bb802159aa7.png)

It seems to happen on those little hills, but I'm not entirely sure if it happens elsewhere too.
I was playing SNAPSHOT-2016.07.16 with RetroArch's Genesis Plus GX emulator.

**Comment by andwn** [comment]
The word "clip" had me really worried but it's just the slope thing :). I was never able to fix it back when I first got slopes working. May look at it again later but it is pretty low priority for me.

**Comment by andwn** [comment]
This should be fixed now, for floors at least
