### ISSUE TITLE
Weapon-switching lockups

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#211]
The X, Y, and Z buttons seem to stop working after obtaining the Bubbler, forcing weapon-switching to only work with the A button - detrimental to potential speedruns/intense playthroughs
(also affects the map system)

**Comment by andwn** [comment]
You somehow made the game think you are using a 3 button controller. Which emulator/console version?

**Comment by SkyTheLeafeon** [comment]
I was using Kega Fusion v3.64.

**Comment by andwn** [comment]
0.5.1
