### ISSUE TITLE
Non-solid spike tile in Grasstown

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#212]
![image](https://user-images.githubusercontent.com/36712090/36511253-dce4f618-171a-11e8-8afd-f29b04b23721.png)

This happened during a run of the 0.5.0a ROM. Regarding what I said about labeling the ROM that fixes the cursor issue ("0.5.0b"), this could be something you'd do for 0.6.0.

**Comment by SkyTheLeafeon** [comment]
By the way, I used a different emulator this time around. BizHawk (actually Ircluzar's Real-Time Corruptor, but I wasn't doing any corruptions).

**Comment by andwn** [comment]
this might be related to me lowering the hitbox due to an old flaw in my collision code that i fixed recently. will mess with it and compare with the pc version

**Comment by SkyTheLeafeon** [comment]
Gotcha.

**Comment by andwn** [comment]
0.5.1
![blastem_2018-03-17_17-58-16](https://user-images.githubusercontent.com/8164394/37560356-ca47e420-2a0c-11e8-8ea9-83ebd298dfa9.png)
