### ISSUE TITLE
Level 3 missile animations + other animations

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#214]
This includes things like the HUD flashing when the player takes damage, the weapon icon "snapping" to the left/right when swapping weapons, and the very subtle bubble-popping animations when a level 1/level 2 shot from the Bubbler terminates.

Probably something to do in 0.6.0?

**Comment by andwn** [comment]
Some of the special effects are left out on purpose (the game lags enough already, i want to fix that first) and others because i'm lazy. For example most gibs and effects from bullets are missing save for the bullets themselves, the smoke doesn't move and there isn't nearly as much of it, etc.

**Comment by SkyTheLeafeon** [comment]
Right. Maybe this can wait until beta.

**Comment by SkyTheLeafeon** [comment]
...I was sorta thinking that you could potentially accomplish this by porting the entire project to C++ instead of C, but that's up to you.

**Comment by andwn** [comment]
C++ isn't any faster than C. If I were to rewrite sections of the game to improve speed, it would be in the machine's assembly language.

**Comment by sikthehedgehog** [comment]
Besides C++ was being avoided like the plague for games in the 90s for
being *slower* than C... (and more memory hungry)

**Comment by SkyTheLeafeon** [comment]
I was told by a friend that C++ has a wider capability range, but given what you two have said, that's probably incorrect

**Comment by sikthehedgehog** [comment]
It has more features than C, that doesn't mean it's faster (indeed, some of
those features can become bloat instead).

**Comment by SkyTheLeafeon** [comment]
Right.

**Comment by SkyTheLeafeon** [comment]
...I should've stated this earlier: maybe, at the very least, wall collision animations for bullets could be feasible

**Comment by andwn** [comment]
It's feasible, and I have a TODO comment in the polar star code for it.

https://github.com/andwn/cave-story-md/blob/master/src/weapon.c#L456

It's been there forever...one day I'll get around to it, probably.

**Comment by SkyTheLeafeon** [comment]
Gotcha.

**Comment by SkyTheLeafeon** [comment]
Sidenote: the star-like effects for the Polar Star don't just apply to wall collision - they also apply to shot termination and firing. Referred to the WiiWare version - likely present in the PC version.

**Comment by SkyTheLeafeon** [comment]
..OK - in the PC version, those effects are not star-like

**Comment by andwn** [comment]
It's star for fire/termination and diamond for hitting a wall. I dunno if it's really worth the waste of VRAM to have both similar effects graphics loaded.

**Comment by andwn** [comment]
Honestly I should do another playthrough of the game in gens-kmod with the VRAM visualizer open. Then I can actually know just how much space there is and if there are any particular rooms that will break with the additional weapon effects.

**Comment by SkyTheLeafeon** [comment]
Understandable.

**Comment by SkyTheLeafeon** [comment]
By the way, I screenshared a playthrough of v0.5.1a with a friend just a few minutes before this reply. He'll edit it, and then he'll send the video he recorded through a .zip file. We spotted some problems, which I'll report to you.

**Comment by SkyTheLeafeon** [comment]
...OK, the video is worthless due to technical difficulties. I'll still send the screenshots, though.

**Comment by andwn** [comment]
HUD flash: implemented
Weapon icon shifting: won't implement
Bubble popping: implemented
Polar star end/wall effect: implemented (but as the star instead of diamond)
