### ISSUE TITLE
Gun visible in Quote's hand when the Blade is selected

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#215]
Quote isn't supposed to look like he's holding anything when the Blade is selected.
...I suppose I'm a bit on-point.

**Comment by andwn** [comment]
Whoops

**Comment by andwn** [comment]
![blastem_2018-03-17_18-03-04](https://user-images.githubusercontent.com/8164394/37560394-799204e2-2a0d-11e8-996a-d996f765bbca.png)
0.5.1

That bed should be broken though.
