### ISSUE TITLE
(Suggestion) Split "Start Game" into "New Game" and "Continue"

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#218]
Similar to the original PC version

**Comment by andwn** [comment]
That's the way it used to be when there was only one save file (like the PC version). I changed it because I felt this way made more sense.

**Comment by SkyTheLeafeon** [comment]
I see. I'm sorta leaning towards having this port being near-identical to the PC version anyway (you don't have to do that)
