### ISSUE TITLE
Sue moves a little too far to the left in the cutscene at the end of Egg Corridor

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#219]
Title explains itself - she stops moving a little too far to the left of the door at the end of that cutscene

**Comment by andwn** [comment]
I think Jack and Santa also do. This is due to timing adjustments for NTSC. I try to keep the game the same speed whether it is being played on a 50/60 FPS console. 

I changed the way the rounding works since 0.4.0, it used to always be rounded down. Maybe that way turned out more accurate?

**Comment by SkyTheLeafeon** [comment]
I think leaning towards the old rounding method is a good idea.

**Comment by andwn** [comment]
0.5.1
![blastem_2018-03-17_18-33-31](https://user-images.githubusercontent.com/8164394/37560594-b4f9af68-2a11-11e8-9084-16779762d72b.png)
