### ISSUE TITLE
The large flyers in the Egg Corridor have no collision with the player

### ISSUE THREAD

**Issue by EvilTelephone** [andwn/cave-story-md#22]
Emu used: Genesis Plus GX
Rom version: SNAPSHOT-2016.07.16

**Comment by andwn** [comment]
Apparently this enemy's attack is 0 and the AI sets it manually... weird. Need to fix the general behavior too, I mostly copied the other beetles code just to make it move.

https://github.com/libretro/nxengine-libretro/blob/master/nxengine/ai/egg/egg.cpp#L283
