### ISSUE TITLE
Camera stuck on 1st phase of Ballos

### ISSUE THREAD

**Issue by anothernobody** [andwn/cave-story-md#220]
As seen in [https://www.youtube.com/watch?v=w-lJuhuagGM](url)

This bug does not occur if you use the Stage Select for the Seal Chamber.

**Comment by SkyTheLeafeon** [comment]
That link is a 404.

**Comment by anothernobody** [comment]
0.5.0b

**Comment by andwn** [comment]
Been fighting with the Ballos camera for a while. I think it is doing something weird like, trying to lock on to Heavy Press even though it no longer exists.

Not a maybe, this is annoying enough to make a 0.5.1. I'd like to reduce the slowdown this boss had too though.

**Comment by SkyTheLeafeon** [comment]
Understandable, and looking forward to it.

**Comment by kenan1099** [comment]
doesn't seem to happen in the latest nightly (4th of march 2018)

**Comment by andwn** [comment]
Fixed in 0.5.1
