### ISSUE TITLE
Palette of the background in the Seal Chamber is too bright

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#221]
![doukutsu-0_5_0b000](https://user-images.githubusercontent.com/36712090/36762254-8c84ad50-1bd7-11e8-8623-c3bcc495a3cf.jpg)

Also, the BGM for Hell itself could potentially use some work as well. It sounds uncomfortably tinny to me.

**Comment by andwn** [comment]
https://www.youtube.com/watch?v=sxuYL14C1EI ??

It's supposed to be darker but... palettes. I was going to try and replace some of the colors in the 4th palette since only Curly and green devils are using those.

**Comment by SkyTheLeafeon** [comment]
Hmm... I always thought that it'd match the rest of Hell's background. I guess I'm wrong.

**Comment by andwn** [comment]
Apparently the statue room also uses the blue background.

At first I ignored that bit about the music on purpose but should clarify something. I'm not a composer or artist. The source DMF files are in this repository for anyone who wants to improve them. One other thing I was considering was commissioning some of the weaker tracks like Egg Corridor. It's missing a pretty important instrument in the beginning part making it sound way off.

**Comment by SkyTheLeafeon** [comment]
I never noticed that.

**Comment by SkyTheLeafeon** [comment]
---Has this been resolved?

**Comment by andwn** [comment]
I made it lower contrast and got rid of that shitty green color. At this point it's about as dark as I can reasonably make it

**Comment by SkyTheLeafeon** [comment]
Gotcha. I'd assume we'll be seeing what you mean by that once 0.5.1 makes it out.
