### ISSUE TITLE
Mimiga mask run is impossible to complete.

### ISSUE THREAD

**Issue by kenan1099** [andwn/cave-story-md#224]
While doing a mimiga mask run , it is impossible to get past the last cave.
This is because there are some platforms which are impossible to jump without a booster . In the Wii version , fans have been placed but they are not present in this version .

**Comment by Leo40Git** [comment]
This port is based on the freeware version, which is why the fans don't exist.

**Comment by kenan1099** [comment]
Okay, but placing 2 fans wouldn't be hard I'd imagine 
(Idk is it ?)

**Comment by sikthehedgehog** [comment]
I think the problem is mostly not trying to run on Nicalis' toes as they
publish commercial versions pretty much on every official port.

No idea if they'd really care in practice over minor changes from the
freeware version, but I think Grind prefers to play it safe.

**Comment by andwn** [comment]
Gonna add the "no Nicalis features" back to the FAQ..

**Comment by andwn** [comment]
Actually are you sure this is a CS+ only feature? I recall it was possible to beat the game with the mask in freeware, but could be wrong.

**Comment by andwn** [comment]
It's totally there in freeware y'all

**Comment by kenan1099** [comment]
Then just place the fans already. Lol 
Thanks btw

**Comment by andwn** [comment]
Already did but didn't commit the change yet.

**Comment by SkyTheLeafeon** [comment]
Oh, my. What an issue this would've otherwise been!
