### ISSUE TITLE
No mimiga mask sprite when using a teleporter.

### ISSUE THREAD

**Issue by kenan1099** [andwn/cave-story-md#225]
When using a teleporter , quote's sprite is without a mimiga mask when a mimiga mask is clearly obtained and equipped.

**Comment by andwn** [comment]
Ehh just gonna add another set of frames for the Mimiga mask. Probably going to give up on a "real" clipping effect and make most of the larger sprites blink instead.

**Comment by andwn** [comment]
I just double checked before closing this and it isn't fixed anymore 🤔 

Well ok then

**Comment by andwn** [comment]
Finally
![blastem_2018-03-17_23-33-22](https://user-images.githubusercontent.com/8164394/37562316-a44c7720-2a3b-11e8-9a32-175068249a7e.png)
