### ISSUE TITLE
(Suggestion) Debug mode ?

### ISSUE THREAD

**Issue by kenan1099** [andwn/cave-story-md#226]
I think a debug mode should be implemented , a mode which allows to skip most of the game and get to the parts which should be tested (ballos fight , endings , etc)

**Comment by Leo40Git** [comment]
Level select/Warp Zone already allows that.

**Comment by kenan1099** [comment]
Thanks , I just noticed the level select code under the image , tho the arrow characters don't show up correctly (just displays a blank box) so it was very easy to ignore .
Anyways thanks again

**Comment by andwn** [comment]
I'll just replace the arrows with words I guess

**Comment by SkyTheLeafeon** [comment]
Up, up, down, down, left, right, left, right.
