### ISSUE TITLE
(Suggestion) Wind fortress?

### ISSUE THREAD

**Issue by kenan1099** [andwn/cave-story-md#227]
Technically it wasn't originally made by nicalis ,sooooo .
But tbh I think it should be a patch after 1.0 is released.....
(Sorry if it seems like I'm spamming at this point •-•)

**Comment by andwn** [comment]
Assuming someone made/found the PXM, tileset, and TSC files, does this level even work in the original engine?

**Comment by SkyTheLeafeon** [comment]
Doubtful.
I wouldn't bother trying to add it, but perhaps what you could do is add the BGM for it in the sound test, hinting towards how it's unused in the original game.

**Comment by andwn** [comment]
It would require some thinking about beforehand for sure. I've never actually played through Wind Fortress, so don't know what to expect (it might do really wacky things like have ridiculously huge sprites and 200 projectiles flying around at once).

That and I'd like to avoid coming home to a C&D letter, is there any version of CS NOT licensed by Nicalis which contains it?

**Comment by Leo40Git** [comment]
Nope, Wind Fortress only exists in CS+, and _maybe_ a prototype version of Cave Story we don't have access to.

**Comment by SkyTheLeafeon** [comment]
Good to know, and lowkey looking forward to hearing andwn's MD rendition of its track.

**Comment by kenan1099** [comment]
god dammit pixel , why aren't you giving us the beta versions of CS .-.

**Comment by Leo40Git** [comment]
```
> hey bitch release beta cvae story
> now!!!!!tell me what you did to it!

:-|
```
Yes, Pixel actually got this message.

**Comment by andwn** [comment]
Big fan of cvae story here

**Comment by kenan1099** [comment]
@Leo40Git 
I think it is -pretty- clear now why we won't get CS beta ......

**Comment by Darknior** [comment]
WOAW incredible, i never see this level before ... so bad it was removed from the original game :(

http://cavestory.wikia.com/wiki/Wind_Fortress

And creating it from Youtube video will be i pain i think.

https://www.youtube.com/watch?v=xqpLkJ_PQvw
