### ISSUE TITLE
Machine Gun's firing rate is too slow?

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#230]
I should've brought this up earlier. I don't remember it firing as slowly as it does in this port compared to the PC version.

**Comment by andwn** [comment]
The velocity of the bullets (on like every weapon not just machine gun) was also slow. Should be more accurate now.

**Comment by SkyTheLeafeon** [comment]
Understandable.

**Comment by andwn** [comment]
0.5.1
