### ISSUE TITLE
(Suggestion) Pip sounds for dialogue?

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#232]
In the PC version, there's a pip that plays every time a letter appears in the dialogue box, one by one.
You might need to look this up in order to get what I'm trying to say here.

**Comment by andwn** [comment]
My reason on procrastinating on this for so long is mostly because the sound annoys me

**Comment by andwn** [comment]
Well there is an options menu so... I'll add a toggle that is on by default.

**Comment by SkyTheLeafeon** [comment]
Cool.

**Comment by andwn** [comment]
In 0.5.1
