### ISSUE TITLE
No falling sprite?

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#233]
When Quote is falling from a jump, his pose is supposed to change.
I don't know if this has been implemented or not already, but I know for sure that this is present in the WiiWare version and is therefore present in the PC version.

**Comment by andwn** [comment]
Yeah his legs get shorter. Forgot to add it

**Comment by SkyTheLeafeon** [comment]
Doesn't his arm move forward as well?

**Comment by andwn** [comment]
Maybe? It's the other walking sprite where the legs are supposed to be the other way so it would make sense for the arms to be too.

**Comment by SkyTheLeafeon** [comment]
It's as such in the WiiWare version, so...

**Comment by andwn** [comment]
0.5.1
![blastem_2018-03-17_18-27-42](https://user-images.githubusercontent.com/8164394/37560547-eb7a8d9c-2a10-11e8-8d10-6a8d66523544.png)
![blastem_2018-03-17_18-27-48](https://user-images.githubusercontent.com/8164394/37560548-eea59fde-2a10-11e8-9205-186fd6813b65.png)
