### ISSUE TITLE
Air counter and steps are too slow

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#234]
They're a tad slow compared to the PC version.

Then again, the whole port itself seems to run at a speed that's slightly slower than the PC version anyway.

**Comment by andwn** [comment]
When you say the entire game is slower are you actually comparing to the freeware at 50 FPS (all the other issues you mentioned the WiiWare version, so this is why I ask)? I've slowed down the game in NTSC to (mostly) match this speed. All the Nicalis versions are sped up.

**Comment by SkyTheLeafeon** [comment]
Oh, I see.
I've got a little more of a feel for the Nicalis versions anyway.
I suppose I am comparing to the freeware after all.

**Comment by andwn** [comment]
I'll double check the air countdown speed though

**Comment by SkyTheLeafeon** [comment]
Understood.

**Comment by andwn** [comment]
Also, maybe me previous comment was worded confusingly, the speed I am trying to match is that of the PC (as in Pixel's) version. Though supposedly the betas were 60fps and Pixel slowed it down to 50 last minute.

**Comment by SkyTheLeafeon** [comment]
I see.
...It's too bad Pixel never released the betas. Those would've been fun to mess with.

**Comment by andwn** [comment]
Ok it's slightly slower. I entered the water on the MD version first, then in the PC version when the MD one got to 90. MD drowned while the original's counter was at 2 (would have been 10 if they were the same speed).

**Comment by SkyTheLeafeon** [comment]
Gotcha. I think there should be a sound for when the player enters water, like the PC version.

**Comment by andwn** [comment]
I need to stop forgetting to close issues
