### ISSUE TITLE
Sprinkler graphics issue

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#235]
Whoo. Lots of new issues today...

The water droplets that fly from sprinklers are not supposed to appear in pairs. They're supposed to appear as single droplets (single pixels).

**Comment by andwn** [comment]
https://github.com/andwn/cave-story-md/blob/master/doc/DIFFERENCES.md

second bullet point

**Comment by SkyTheLeafeon** [comment]
Understandable.
