### ISSUE TITLE
Item acquisition animation

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#236]
When the player obtains an item, it's supposed to sorta drop into the small box that it appears in.
Like most of the other issues I've posted today, this is compared with the WiiWare version.

**Comment by andwn** [comment]
This one seems easy enough to implement at least 👀

**Comment by SkyTheLeafeon** [comment]
I'm not annoying you, am I?

**Comment by andwn** [comment]
Nah you're fine

**Comment by SkyTheLeafeon** [comment]
Gotcha.
I'm probably doing a good deed by pointing out all these problems anyway.
