### ISSUE TITLE
Enemies continue to move around during the Life Capsule pick-up cutscene/jingle

### ISSUE THREAD

**Issue by EvilTelephone** [andwn/cave-story-md#24]
I haven't been able to get one to actually run in to me to see if they still do damage, though.

In the original game, enemies are paused during the pickup jingle.

Emu used: Genesis Plus GX
Rom version: SNAPSHOT-2016.07.16

**Comment by andwn** [comment]
There is a nuance in the real cave story where sometimes events will stop entities from moving and sometimes they will not. I think it has to do with the <PRI command but I haven't looked much into it since I've yet to see anything break because of it.

**Comment by andwn** [comment]
<PRI is working on 0.2.0, all objects freeze in place
