### ISSUE TITLE
v0.5.1 - Toroko's theme is too quiet

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#240]
It might be missing a few instruments as well.
I won't rush you, though - this can be fixed easily!

**Comment by SkyTheLeafeon** [comment]
Meanwhile, White Stone Wall is sounding... short, but 👌

**Comment by andwn** [comment]
neither are finished, it's the first 10 seconds of the song in a loop. i just wanted to play something other than balcony for people who actually beat hell fast enough

**Comment by SkyTheLeafeon** [comment]
Understandable.

**Comment by SkyTheLeafeon** [comment]
Oh! I've been mistaken this whole time.
King's theme isn't called White Stone Wall. It's just called White.

**Comment by andwn** [comment]
It's internally called white but I thought White Stone Wall was the full name.

**Comment by SkyTheLeafeon** [comment]
Nope. It's just called White.

**Comment by andwn** [comment]
Done it

Toroko https://files.catbox.moe/x8f4kx.ogg
King https://files.catbox.moe/cvf9td.ogg
