### ISSUE TITLE
v0.5.1, second jump to terminal in "Core".

### ISSUE THREAD

**Issue by lolipunk** [andwn/cave-story-md#241]
Can't make the jump to the second terminal in the level "Core" (the one that opens the large door to the boss fight). Water level doesn't permit me to jump high enough.

Using Mednafen v0.9.48.

**Comment by andwn** [comment]
Well shit. I hope fixing this doesn't glitch the water again

**Comment by lolipunk** [comment]
Excellent. This is quickly becoming one of my favourite versions/ports of the game.
