### ISSUE TITLE
v0.5.1 - PCs aren't animated

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#243]
It previously was. This was probably just a small slip-up.

**Comment by SkyTheLeafeon** [comment]
Just realized that this affects literally every PC in the game

**Comment by andwn** [comment]
Nightly should be fixed
https://github.com/andwn/cave-story-md/commit/9284dcdcffab552fd7a064a88f0fbf6a66697a0f#diff-14c9c199f312454b650531cc7fdf547fR456

**Comment by SkyTheLeafeon** [comment]
I think I'll wait until v0.6.0 (is that what's next? if not, 0.5.2) to confirm this. I like to rely on the releases instead of the nightly.

**Comment by SkyTheLeafeon** [comment]
Fixed in v0.5.2
