### ISSUE TITLE
Polar Star description text doesn't display properly

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#244]
![image](https://user-images.githubusercontent.com/36712090/37435710-a19d66ca-27a1-11e8-98c0-135045a51e85.png)

Note how the name "Polar Star" isn't shown, whereas choosing the other weapons properly displays their names.

**Comment by andwn** [comment]
There was an extra carriage return in the script for some reason, so it pushes "- Polar Star -" past the top of the message.

**Comment by SkyTheLeafeon** [comment]
Hmm.

**Comment by andwn** [comment]
Seems fixed now
