### ISSUE TITLE
Small textbox VRAM error

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#245]
![image](https://user-images.githubusercontent.com/36712090/37435986-0261784c-27a3-11e8-97cd-0805d3899cbb.png)

I'm talking about that small tile outside the textbox. That's not supposed to be there, and this seems to happen with every instance of dialogue in v0.5.1.

**Comment by andwn** [comment]
Something Sue says in the cutscene where she is on the computer with Kazuma is 2 letters too long and goes off there. I think it gets cleaned up if you pause but not sure. It's happened forever. Every so often I notice a line of text too long and have to change the TSC to fix it.

**Comment by SkyTheLeafeon** [comment]
Ah.

**Comment by andwn** [comment]
This particular instance of it is fixed and I haven't noticed another yet so closing
