### ISSUE TITLE
Can still get stuck in a wall in Grasstown Hut

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#246]
![image](https://user-images.githubusercontent.com/36712090/37436052-53003cd4-27a3-11e8-9ad9-bd4dedc70d05.png)

Argh.

**Comment by SkyTheLeafeon** [comment]
v0.5.1.

**Comment by andwn** [comment]
Why is it always this wall, I even put a check in to push the player out if the centerpoint is somehow in the wall. There must be something about that enemy.

**Comment by SkyTheLeafeon** [comment]
Hitbox issue, perhaps? Hmm...

**Comment by andwn** [comment]
Maybe the Ravil is a "brick" type solid instead of a "mushy" one like most other enemies are. Will have to look into it eventually.

**Comment by SkyTheLeafeon** [comment]
OK.

**Comment by andwn** [comment]
That enemy is definitely solid. It doesn't need to die at that spot either, it just pushes you in alive. I disabled that locally but haven't committed it yet. Anyway continue the discussion in #189 since it's still open

**Comment by SkyTheLeafeon** [comment]
Gotcha.
