### ISSUE TITLE
Nikumaru counter doesn't stop in Ballos conversation

### ISSUE THREAD

**Issue by anothernobody** [andwn/cave-story-md#248]
Rather self-explanatory.

As tested in v0.5.1a

**Comment by SkyTheLeafeon** [comment]
Imagine how many timeattack records that'd invalidate...

**Comment by andwn** [comment]
new category

Think my mistake is that the counter should be stopped whenever a script is running, not just when the script freezes gameplay (it's not frozen while talking to Ballos or the ghost puppy since animations are still going).

**Comment by Leo40Git** [comment]
The <KEY command should also stop the Nikumaru Counter.

**Comment by Leo40Git** [comment]
Message window check's redundant, since you never see a message without either <PRI or <KEY being active.
Also, yes, <KEY is the command that locks player control.

**Comment by andwn** [comment]
Working now
