### ISSUE TITLE
Invisible tiles issue.

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#25]
In vanilla CS there are invisible tiles that can be destroyed by shooting them enough times. After these tiles are destroyed a heart will appear.

In this port the invisible tiles are still present, but are invincible, they absorb the shots, but are never destroyed. Not only that, but if you move over the invisible tile you will pick up the heart regardless of whether or not you shot the tile.

Here's an image for reference:
http://i214.photobucket.com/albums/cc164/andwhyisit/invisibletile_zpsugbmzjnl.gif

The heart represents where the hidden tile is located (it's also what you see after destroying the tile).

Here are save files for both this port and the pc original that place you in that exact room:
https://www.mediafire.com/?5i90jlgezgxzza4

This is based on the 2016.07.16 snapshot, so let me know if this issue has already been resolved.

**Comment by andwn** [comment]
This must be what the "hidden heart/missile" in the NPC table is. Not knowing what it was, I just gave it the AI routine I already wrote for regular hearts, so that is why you were able to pick it up. Will fix it in the next release.
