### ISSUE TITLE
Oddly placed door to Jail No. 2 in Plantation

### ISSUE THREAD

**Issue by anothernobody** [andwn/cave-story-md#250]
![doukutsu-v0 5 1a001](https://user-images.githubusercontent.com/36806115/37498507-68581c96-2884-11e8-83a4-3f782605869b.png)

There's a door that leads to Jail No.2 in the square Quote is standing on.

As tested in v0.5.1a

**Comment by andwn** [comment]
Apparently, that door is there in the original, just impossible to activate.

![caveeditor_2018-03-15_21-24-00](https://user-images.githubusercontent.com/8164394/37498931-5df86d56-2897-11e8-9d99-4f91bb21b79f.png)

My check for overlapping with objects when pressing down lets the player be a bit farther away than the original so I guess it needs to be made more strict.

**Comment by andwn** [comment]
You know what I'll just... remove the door it's easier.

**Comment by SkyTheLeafeon** [comment]
I wonder if that frees up anything.

**Comment by andwn** [comment]
About 64 bytes of memory and a few clock cycles that don't matter because that section wasn't lagging 🤷‍♂️

**Comment by SkyTheLeafeon** [comment]
Ah, cool. 64 bytes is at least something.

**Comment by SkyTheLeafeon** [comment]
Perhaps this can be done with any other unused stuff as well?

**Comment by andwn** [comment]
Oh right, I removed the door but didn't close this
