### ISSUE TITLE
Critter gets stuck in the ceiling in the First Cave

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#251]
https://im4.ezgif.com/tmp/ezgif-4-eb5fbf2524.gif
I can't believe this got past me. This happened in v0.5.1a, and it left me in stitches. XD

**Comment by andwn** [comment]
This is a result of my attempt to optimize Critter behavior and collision, since they were contributing to some of the lag in Grasstown. Messed up ceilings I guess.

**Comment by SkyTheLeafeon** [comment]
...And the link to that gif expired. Oh, well.

**Comment by andwn** [comment]
So reason for this was that the ceiling collision wasn't checking slope tiles, but the floor collision was. So the critter went inside the slope so far that it thought it was a floor when it started falling.
![blastem_2018-03-18_10-12-15](https://user-images.githubusercontent.com/8164394/37566867-2daa4958-2a95-11e8-8016-3b475444df04.png)

**Comment by SkyTheLeafeon** [comment]
Ah-ha!
