### ISSUE TITLE
A couple things about the "?" that appears over Quote's head when checking nothing

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#252]
I'm not sure if multiple of them are allowed on-screen, but I don't think multiple should appear by rapidly tapping down in one spot.
Also, it should move up faster, and it should vanish quicker.

**Comment by andwn** [comment]
Just made it so there is one at a time. Didn't change the other things yet.

**Comment by SkyTheLeafeon** [comment]
OK.

**Comment by andwn** [comment]
Sped up for 0.6
