### ISSUE TITLE
Frenzied Toroko graphics problem

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#255]
https://cdn.discordapp.com/attachments/390712715196235778/425472871905624064/cavestorygenprob1.gif

This happened during that screenshared playthrough I mentioned earlier.
One out of... I don't know, actually.

Also, we've reached a full two-bit hexadecimal byte in terms of the numbers of the issues.
This is the 255th one - literally FF in hex!

**Comment by Leo40Git** [comment]
Sprite's taller than it actually is, so it's going beyond Toroko+'s graphics and using King's graphics.

**Comment by andwn** [comment]
Another one I've been procrastinating looking into. Maybe I changed the size of the sprite by accident, or Toroko thinks a random other object is a block. This has happened before with the "level up!" text as well. Toroko tried to throw it like a block I think. It was as hilarious as it sounds, until I realized I had another bug to fix.

**Comment by Leo40Git** [comment]
Boss concept: Steals HUD elements and throws them at you.

**Comment by andwn** [comment]
Funny you say that actually

http://gendev.spritesmind.net/forum/viewtopic.php?f=19&t=2452

That and the Ironhead health bar issue I forgot to screenshot whoops.

**Comment by andwn** [comment]
Turns out the reason is I set the Toroko+ object to use 2 (hardware) sprites but she isn't large enough that it's necessary, so what you said turned out to be pretty accurate.

Why this wasn't happening before 0.5.0 is a mystery, since I'm sure the mistake was always there.
