### ISSUE TITLE
Omega's legs are misaligned

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#257]
Should've mentioned this earlier

**Comment by SkyTheLeafeon** [comment]
I'll be specific about it.
Omega's legs are positioned off to the right, and they shouldn't be.

**Comment by SkyTheLeafeon** [comment]
Also, don't they move horizontally when Omega gets close to walls?

**Comment by andwn** [comment]
The legs are centered now but I'm not going to mess with wall movement
