### ISSUE TITLE
Balfrog sprite problems

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#258]
![cavestorygenprob3](https://user-images.githubusercontent.com/36712090/37693675-8bcb6522-2c7e-11e8-9e11-74d1773a9bcd.gif)

Third problem sighted in that run I mentioned.
This only seems to happen while holding A.
Also, maybe change the line saying "Fought off Balrog!" to "Defeated Balfrog!"?

**Comment by andwn** [comment]
Well the options here are

- Slow down every flicker in the game to 30 fps instead of 60
- Disable fast forward

All the text in the game is from the Aeon Genesis translation. The PC version says "Fought off Balrog!" too. The doctor also says "I feel like a superman" before the Undead Core fight too. I hate that line but kept it in.

**Comment by SkyTheLeafeon** [comment]
Hmm... There's gotta be more to this than just those two options.

**Comment by andwn** [comment]
The thing is there are other objects that blink. Anything that does during a scene will have this happen while holding A.

**Comment by andwn** [comment]
There might be less than I thought though.
![code_2018-03-21_20-06-25](https://user-images.githubusercontent.com/8164394/37744469-b87ef260-2d45-11e8-8222-688804756c48.png)

**Comment by SkyTheLeafeon** [comment]
OK.
I did a second screenshared run of 0.5.1a earlier today - no-save run, died - but my friend who made the gifs I posted spotted a few new issues, which I'll get to you as soon as he gets the gifs to me.

**Comment by andwn** [comment]
I see a commit from a while ago with "Make (most?) flickering sprites flicker a bit slower #258" and didn't notice any lack of flickering (except when Misery teleports the Core away, but fixing that now)
