### ISSUE TITLE
Second boss meter in place of "Main Artery" in Main Artery

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#259]
https://cdn.discordapp.com/attachments/390712715196235778/426186920507342858/cavestorygenprob4.png

Happened during the second screenshared run of mine.

**Comment by andwn** [comment]
This one is fixed, but not in 0.5.1.

**Comment by SkyTheLeafeon** [comment]
This was in 0.5.1a.

**Comment by andwn** [comment]
They are the same except one line of code to change the water position in Core.

**Comment by SkyTheLeafeon** [comment]
Ah-ha...

**Comment by SkyTheLeafeon** [comment]
Doesn't seem to explain why it's double-layered though

**Comment by andwn** [comment]
I "fixed" this by hiding the name, figured it wouldn't be a big deal
