### ISSUE TITLE
Getting to Mahin (player physics issue)

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#26]
That 1 tile high gap you go through to get to Mahin in Mimiga Village is much harder to get through than in vanilla CS.

In vanilla CS:
http://i214.photobucket.com/albums/cc164/andwhyisit/GIF_zpsbl0iglbi.gif

In MD CS:
http://i214.photobucket.com/albums/cc164/andwhyisit/GIF2_zpskqjhbmlk.gif

This also seems to be an issue with running over 1 tile gaps in that you don't fall into them unless you are going crazy slow.

**Comment by andwn** [comment]
My collision code is now a complete mess. Try this: https://my.mixtape.moe/xqzvgs.bin

I may have inadvertently broken other things and want to play through the game again before releasing.

**Comment by andwhyisit** [comment]
Confirmed as working from my own tests.
