### ISSUE TITLE
Warehouse door artifact

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#260]
https://cdn.discordapp.com/attachments/390712715196235778/426188878378958848/cavestorygenprob5.png

Also happened in that second screenshared run.

**Comment by SkyTheLeafeon** [comment]
Did a few more runs. This has been recurring. All of these runs were no-save runs.

**Comment by andwn** [comment]
Where do I get the patience to play through this game those many times 😮

**Comment by SkyTheLeafeon** [comment]
I think it's just because I'm sorta the opposite of you in that matter. Though I'm not a very patient person, I'm actually very good at Cave Story. Granted that I stay focused, I can easily beat the game and get the best ending in one day.

**Comment by andwn** [comment]
I've only learned the speedrun up to Omega. Something about the Sand Zone fetch quest just feels like a drag. Should probably get to learning that part so I can get it over with faster.

Gonna get to that door eventually..

**Comment by SkyTheLeafeon** [comment]
Gotcha.
...I can handle a no-save run up until the point in the Prefab Building just before Hell. I haven't gotten there in this port yet, but I'm aiming to.

**Comment by SkyTheLeafeon** [comment]
...Something like two days ago, I managed to get all the way up to that aforementioned point in v0.5.1a. I can easily say that Hell is intact, but sorta broken and flawed. That can be remedied, however.

**Comment by andwn** [comment]
Should be fixed, at least I'm not seeing it happen anymore
