### ISSUE TITLE
Double-layered Core water

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#261]
https://cdn.discordapp.com/attachments/390712715196235778/426189463849533441/cavestorygenprob6.png

From the second screenshared run.
Turns out I'm just getting images instead of gifs.

**Comment by andwn** [comment]
Was this being played on a PAL console? This was happening before on PAL and I thought I fixed it but maybe not.

**Comment by SkyTheLeafeon** [comment]
Nope. This was being played in NTSC, on Fusion 3.64.

**Comment by andwn** [comment]
![vlc_2017-10-22_18-23-47](https://user-images.githubusercontent.com/8164394/37751816-e39775ba-2d6a-11e8-8536-f6236e7a7373.png)


This water background is the worst. Even now playing through it again it won't happen. Was it like that the entire time you were in that room or just in that cutscene? Maybe the camera moved up while the water moved down fast enough and something about that caused it?

**Comment by SkyTheLeafeon** [comment]
The entire time.

**Comment by SkyTheLeafeon** [comment]
You might also want to take a look at #239 - that's kinda important

**Comment by andwn** [comment]
Are you sure you linked the right issue? #239 is the one where you listed a bunch of visual differences like water drops and damage numbers following objects.

**Comment by andwn** [comment]
And if that only happened during the cutscene I am thinking maybe the Y value it draws the surface on is slightly off between the top and bottom of the screen. An easier way to test that could be to see at what point the game considers the player underwater, comparing after the water surface rises from the bottom and after it descends from the top (if the air counter appears when just quote's feet are touching, or not until he is completely submerged). I will have to try this out later.

**Comment by SkyTheLeafeon** [comment]
Yes, I linked the right issue. I had posted a reply to your reply, pointing a few things out and specifying what I meant.

**Comment by andwn** [comment]
0.8.0
Definitely should not happen now and I can't get it to myself.
