### ISSUE TITLE
Critter flight speeds and effects in Grasstown

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#265]
I think the green ones are supposed to be a bit faster, and I think the larger, blue ones are supposed to make the screen shake when they land (plus the thudding noise.) Also, their animations are very slow despite being present - easy fix, I think. ...Lastly, I think the blue ones use a different sound when jumping.

**Comment by andwn** [comment]
Comparing with this video, I think the only thing right about this issue is the thud/shake, so I've added it in.
https://youtu.be/EUXEmc3P2fc?t=136
