### ISSUE TITLE
Small VRAM error

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#266]
Something similar happens when obtaining the Bubbler. Look at the door.
![bandicam 2018-03-25 10-53-25-057](https://user-images.githubusercontent.com/36712090/37878254-d8095f9e-301a-11e8-81b8-d13300f0ddc9.jpg)

**Comment by andwn** [comment]
![firefox_2018-03-25_14-36-14](https://user-images.githubusercontent.com/8164394/37878614-ea88f778-3039-11e8-8191-05d4d6944813.png)

**Comment by SkyTheLeafeon** [comment]
Fuck doors?
...OK, then.

**Comment by andwn** [comment]
I thought this was just some one off thing that would be hard to reproduce, but it's actually consistent, specifically right before Sand Zone. I think it's the sprite tile per line limit. Maybe I can move the warp options up 8 pixels to avoid overlapping with all the characters.

**Comment by andwn** [comment]
Actually, I guess it should be a lot higher up anyway
![image](https://user-images.githubusercontent.com/8164394/88473084-ffa51e80-cee7-11ea-9453-c139e50c1252.png)
