### ISSUE TITLE
Curly boss problem

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#267]
Curly's palette changes slightly when she reveals her gun before the fight against her. I don't think this is supposed to happen. Her position changes slightly as well, which also shouldn't happen.
![bandicam 2018-03-25 10-56-28-248](https://user-images.githubusercontent.com/36712090/37878283-5a3c458a-301b-11e8-9c95-b7d397ce1b6d.jpg)
![bandicam 2018-03-25 10-56-37-871](https://user-images.githubusercontent.com/36712090/37878284-5e08148c-301b-11e8-89f1-23d19d2e3086.jpg)

**Comment by Leo40Git** [comment]
Yeah, eyes are different.
...which is odd, since they're both using palette line 3. Must be a difference in the sprite itself.

**Comment by andwn** [comment]
At least I can update the color of all the eyes in that sprite in one go instead of individually.

**Comment by SkyTheLeafeon** [comment]
@Leo40Git Her hair's color changes slightly as well. Very subtle.

**Comment by andwn** [comment]
The color of Curly's antennas was fixed a long time ago but I forgot to actually close this
