### ISSUE TITLE
Missing door in the Labyrinth

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#268]
![bandicam 2018-03-25 12-32-27-379](https://user-images.githubusercontent.com/36712090/37879149-9ed83598-3028-11e8-946c-d5b3473d0ec3.jpg)

Fuck doors?

**Comment by Leo40Git** [comment]
FCKDOORS.

**Comment by SkyTheLeafeon** [comment]
Also, that robot off to the right is using the wrong sprite.

**Comment by andwn** [comment]
Oh, this explains the other door issue actually. The black area in the door frame used to be transparent. Guess I need to make sure the double doors are drawn on top instead of underneath.

Here is some good anti-door entertainment meanwhile https://www.youtube.com/watch?v=4p9_GxicLlw

**Comment by SkyTheLeafeon** [comment]
Doors have apparently become a meme among us. XD

**Comment by SkyTheLeafeon** [comment]
Patched in v0.5.2. Diddle diddle dee dee door.
