### ISSUE TITLE
Faults in Hell

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#272]
I've noticed that every location name except for the one at the very beginning of Hell is completely missing. Also, Curly doesn't seem to fire her Nemesis from time to time, and that's kinda sporadic in terms of frequency. The bullets from that also look weird.

Also, accessing the Seal Chamber via Warp Zone results in Curly being invisible until the player triggers the final boss battle. Minor, but that's something to look at.

**Comment by andwn** [comment]
Curly has to share the same bullet array as the player, and sometimes there is not enough room. The nemesis sprite issue has been mentioned previously.

The last bit is a workaround for level select only because previously Curly didn't appear *at all*, and I'm not too concerned about cheat codes being off somewhat.

**Comment by SkyTheLeafeon** [comment]
Right. Because the player's not really supposed to cheat in the first place.

**Comment by SkyTheLeafeon** [comment]
What about the location names?

**Comment by andwn** [comment]
I'm not sure what you are talking about with the location names. The only one missing for me is B3, and looking at the script of the original game, there is no <MNA in the event that starts with the room (95).

![caveeditor_2018-04-11_12-53-42](https://user-images.githubusercontent.com/8164394/38631342-81ca3c82-3d87-11e8-8c55-046d76733206.png)
![caveeditor_2018-04-11_12-54-00](https://user-images.githubusercontent.com/8164394/38631347-8616878c-3d87-11e8-9f17-f8044b543594.png)
![caveeditor_2018-04-11_12-54-27](https://user-images.githubusercontent.com/8164394/38631351-88885220-3d87-11e8-8ae3-d6c94576a4da.png)
![caveeditor_2018-04-11_12-53-17](https://user-images.githubusercontent.com/8164394/38631355-8bbcf78e-3d87-11e8-9f77-1cef2c1273a0.png)

**Comment by andwn** [comment]
I played through Hell a couple times today.

B1: Name shows up
B2: Name shows up
B3: No name
Passage?: No name when entering from the top, but shows up when coming back from the statue room
Statue Room: Name shows up
Corridor: Name shows up
Seal Chamber: Name shows up

This seems to match the original
https://youtu.be/VJbTX21TeNM?t=65
