### ISSUE TITLE
Nemesis projectile goes through walls

### ISSUE THREAD

**Issue by anothernobody** [andwn/cave-story-md#273]
![wvga](https://user-images.githubusercontent.com/36806115/38221359-4bc8dd38-369c-11e8-94cb-311626ed6a39.gif)

It shouldn't be able to go through walls.
It also needs to be able to pass through enemies IIRC.

As tested in v0.5.1a

**Comment by SkyTheLeafeon** [comment]
Uh-oh.

**Comment by andwn** [comment]
I thought it went through walls for some reason idk. Passing through enemies without spamming damage to them every frame is probably possible to implement without lag... each bullet coukd keep a list of enemies it already hurt or something.

**Comment by SkyTheLeafeon** [comment]
Hmm.

**Comment by andwn** [comment]
Like, half fixed now. It still spams damage on some enemies instead of damaging them once. Juse need to make the bullets remember more than one enemy I guess.

**Comment by andwn** [comment]
Should be good now apart from the graphic messing up occasionally
