### ISSUE TITLE
Booster glitches

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#275]
When boosting onto the upper edges of the Ravils and the Igor Lookalike on the Balcony at precise points (might work on other enemies), the player can boost infinitely as long as they hold the jump button.
Tested in 0.5.1a. I'll send a video to your email in order to prove this.

**Comment by SkyTheLeafeon** [comment]
It's also evident that this can cause the player to go through slopes.
Heck. By boosting downwards, holding down for a moment, and then releasing down just before moving towards a slope right next to Quote causes Quote to go through that slope.

**Comment by andwn** [comment]
How the hell does that even happen.. maybe something causes the booster fuel to decrement multiple times and skip 0, and then it becomes 65535.

**Comment by SkyTheLeafeon** [comment]
Hmm... Weird, is it not?

**Comment by andwn** [comment]
I feel like this issue needs a galaxy brain image but instead here is a rave review

![firefox_2018-04-06_22-34-08](https://user-images.githubusercontent.com/8164394/38450377-c1ca4b74-39ea-11e8-8150-5bc093f60a65.png)

**Comment by SkyTheLeafeon** [comment]
Oh, god. XD

**Comment by SkyTheLeafeon** [comment]
Patched in v0.5.2.
