### ISSUE TITLE
Problem with the note left by Booster in the Prefab Building

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#276]
Shouldn't each part of it appear instantly? ...I might've forgotten.

**Comment by andwn** [comment]
There is actually a minor issue with either <TAN or <SAN or <CAT where the last line of text is not instant. Didn't look into it very deeply because I didn't think it was a big deal.

Speaking of minor things in the prefab building I still need to add the broken bed sprite.

**Comment by SkyTheLeafeon** [comment]
I didn't notice that.

**Comment by andwn** [comment]
Fixed for next release. Turns out both <CAT and <TUR are supposed to last until <END or <CLO, not just one of them.
