### ISSUE TITLE
Nikumaru counter should not keep counting when paused in Hell

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#278]
Self-explanatory.

**Comment by andwn** [comment]
Fixed in nightly but not release (I noticed it while fixing #248)

**Comment by SkyTheLeafeon** [comment]
Alright. Looking forward to 0.6.0/0.5.2.

**Comment by andwn** [comment]
I'm gonna start tagging these cause it's hard for me to tell at a glance what is ready for the next version and what still needs to be done.

**Comment by andwn** [comment]
Both counter issues fixed
