### ISSUE TITLE
More Faults in Hell

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#279]
The exploding doors that you have to shoot in order to get past can't be hit at point-blank range for some reason.
The hitboxes of the Presses are kinda off.
The Butes in the second room aren't supposed to be immediately visible (same with the flies around the Egg Observatory in the Egg Corridor, strangely).
The parts of the walls that turn to smoke leave behind artifacts.
The Rollers in the third room don't appear to do anything when offscreen.
Shouldn't Curly smoothly shift from one position to the other?

Was unable to test past Heavy Press. Kept dying - argh, gotta keep practicing even though I'm normally good at Hell.

**Comment by SkyTheLeafeon** [comment]
I've never been able to get past Heavy Press, but I think that's just because I haven't been going through Hell properly.

**Comment by SkyTheLeafeon** [comment]
...OK. I actually made it to Ballos, barely alive.
I really need to practice. ...Either that or wait till 0.6.0 since Ballos is technically broken.

**Comment by andwn** [comment]
These two aren't fixed yet. I'm going to make separate issues for them

"The exploding doors that you have to shoot in order to get past can't be hit at point-blank range"

"The parts of the walls that turn to smoke leave behind artifacts"
