### ISSUE TITLE
Error when going through the door to the save room in the starting cave.

### ISSUE THREAD

**Issue by EvilTelephone** [andwn/cave-story-md#28]
I was leveling Polar Star off those first few hopping guys and going in and out of the door to respawn them. After 7 or 8 door usages, this error occurred. Note that I've done this same leveling process in previous builds and not had an error. Could be a coincidence.

ROM used: SNAPSHOT-2016.07.26
Emu used: Genesis Plus GX

![retroarch-0727-160737](https://cloud.githubusercontent.com/assets/539616/17190693/cf097480-5414-11e6-8720-60cc0970eb83.png)

**Comment by andwn** [comment]
What version of the emulator on what OS? I tried Genesis Plus GX, Gens GS, Kega Fusion and Regen on Linux and am unable to reproduce.

I'd try on real hardware but my system has been crashing a lot lately even on retail games.

**Comment by EvilTelephone** [comment]
Genesis Plus GX v1.7.4
Windows 10

I'll see if I can re-create the error on my Android tablet running Genesis Plus GX.

**Comment by andwn** [comment]
I still don't know why this happened but never ran into it. During the time this was reported I was building SGDK with -O3 because I'm an idiot. Either it has something to do with that, or it was a fluke.
