### ISSUE TITLE
No "Empty!" effect for Machine Gun & Bubbler being out of ammo

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#281]
All weapons with ammo should show the "Empty!" effect if they're out of ammo.

**Comment by andwn** [comment]
At least it should be easy to get this on the rest of the weapons now that the missiles have it.

**Comment by SkyTheLeafeon** [comment]
I mentioned this in #263 already, but OK.

**Comment by andwn** [comment]
That one only mentioned the missile launcher. So I only added the effect for the missile launcher at first.

**Comment by SkyTheLeafeon** [comment]
Ah-ha...

**Comment by andwn** [comment]
Just confirmed this one too, got "Empty!" for all 3 now
