### ISSUE TITLE
A few (practically just one) minor problems with Monster X

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#285]
The green fish-like things it fires at you shouldn't immediately home in on the player. As they currently are, Monster X is a bit of a choke in the MD version. There are also the Booster-like effects that trail behind them, but those might be one of the things you're purposefully omitting.

**Comment by andwn** [comment]
There are trails on them and they home in more slowly so I must have read this, implemented it, and never responded
