### ISSUE TITLE
Looks great! Can we distribute it?

### ISSUE THREAD

**Issue by hizzlekizzle** [andwn/cave-story-md#29]
This looks really fantastic so far! We recently added an area in RetroArch for downloading freeware and homebrew content for various libretro cores and were wondering if you would mind us adding it to the list.

I see that it's GPL v3 but wanted to ask first anyway :)

**Comment by andwn** [comment]
Go right ahead. I haven't seen the interface for this but is there some way to make sure the people downloading know it is a work in progress?

Well I could just add a splash screen thing too.

**Comment by andwn** [comment]
Yeah splash screen it is
![Image](https://my.mixtape.moe/shgnhi.png)

NXEngine is in there too that's interesting.

**Comment by hizzlekizzle** [comment]
Sweet, thanks :)

I can add (WIP) or "pre-alpha" or something like that to the title, if that's clear enough, but yeah, splash screen would be great, too, if you're up to it.

**Comment by andwn** [comment]
(WIP) is clear enough. As long as people don't download it expecting the full game and get mad when it breaks, especially with a completed Cave Story already existing in there.

I'll work on adding a splash screen for the next release though.

**Comment by hizzlekizzle** [comment]
Cool, no problem. Most of the content we have up there is incomplete/shareware or utility (like controller tests and 240p test suite), so it won't be out of place at all.

Thanks again!
