### ISSUE TITLE
Door to Jail No. 2 in Plantation should look like an open doorway

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#293]
Self-explanatory.

**Comment by andwn** [comment]
Ok so I get that this is different but how does it negatively impact the game?

**Comment by SkyTheLeafeon** [comment]
Accuracy... _please don't tell me off._

**Comment by andwn** [comment]
??? 

Ok I think it's real talk time.

You've found a few major things that I wasn't aware of and I'm thankful you brought them to my attention. But please... slow down, especially with little details like this. I'm at the point where I don't even want to work on this project anymore, but it's taken 3 years so far and I just want to be able to say it's finished.

The goal of this project wasn't to make the NXEngine of MegaDrive, it was to teach myself gamedev and MegaDrive dev. It achieved that goal in 2015, but then people found it, and spread it around the internet, and now hundreds of people I don't know are egging me on to finish it.

**Comment by andwn** [comment]
I was going to say something about focusing on major issues but I hit send early amd probably said it before anyway

**Comment by SkyTheLeafeon** [comment]
I'm sorry. You have my utmost apologies.

I think it's needless to say that the door to the Prefab Building before Hell has the same aforementioned issue. But, I'm gonna shut up now.

**Comment by andwn** [comment]
The last 10% are the hardest I guess. Just some things that have been getting under my skin lately, like someone selling bootlegs of old buggy builds. Can't imagine how this would be with deadlines and paying customers.

**Comment by SkyTheLeafeon** [comment]
Oh, word?!
It's been a while! I'm looking forward to what's next.

**Comment by andwn** [comment]
I thought I was stupid for a hot minute, but get ready for some fun. 

So simple mistake, I made it so the door was invisible when facing right, but I didn't make the Option 2 flag have it face right. Wow, it's so easy, I just have to fix that and it'll hide the door.

Nope, not good enough. The map has no door frame at that location, so now it's completely invisible. So actually, the door sprite itself also has to have an open door frame, making those map tiles for door frames redundant in most cases.
