### ISSUE TITLE
Can't reach the core without any booster or machine gun

### ISSUE THREAD

**Issue by Lizstar64** [andwn/cave-story-md#299]
Hey! I'm playing the game on an Everdrive on an NTSC Genesis, and was working towards getting the Spur. However, upon reaching the Core Chamber, I found that I can't make the jump to unlock the final lock without using the machine gun, the water keeps me from jumping properly every time. It seems like the water is just a little too high.

Am I just missing something, or is this a bug?

**Comment by andwn** [comment]
See #241 and make sure you are on 0.5.1a

**Comment by SkyTheLeafeon** [comment]
You're just missing something, really. Use the latest release.
@andwn Hey, what's the holdup?

**Comment by andwn** [comment]
burnout. im sick of working on this (because when i do, all my free time ends up going to it). ill probably stop hating it in a few months like i usually do

**Comment by Lizstar64** [comment]
Ugh, I totally looked through the issues looking for this problem too. I looked really thoroughly! Sorry everyone, thanks for the help!

**Comment by SkyTheLeafeon** [comment]
@andwn It never hurts to take a break.

**Comment by ijacquez** [comment]
@andwn That's usually how it goes.
