### ISSUE TITLE
SRAM field in the header is wrong

### ISSUE THREAD

**Issue by sikthehedgehog** [andwn/cave-story-md#3]
The SRAM field in the header is not valid. Some emulators *do* pay attention to it and will not make the savegame functionality work properly since Cave Story is not in their list of exceptions (BlastEm happens to trip over this).

The entire header could use being updated but this is the most critical part.

**Comment by andwn** [comment]
I don't know how this works at all but guessing change type to 0xF820, address to 0x200001 and end address to something larger at 0x200001 + some power of 2.

By the way I have been wondering what should be used as the serial number. There is not any agreed upon format to follow that I know of. Putting a date like 20160706 works but that'll collide if 2 games are released same day (eg. bitbitjam).

**Comment by sikthehedgehog** [comment]
It doesn't even declare the existence of SRAM.

Changing the 12 bytes of the SRAM field to this seems to work (asm but you get the idea):

        dc.b "RA", $F8, $20
        dc.l $00200001, $0020FFFF

That'd declare 32KB of SRAM at odd addresses (the usual setup), dunno if that size is correct. It's what most emulators and flashcarts support however.

As for the serial number... I don't think there's anything =D My suggestion would be to take the copyright abbreviation (the four letter code), slap a hyphen, then three digits. That should give you room for 1000 games while being unlikely somebody else uses the same serial number. (also note that it should *not* change between builds - that's what the revision number after that is for)

**Comment by andwn** [comment]
Forgot to mention this new header

https://github.com/andwn/cave-story-md/blob/master/src/boot/rom_head.c
