### ISSUE TITLE
Mannan health issue

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#30]
Mannan, those tombstone shaped enemies from Grasstown, they have too much health. There are certain enemies in Cave Story that die before their HP total is reached. For instance Mannan is listed as having 100 hp, but it dies after 11 damage or greater.

Other examples of this behaviour to watch out for:
Polish is listed as 120 HP, but splits up at 20 or more damage.
Gaudi/Armor is listed as 1000 HP, but dies at 15 or more damage.
Gaudi Egg is listed as 100 HP, but dies at 11 or more damage.
Buyobuyo base is listed as 1000 HP, but dies at 61 or more damage.
Dragon Zombie is listed as 1000 HP, but dies at 51 or more damage.
Bute is listed as 1000 HP, but dies at 4 or more damage.
Mesa is listed as 1000 HP, but dies at 64 or more damage.
Deleet is listed as 1000 HP, but dies at 31 or more damage.
Toroko (before first Balrog fight) had the same behaviour, but you've already addressed Toroko.
Sue (1000 HP, 501 damage to die) and Misery (1000 HP, 601 damage to die) from the Undead Core fight share this behaviour as well.

**Comment by andwn** [comment]
Sounds like all the non-bosses that do something other than just explode. Thanks for listing those out. I'll fix Mannan and Polish in the next release.

**Comment by andwn** [comment]
The HP for all the enemies so far (except Omega) is correct now in 0.2.0
