### ISSUE TITLE
Polar Star shoots fully upgraded shots in Hermit Gunsmith

### ISSUE THREAD

**Issue by NasrinAtiyeh** [andwn/cave-story-md#300]
Even at Lv 1, it shoots fully upgraded in that room. Re entering the room does not fix it.
Using the nightly release.

**Comment by andwn** [comment]
I think the reason for this one is that in the rooms where you "trade" weapons I load the graphics for both weapons, but Spur's graphics do a special thing where it not only loads it's own laser beams, it also loads Polar Star Lv 3 (so you can fire pea shots while a laser is still there). Will have to make some kind of spacial case for this room.

**Comment by SkyTheLeafeon** [comment]
Hmm...
300th issue. Also, it's good to see things going on here once again.

**Comment by SkyTheLeafeon** [comment]
Alright, I just tested for this in v0.5.2 and it just happened to me.

**Comment by andwn** [comment]
Fixed by:
https://github.com/andwn/cave-story-md/commit/fee0e72008a29cbff055a333d157f9afc5f818c6
