### ISSUE TITLE
No option to save on MiSTer

### ISSUE THREAD

**Issue by jonasongithub** [andwn/cave-story-md#302]
I've been trying to play the latest release and also the nightly from january 20th on my MiSTer and with both I can't save the game. Where the floppy disk icon should be in game it is simply missing.

**Comment by sikthehedgehog** [comment]
Does it work with Phantasy Star IV?

The bug is likely on MiSTer's end, so yeah first check that game to make sure (as it uses the same configuration, i.e. 4MB ROM + SRAM).

**Comment by sikthehedgehog** [comment]
Then yeah, sounds like MiSTer's fault, you'll need to report the bug on that side then :/

**Comment by jonasongithub** [comment]
There was an update to the genesis core on MiSTer yesterday and saving is now supported for this game, so this issue can be closed.
