### ISSUE TITLE
stage "Outer wall" is all glitchy.

### ISSUE THREAD

**Issue by Pukuotukas** [andwn/cave-story-md#304]
On version "Test Build - Jan 28 2019" stage "Outer wall" is all glitchy.
![20190129_175711](https://user-images.githubusercontent.com/47151817/51931858-83bb3a80-2406-11e9-8c2c-a8ab15ed5bb4.jpg)
 It's impossible to play. i tried to switch regions, but no luck. i'm playing on original mega drive first model. With only region switch mod. also sometimes some sprites of enemies, items or projectiles turns to white square, but pause/unpause fix this glitch. On version "0.5.1a" that stage looks normal.

**Comment by Pukuotukas** [comment]
![doukutsu bin gen sta](https://user-images.githubusercontent.com/47151817/52119906-67e0b000-2623-11e9-9c2a-2fe4c09758a0.png)
also background of sound test option is glitched. Background of Balcony and pictures on the left side in final credits. P.s. Thank you for the great port. superb music and from now the best game on Mega Drive! I love you stranger from internet.

**Comment by andwn** [comment]
I wonder if this will still happen if I build it locally. There is a tool I used (mdtiler) to deduplicate tiles specifically in the backgrounds you mentioned, and the build server for nightlies didn't have this tool (it's not my server though). Not sure when I'll have a chance to work on this again but maybe I'll have to replace the precompioed mdtiler in the repo. 

Anyway thanks for pointing this out.

**Comment by SkyTheLeafeon** [comment]
That's strange... Reminds me of when a friend of mine hacked one of the builds and took the crash handler out. The sound test looked exactly like that in that ROM.

**Comment by andwn** [comment]
<img width="639" alt="Screen Shot 2019-03-13 at 15 56 30" src="https://user-images.githubusercontent.com/8164394/54310582-1542ce00-45a9-11e9-9640-c91210897bbc.png">

Well, I dunno what's going on with the nightly server anymore. I'm gonna remove it from the readme until this stuff gets fixed. For now I'm gonna just release what I have as 0.5.2 or something.
