### ISSUE TITLE
Curly's gun is misaligned in the Labyrinth

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#306]
https://cdn.discordapp.com/attachments/350781762349039617/552604991916081162/unknown.png

I'm surprised this slipped past me.
Seen in v0.5.1a.

**Comment by SkyTheLeafeon** [comment]
Haven't done a full run of v0.5.2 yet, been slacking
I'll see if this is patched when I get the chance

**Comment by andwn** [comment]
0.6, if not tonight, tomorrow
