### ISSUE TITLE
Some HUD weirdness

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#308]
https://streamable.com/hmqcj
Glad to see that this is back in the works.

**Comment by SkyTheLeafeon** [comment]
Put simply: I do NOT remember the HUD acting like this in the original game.

**Comment by ChampionDude345** [comment]
Its an entirely different engine on the _megadrive_. Expect to see these bugs.

**Comment by andwn** [comment]
Sometimes the white flash also stays when the -MAX- should be there, if you get hurt then collect energy quickly. I'll get to it eventually

**Comment by andwn** [comment]
The video is gone now but I recall it being the issue described in #344 which I committed a fix for a few days ago
