### ISSUE TITLE
"AIR" missing from air meter

### ISSUE THREAD

**Issue by SkyTheLeafeon** [andwn/cave-story-md#309]
Self-explanatory.
(We could really use a Discord server for this.)

**Comment by andwn** [comment]
Fixed by:
https://github.com/andwn/cave-story-md/commit/7afc3b3c5c525f85e822d84ae3045a6c56bf7e00

I've thought about making a Discord server and I dunno, just seems like another thing to moderate. Wouldn't mind joining some Cave Story modding server if one already exists though.
