### ISSUE TITLE
Game crashes when resetting under 32X

### ISSUE THREAD

**Issue by darkfalzx** [andwn/cave-story-md#310]
When playing the game off Mega Everdrive on a Model 2 Genesis with a 32X addon, pressing the on-cart reset button crashes the game (music hangs, background turns magenta).
This can be reproduced at any time after booting up the game.

Removing the 32X addon eliminates the issue.

**Comment by sikthehedgehog** [comment]
You sure that doesn't also happen with other games? I don't think the 32X expects the cartridge to attempt resetting the console by itself… (also, isn't that button actually meant for use with Master System games?)

**Comment by darkfalzx** [comment]
You are correct. What I thought was an Everdrive feature ended up just a busted reset button on my system. Sorry for wasting your time. I will really need to overhaul my Genesis before I can be sure any issues aren't just due to faulty hardware: (
