### ISSUE TITLE
Life Capsule fanfare loops

### ISSUE THREAD

**Issue by darkfalzx** [andwn/cave-story-md#311]
When player collects any one of the Life Capsules but doesn't press anything to speed up or skip the text popup, the fanfare tune will loop after a few seconds, and will continue doing so until a button is pressed.

**Comment by SkyTheLeafeon** [comment]
Noticed this a long time ago but never mentioned it here.

**Comment by andwn** [comment]
A loop of silence needs to be added to the end of the track, however the current version of this track was contributed without the tracker file, so I'm unable to fix it without remaking the track. Honestly, I might as well just do it, it's pretty short.
