### ISSUE TITLE
Polar Star shots lack fizzle-out animation

### ISSUE THREAD

**Issue by darkfalzx** [andwn/cave-story-md#312]
In the original PC game each fired Polar Star shot generates a small puff animation whenever it either hits a wall or fizzles out after reaching maximum range. These animation are absent in the Megadrive version, though their sprites are included in game's spritesheet.

**Comment by SkyTheLeafeon** [comment]
Also saw but never noted.

**Comment by andwn** [comment]
Got this in now (when hitting walls, enemies, something invincible, or just reaching the end of it's range). The original game also does it where the bullet starts but decided not to here
