### ISSUE TITLE
Jump disabled while standing on fans in Grasstown 

### ISSUE THREAD

**Issue by darkfalzx** [andwn/cave-story-md#315]
After activating the Grasstown fans, pressing the jump button will do nothing if Quote stands anywhere near a fan, but outside of its actual lifting area.

![doukutsu-0 5 2-190509-102117](https://user-images.githubusercontent.com/38352731/57461348-d77ac280-7244-11e9-8e4c-b320d0dd7abb.png)

**Comment by SkyTheLeafeon** [comment]
This may have something to do with how far out the air currents' hitbox extends. Since Quote is never intended to jump while floating on the currents, this may be because the game thinks he is in one when he's really not.

**Comment by andwn** [comment]
This one was because Quote is actually in the range to get pushed up. The fan sets his jump_time to 4 but should have also disabled the flag for being on the ground so that the slope would "let go".
