### ISSUE TITLE
Burned ROM - Background graphics issue

### ISSUE THREAD

**Issue by bootleg714** [andwn/cave-story-md#316]
This is kind of a minor thing. 

I burned this to an 4MB EEPROM (two different times and had the same problem) and installed on an SRAM board. It works which is pretty awesome. But the intro and first cave background graphics seem to be a little glitchy. 

That's the only place I've seen some issues. The ROM works fine in my emulator. Just thought I'd give my experience.

![DSC03986](https://user-images.githubusercontent.com/51009724/58362620-e9b44d80-7e4d-11e9-802f-20e3a972c891.JPG)
![DSC03991](https://user-images.githubusercontent.com/51009724/58362621-e9b44d80-7e4d-11e9-954e-ac7169bf4d14.JPG)
![DSC03992](https://user-images.githubusercontent.com/51009724/58362622-ea4ce400-7e4d-11e9-91a8-a9ecca271adf.JPG)

**Comment by SkyTheLeafeon** [comment]
Burning the ROM to an EPROM doesn't seem like a good idea at this point in development - you're better off putting it on a flashcart instead.

**Comment by Leo40Git** [comment]
Replicated on BlastEm with version 0.5.2, with System => Initial RAM Value set to "random".

Seems like someone forgot to clear all the RAM. :P

**Comment by bootleg714** [comment]
@Leo40Git I'm kinda of a noob. What does that mean? Thanks for any insight!

**Comment by sikthehedgehog** [comment]
That the game isn't clearing everything properly when it starts.

Technical explanation: memory on real hardware has random values when it powers on, but most emulators fill it with zeroes instead, which leads to people not paying attention and stuff like that happening because they never noticed they forgot about it.

**Comment by bootleg714** [comment]
@sikthehedgehog Thanks man. I appreciate the explanation.

**Comment by andwn** [comment]
This probably started happening a couple versions ago when I started using the newer VDP module from another project. Easy to fix though

**Comment by bootleg714** [comment]
@andwn Thanks for the reply man! Amazing work. Pretty stoked I was able to get it to work off EPROM. I've made it to Grasstown so far without any problems.

**Comment by SkyTheLeafeon** [comment]
@bootleg714 Quick question: what version are you using? 0.5.2? 0.5.1a?

**Comment by bootleg714** [comment]
@SkyTheLeafeon I used 0.5.2.  Haven't tried any other versions yet.

**Comment by SkyTheLeafeon** [comment]
@bootleg714 I see.

**Comment by andwn** [comment]
This should be fixed in master currently but my flasher isn't working at the moment. Once it's fixed or I get one that works I'll have to test it (this issue doesn't happen on an everdrive otherwise I would have noticed it a long time ago)

**Comment by bootleg714** [comment]
Cool man. Just thought I'd let you know. I'm probably the only person that's burned a ROM lol. I can make a cart for you if you want.

**Comment by andwn** [comment]
Turns out the flasher gets mad if your ROMs aren't padded to 512KB. I can now safely say this issue doesn't happen on a standalone cart anymore
