### ISSUE TITLE
No savepoints, playing with Regen

### ISSUE THREAD

**Issue by igpollitzer** [andwn/cave-story-md#317]
I like to use the Regen Genesis emulator and, when playing, the save diskettes don't show up. They do show with Kega Fusion.
I know that the game has a cheat mode that doesn't allow you to cheat so, I assume that, somehow, the game thinks that a cheat code has been entered.

**Comment by andwn** [comment]
The save disks are hidden when SRAM doesn't work. Regen may not emulate the kind of SRAM used properly.

This project is also kind of on hiatus, possibly indefinitely. I don't have the time to work on it anymore.

**Comment by andwn** [comment]
For better or worse I'm working on this again, but not sure why I left this issue open. I'm not going to fix Regen to support the SRAM mapper, and that emulator's development hasn't been active for a long time iirc.
