### ISSUE TITLE
Stage name messed up kanji graphics

### ISSUE THREAD

**Issue by lemon-sherbet** [andwn/cave-story-md#319]
When setting the game to Japanese, the text that shows the name of the room seems to be messed up. Doesn't happen in English.

![image](https://user-images.githubusercontent.com/41162747/74102886-74a1b900-4b3f-11ea-9efe-ded7c7607133.png)
![image](https://user-images.githubusercontent.com/41162747/74102912-b9c5eb00-4b3f-11ea-9d5e-af2d0ac0acb5.png)

This was tested on the latest commit, on Kega Fusion (linux) and on Gens (rerecording version, with wine).

---

Please check before continuing:
- [y] I've searched my issue or question to make sure it has not been reported/answered already
- [y] If the issue happens on emulator, it happens on more than one emulator
- [y] I understand there is no physical release and you are not responsible for issues with bootlegs
- [y] This is a functional problem or general question, not an opinion or suggestion

**Comment by andwn** [comment]
welcome to ll ll ll ll ll

**Comment by andwn** [comment]
I hate programming actually
![image](https://user-images.githubusercontent.com/8164394/74106156-13bfb400-4b32-11ea-9f13-f2fcf69d2451.png)

**Comment by lemon-sherbet** [comment]
lol

**Comment by SkyTheLeafeon** [comment]
We've been stuck on 0.5.2 for months. Is 0.6.0 shelved?
