### ISSUE TITLE
Incorrect visual priority during Balrog introduction.

### ISSUE THREAD

**Issue by darkfalzx** [andwn/cave-story-md#320]
This is an issue in version 0.6.0. Checked on real hardware, using Mega Everdrive, Kega Fusion 3.64, and Retroarch running Genesis Plus GX 1.7.4 core. 
When first encountering Balrog inside the shed in Mimiga village, the door sprite he's supposedly smashing through is displayed in front of him. The door's visual priority is only adjusted once Balrog switches to idle animation.
![doukutsu-0 6 0-200729-025118](https://user-images.githubusercontent.com/38352731/88767521-bf43db80-d147-11ea-909a-104d339fa87f.png)

PS: It's super exciting to see you working on this again!
To come so far and to stop meters from the finish line was just heartbreaking.

**Comment by andwn** [comment]
Well that's what I get for changing something halfway through a game save and not starting over. Will probably change it back to hiding the open door sprite everywhere except plantation
