### ISSUE TITLE
Save select screen doesn't respect custom button layouts.

### ISSUE THREAD

**Issue by vaguerant** [andwn/cave-story-md#324]
Please check before continuing:
- [x] I've searched my issue or question to make sure it has not been reported/answered already
- [x] I've checked [COMPATIBILITY.md](doc/COMPATIBILITY.md) to make sure my emulator or system is known to work
- [x] I understand there is no physical release and you are not responsible for issues with bootlegs
- [x] This is a bug or question and not a feature request

I have my buttons customized, which works across everything I've tested so far *except* for the save select screen, which reverts back to the original programmed defaults. Have tried multiple saves and reboots to be sure, and it seems that the save select screen simply doesn't support custom button layouts.

This isn't a major issue, as you don't spend much time interacting with the save select screen, but since my Confirm button is the default layout's Cancel button, I do a lot of hitting Start Game then Cancel, since the button layout changes between the title screen (works perfectly) and the select screen (reverts to default).

**EDIT:** And FYI, the link to COMPATIBILITY.md in the issue template is broken. You're providing a relative link to `doc/COMPATIBILITY.md` which means you end up at `issues/doc/COMPATIBILITY.md`. You probably want something like `[COMPATIBILITY.md](/andwn/cave-story-md/blob/master/doc/COMPATIBILITY.md)`, which makes this link: [COMPATIBILITY.md](/andwn/cave-story-md/blob/master/doc/COMPATIBILITY.md)

**Comment by andwn** [comment]
Whoops, yeah I was using BUTTON_C and BUTTON_B macros instead of the cfg_btn_jump/cfg_btn_shoot like the rest of the game.

Here's a ROM with the fix, but it's based on the bleeding edge version and may have new issues that 0.6.0 doesn't.

[doukutsu.zip](https://github.com/andwn/cave-story-md/files/5114897/doukutsu.zip)
