### ISSUE TITLE
PAL still uses NTSC camera scrolling rather than fixed camera in single screen height areas.

### ISSUE THREAD

**Issue by vaguerant** [andwn/cave-story-md#325]
Please check before continuing:
- [x] I've searched my issue or question to make sure it has not been reported/answered already
- [x] I've checked [COMPATIBILITY.md](/andwn/cave-story-md/blob/master/doc/COMPATIBILITY.md) to make sure my emulator or system is known to work
- [x] I understand there is no physical release and you are not responsible for issues with bootlegs
- [x] This is a bug or question and not a feature request

This might technically be considered a feature request rather than a bug since nothing is technically going *wrong* in the current code, but it is an inaccuracy relative to the original game. Feel free to close if you feel this doesn't warrant fixing.

In the many single screen height areas like Arthur's House and the Egg Corridor, the original game uses a fixed camera height, never scrolling vertically, but scrolling horizontally if necessary. This port scrolls those areas vertically to accommodate the reduced resolution of the NTSC Genesis, but they still scroll on PAL Mega Drive, where the resolution is identical to the original PC game and no scrolling is necessary.

I know the Egg Corridor is technically larger than 240 lines, so checking if an area is `≤ SCREEN_HEIGHT` would still result in scrolling in situations like that. Perhaps `≤ (SCREEN_HEIGHT + 16)` or something?

Apologies if this behavior has changed since the last stable. I'm testing via 0.6.0, as the version from #324 crashes the emulator (Genesis Plus GX via RetroArch on Wii U) before it reaches the title screen on my end.

**Comment by andwn** [comment]
The camera bounds are at 4 (or 2? i forget) pixels instead of 8 pixels, my reasoning is that the bottom of Egg Corridor looks like a bottomless pit on many CRTs otherwise. Also, it means I don't have to write extra code to change it when the screen shakes.

**Comment by vaguerant** [comment]
Overscan is certainly a concern on NTSC, but you'd have to have some pretty serious overscan on a PAL TV to overcome the borders in the Mega Drive's signal. The usable area is 240 lines, but the whole visible part of the signal is 288. Anybody losing more than 48 whole lines (17% of the image) has a pretty terrible TV.

I'd say the vast, vast majority of PAL users are only losing empty border area to overscan.

**Comment by sikthehedgehog** [comment]
Screenshots are not exactly the best example, but yeah I recall somebody making a video of Sonic 1 in PAL and it had some chonk borders at the top and bottom (and many people refusing to believe it, which shows how bad is the misconception). And Sonic 3 in PAL goes out of its way by wasting vblank time just to push CRAM dots out of the visible portion of screen, which if anything shows how bad is the problem with the visible border in PAL.

*That said* even if we assume that the amount of visible border area is unreliable, isn't the map block size 16×16? The Sega docs only say to account for ~8px vertically, so technically that still leaves half of the block visible. That rule was about NTSC, but should still apply for PAL because lines are put closer together after all.

**Comment by andwn** [comment]
Guess I can just change it back to the 8px border and see what happens. I think the only hard coded exception I had for this before was shelter on NTSC to stop the text box from overlapping Kazuma.

**Comment by vaguerant** [comment]
> Screenshots are not exactly the best example

I agree, so I dug out my dusty old CRT.
![IMG_20200830_155109_290](https://user-images.githubusercontent.com/5259025/91652284-04598580-ead9-11ea-9c13-7463fbd05a9d.jpg)
It's a dual 50/60Hz Panasonic TC-14L10A3. I don't want to say it's junk, but it's a pretty bog standard CRT from the ... mid-to-late '90s? Possibly very early 2000s? It's not an especially good TV is really what I'm saying. It's small, has only mono inputs, and a fairly large amount of overscan.

I'm not running the game on a real Mega Drive, but rather on Genesis Plus GX for Nintendo Wii, in 288p. I know there might be some pushback on whether that's a valid testing scenario, so I want to stress that what we're talking about here is composite video signals, and while almost 20 years separates the Mega Drive and Wii, composite video is composite video. The PAL Mega Drive ran in 288p (double-strike equivalent of 576i) with the game in the middle 240 lines, and that's exactly what the Wii is outputting. The console has no control over what the TV does with that signal, so a 288p signal from a Wii will be impacted by exactly the same overscan as a 288p signal from a Mega Drive. Sorry if I'm overexplaining this.

As you can see, the top/bottom borders are still pretty substantial, as they are for basically everybody running PAL Mega Drive (or basically any other pre-2000 platform) games. I'm not losing any of the 240 lines of actual game image, vertically, from the 288-line signal. There is some overscan loss on the sides, as is to be expected. Us PAL weirdos didn't spend 20-odd years complaining about PAL borders and/or importing NTSC consoles just for kicks, they've been a prominent part of PAL console gaming from the start. This, however, is one of the few upsides for us: we really never had to worry about overscan on the vertical axis, because none of our games were *using* that space anyway.

I will edit shortly to demo the NTSC overscan on this same TV.

**Comment by andwn** [comment]
Wish I knew where to get one of those hybrid TVs here. Actually did get a PAL Mega Drive after [this](https://www.youtube.com/watch?v=D8ajL4ql2A0) happened but the only way I can get AV is with a capture card.

**Comment by andwn** [comment]
Here's a build with the X and Y borders put back to 8 (except when the earthquake effect is active). If i get reports in the future of people not being able to see the edge of the screen I'll just add a config option or something.

[doukutsu.zip](https://github.com/andwn/cave-story-md/files/5147156/doukutsu.zip)
