### ISSUE TITLE
"No permission to teleport." text in Arthur's house is skipped.

### ISSUE THREAD

**Issue by vaguerant** [andwn/cave-story-md#326]
Please check before continuing:
- [x] I've searched my issue or question to make sure it has not been reported/answered already
- [x] I've checked [COMPATIBILITY.md](/andwn/cave-story-md/blob/master/doc/COMPATIBILITY.md) to make sure my emulator or system is known to work
- [x] I understand there is no physical release and you are not responsible for issues with bootlegs
- [x] This is a bug or question and not a feature request

This line: https://github.com/andwn/cave-story-md/blob/master/res/tsc/en/StageSelect.txt#L2

You can trigger this by examining the teleporter before you look at the computer at the very beginning of the game, so that no locations are open for teleporting. It doesn't wait for the user's input, so it only flashes up for like a single frame before the text box vanishes. I don't know how the text control codes work, does it need a `<NOD` on the end of it or something?

**Comment by andwn** [comment]
Looking at tsc.c this file actually isn't loaded at all. I should probably change it so it actually does read it (so that the text is translated properly too).

**Comment by andwn** [comment]
Wait I'm blind, it does load it, just doesn't do the right thing when there are no options available.

**Comment by andwn** [comment]
Not sure why Pixel didn't include a <NOD in the script, because the solution is basically to make the code emulate one. I decided to do that instead of change every translation of StageSelect, because when more are added I will definitely forget.
