### ISSUE TITLE
Broken cutscene in Chako's house

### ISSUE THREAD

**Issue by darkfalzx** [andwn/cave-story-md#329]
During the cutscene that plays after Quote checks the fireplace at Chako's house In Grasstown, she walks through a wall of her house and completely off screen.
Verified three separate times on 0.7.0. Screenshot taken right before she disappears into the wall.
![doukutsu-0 7 0 en bin-200915-090537](https://user-images.githubusercontent.com/38352731/93214466-39014a00-f733-11ea-8771-6d9dabf52d8b.png)

**Comment by andwn** [comment]
Ah shoot, so when I changed Chaco's sprite in the credits I overwrote state 0 which used to also set the x speed to 0.
https://github.com/andwn/cave-story-md/commit/5479a7edd3dd62a0eb78b30bc35d5606a529c08e#diff-1a1e041410f7911bc077e91c3132d493R33

Oh well.
