### ISSUE TITLE
Balrog AI (Fight 1)

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#33]
When you stand on the block on the upper-right of the shack Balrog will stand there underneath you and do nothing but jump occasionally.

http://i214.photobucket.com/albums/cc164/andwhyisit/balrogmd_zpsoug8qyjs.gif
http://i214.photobucket.com/albums/cc164/andwhyisit/balrogpc_zpswh1zn9ef.gif

Also in vanilla CS Balrog will always travel a set distance in the direction of the player, never longer, and only shorter when he runs into something like a wall. The MD version on the other hand has him travelling the full distance to the player regardless of length. The player's position should only determine the direction of travel, not the distance of travel. Although I think the distance is different during the jumping phase.

http://i214.photobucket.com/albums/cc164/andwhyisit/balrogdistancemd_zpswhv6sqm4.gif
http://i214.photobucket.com/albums/cc164/andwhyisit/balrogdistancepc_zpsdpvuamku.gif

Oh, and it should be 2 points of damage, not 1.

Tested in v0.2.0-alpha

**Comment by andwn** [comment]
I rewrote this fight's AI a couple weeks ago. Balrog should run like how he does in the original but not sure about the damage. Will double check this stuff later when I make another pass thorugh the game.

**Comment by andwhyisit** [comment]
I finally managed to compile a recent build (gendev is evil though, it complains about missing dependencies towards the very end of the entire process, and then it complains about the files the previous build process has generated, not to mention the lack of "make clean", your build process on the other hand was a breeze).

Everything is looking good, including damage, except Balrog can sometimes phase through the top-right block.

**Comment by andwn** [comment]
Sorry I haven't been posting builds lately (major refactor), but I'm glad the build process actually works for other people.

There is a "make sgdk" and "make sgdkclean" in the makefile somewhere, that way if the build of the cross compiler worked you don't have to wait another hour for it to rebuild, it'll just try the md lib again. I should add instructions for this and the dependencies, probably beneficial. In my opinion Gendev is still rather dirty ("sudo make"?) but I'm afraid of taking too many liberties changing around my fork.

**Comment by andwn** [comment]
The dependencies for gendev should be:
- Base compiler package for whatever distro: build-essential / base-devel
- Texinfo (I think newer GCC pulls this with it not sure though)
- Java (for ls4w... I wanto to rewrite that tool in C kind of)

Then CS would need Python 3, I have a small script that generates a header. Did you need to install anything else?

**Comment by andwhyisit** [comment]
I had python 2.6.6 installed and it seemed to build the rom fine.

**Comment by andwhyisit** [comment]
Sooo... here's that block phasing issue I was talking about:
http://i214.photobucket.com/albums/cc164/andwhyisit/balphase_zpstvvjmhxh.gif

**Comment by andwn** [comment]
Oh! I know why this is happening, the big jellyfish does it too. The typical collision routines check near the corners, so I gotta customize the big objects a bit.

**Comment by andwhyisit** [comment]
Confirmed as working. I'll mark this one as fixed.
