### ISSUE TITLE
Music still runs slower on PAL Mode [0.7.0]

### ISSUE THREAD

**Issue by brunorurz** [andwn/cave-story-md#330]
As of version 0.7.0 the music on PAL Mode is still runs slower as it would without the pal mode optimization [Gameplay is still sped up]. It happens both on emulators and real hardware. My theory is that it may have something to do with the "CS+ Speed" option added in this version.

**Comment by andwn** [comment]
I was confused for a hot minute but the issue was that I initialized the sound driver before the VDP. The VDP init function sets the pal_mode flag which the sound driver init function checks to set the tempo.

Not sure what language you prefer but here is a fixed one in English.
[doukutsu-en.zip](https://github.com/andwn/cave-story-md/files/5263242/doukutsu-en.zip)

**Comment by brunorurz** [comment]
> I was confused for a hot minute but the issue was that I initialized the sound driver before the VDP. The VDP init function sets the pal_mode flag which the sound driver init function checks to set the tempo.
> 
> Not sure what language you prefer but here is a fixed one in English.
> [doukutsu-en.zip](https://github.com/andwn/cave-story-md/files/5263242/doukutsu-en.zip)

Thanks man. I used the english version. Im not sure if this also occurs on other languages. If the source code between all languages is the same [not counting the translated text of course], this bug may also happen on all other versions.

**Comment by brunorurz** [comment]
Hey. Sorry to bother you again. I just realised that the fixed version you sent me has no neat Sega intro at the begining. It doesn't make the game unplayable for me but I just thought to let you know.

**Comment by vaguerant** [comment]
@brunorurz That's normal, only proper release builds get the Sega screen. There's a flag in the Makefile which adjusts whether or not to show the Sega screen; I imagine it gets annoying when you're making test builds to sit through the Sega screen each time.
