### ISSUE TITLE
Broken sprites on ATGames Sega Genesis handheld

### ISSUE THREAD

**Issue by Wumbo2255** [andwn/cave-story-md#331]
I was trying to play this on my 2016 "SEGA Genesis Ultimate Portable Game Player", and I've noticed that the sprites for the game look broken. 
![broken sprites](https://user-images.githubusercontent.com/61855201/102426585-98dee980-3fdd-11eb-9d05-8fe64046aa4c.png)
This issue has only happened to me when I attempted to play the port on this handheld.

**Comment by andwn** [comment]
Try out the test ROM from #330 that should have a fixes for a DMA issue that affects some consoles. If that doesn't do it then I'm sorry to say I'm not really interested in fixing issues with ATGames consoles.
