### ISSUE TITLE
Portuguese br text sometimes gets broken

### ISSUE THREAD

**Issue by Red-gehog** [andwn/cave-story-md#335]
Hi! I think the port is wonderful! But I am having these problems in the text boxes. Sometimes the text appears to have holes, this happens most of the time after screen transitions. 

Version: 0.7.0

![doukutsu-br-210314-234729](https://user-images.githubusercontent.com/73415642/111098697-cbd44300-8522-11eb-8f87-c224dc430c9f.png)

![doukutsu-br-210314-235247](https://user-images.githubusercontent.com/73415642/111098710-d2fb5100-8522-11eb-99e8-cc3e68155128.png)

**Comment by altiereslima** [comment]
accent marks in stage names too

**Comment by altiereslima** [comment]
> Hi! I think the port is wonderful! But I am having these problems in the text boxes. Sometimes the text appears to have holes, this happens most of the time after screen transitions.
> 
> Version: 0.7.0
> 
> ![doukutsu-br-210314-234729](https://user-images.githubusercontent.com/73415642/111098697-cbd44300-8522-11eb-8f87-c224dc430c9f.png)
> 
> ![doukutsu-br-210314-235247](https://user-images.githubusercontent.com/73415642/111098710-d2fb5100-8522-11eb-99e8-cc3e68155128.png)

happens after using the map

**Comment by andwn** [comment]
Hello I'm a dumbass

<img width="366" alt="Screen Shot 2022-01-16 at 2 42 49" src="https://user-images.githubusercontent.com/8164394/149651642-e858184a-2c18-47e5-8010-69d53e2146c7.png">

**Comment by andwn** [comment]
<img width="623" alt="Screen Shot 2022-01-16 at 2 46 57" src="https://user-images.githubusercontent.com/8164394/149651789-3bf346bc-26f2-419f-9292-84bf04bc03cc.png">

Yep... but the map names are still wrong

**Comment by andwn** [comment]
The code that draws the map name is off by one for the non-ascii chars and actually effects all languages oops

**Comment by andwn** [comment]
0.8.0 (respond/reopen if i missed something though)

**Comment by Red-gehog** [comment]
Thanx!! You're a hero!!
