### ISSUE TITLE
The Sisters boss fire projectiles (0.7)

### ISSUE THREAD

**Issue by mastercheff** [andwn/cave-story-md#336]
They're like invincible, can't shoot them down no reaction.  When boss HP goes down to about half, dragons breath non-stop with no chance to avoid them. I consider this a game breaking bug 

Mega Drive PAL VA6 ntsc mod (jumpers no oscillator)

https://imgur.com/yrYpASk

I can send the save file if that would be helpful , cheers

**Comment by mastercheff** [comment]
Transferred my save file to PC , using Kega Fusion emulator i was able to reproduce the behavior 
definitely a bug

**Comment by andwn** [comment]
Are you comparing the behavior to the original game?

**Comment by mastercheff** [comment]
In the original game You can shoot down the flames
in CSMD 0.5.2  dragons don't breath a single flame afaik
https://youtu.be/exVVHUfKWJw?t=6571
0.7 flames are invincible. I tried like 10 times yesterday with every weapon , 100% rekt - im not that good at bullet hell
