### ISSUE TITLE
Egg Coridor? Possible Softlock

### ISSUE THREAD

**Issue by sonich2401** [andwn/cave-story-md#337]
I've been playing on the latest English release of this game for a while now and I am currently at the "Egg Corridor?" where there is a door that is supposed to lead into Egg 00. However this door is locked for me and says "It won't open!" which is odd because in all of the walkthroughs of this area people walk strait in with no problems.

If it helps any I attached my save file.
[Cave Story.zip](https://github.com/andwn/cave-story-md/files/6283682/Cave.Story.zip)

**Comment by andwn** [comment]
It checks for a flag that gets set when defeating Igor. There isn't any way for that flag to get unset by the time you revisit Egg Corridor so I don't get why it would be for you (corruption?). I removed the <FLJ since it's superfluous anyway.
