### ISSUE TITLE
Chinese language support

### ISSUE THREAD

**Issue by James-Makoto** [andwn/cave-story-md#339]
Is it possible to support chinese for this CSE port? The original Cave Story have the zh_CN/zh_TW translation. thank you :)

**Comment by andwn** [comment]
I'm looking for a font that could possibly be used for this. The glyphs have to fit in 12x16 rectangles. Found this:

https://timothyqiu.itch.io/vonwaon-bitmap

On the page it says "second level Chinese characters are not included". I don't know what those are. Would anyone watching these issues happen to know if either Cave Story Chinese translation use "second level" characters?

**Comment by andwn** [comment]
Added Simplified Chinese in 0.8.0 and will probably add Traditional Chinese at some point in the future
