### ISSUE TITLE
Giant Pignon AI

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#34]
The Giant Pignon (the big mushroom in the cemetery) seems to rebound backwards (in the opposite direction to where it is facing) when it takes damage from the player, but in vanilla CS it always rebounds in the direction of the player.

**Comment by andwhyisit** [comment]
Just regarding the relevant commit, how literal is "FACE_PLAYER(e);"? Because Giant Pignon shouldn't change its direction of facing when it rebounds from damage.

Here's an example shooting both front and back:
http://i214.photobucket.com/albums/cc164/andwhyisit/pignon_zpsqnnwwd8a.gif

**Comment by andwn** [comment]
That's weird usually you would expect it to bounce away. Only the big one does this?

Looks like it travels a bit too far from the bounce in my version too.

**Comment by andwhyisit** [comment]
Turns out that the smaller ones don't rebound backwards or forwards, just upwards.

**Comment by andwn** [comment]
Welp. At least it's easy to fix, but most other enemies probably don't react quite right either (no shake)

I should really just play through the real game again it's been months.
