### ISSUE TITLE
save flopys dont exsist

### ISSUE THREAD

**Issue by EmealdTuxedo** [andwn/cave-story-md#340]
Please read the [FAQ](/andwn/cave-story-md/blob/master/doc/FAQ.md) before submitting your issue, and do a quick search to make sure your issue has not already been reported.
i was playing cave story with this version and the save things didnt apear at all

**Comment by andwn** [comment]
Your SRAM is malfunctioning or your emulator sucks.
https://github.com/andwn/cave-story-md/blob/master/doc/COMPATIBILITY.md

**Comment by bootleg714** [comment]
I've made a physical cart using a SecondDimension PCB and it filly works and saves with real hardware. 

But I can confirm it does not work with AtGames. Graphics are very corrupted. So you can update your compatibility list if you want.

**Comment by andwn** [comment]
Ok, adding that to the compatibility list
