### ISSUE TITLE
On Genesis Plus GX, x, y, and z buttons are ignored.

### ISSUE THREAD

**Issue by crocket** [andwn/cave-story-md#342]
Version: 0.7.0

On BlastEm libretro core, x, y, and z buttons are recognized.
On Genesis Plus GX libretro core, x, y, and z buttons are ignored.

I compiled the latest commit of https://github.com/libretro/Genesis-Plus-GX

**Comment by andwn** [comment]
Meh.

<img width="613" alt="Screen Shot 2022-01-16 at 0 58 50" src="https://user-images.githubusercontent.com/8164394/149649137-9402e2fb-b713-4956-bbae-418d702f516e.png">
