### ISSUE TITLE
When I move, I see white border around doors.

### ISSUE THREAD

**Issue by crocket** [andwn/cave-story-md#343]
Is this a bug or a limitation of sega genesis? I use either BlastEm or Genesis GX Plus.

![Cave Story (en) 0 7 0-211027-085558](https://user-images.githubusercontent.com/748856/138977668-63a01d09-ec55-4ac1-aab5-2be9c27d2374.png)

This white border bothers me.

**Comment by andwn** [comment]
The white border is part of the map behind the door. It shows up because the sprites sometimes fall behind when rendering a frame. There is no real fix other than continuing to optimize the game in general over time.
