### ISSUE TITLE
Don't show level point change animation when I switch between weapons of the same level.

### ISSUE THREAD

**Issue by crocket** [andwn/cave-story-md#344]
If I switch between weapons of the same level, the game shows level point change animation as if I didn't switch weapons.

The game thinks the current weapon's level point changed and shows level point change animation while, in fact, I switched to a different weapon. If I switch back to the previous weapon while the level bar is white, the level bar stays white until there need to be changes to level bar again.

![139191521-fe674130-6290-407c-9ab8-fed90636cedd](https://user-images.githubusercontent.com/748856/139216271-ae25f56e-9a61-4763-957a-e753b0acecb3.png)

This issue is related to https://github.com/andwn/cave-story-md/issues/321

**Comment by andwn** [comment]
0.8.0
