### ISSUE TITLE
Arms barrier can't be obtained without booster.

### ISSUE THREAD

**Issue by crocket** [andwn/cave-story-md#348]
In the original freware and nxengine derivatives, it's possible to get arms barrier without booster by jumping on top of an enemy.

![mpv-shot0001](https://user-images.githubusercontent.com/748856/142353739-40c2fe18-6461-4468-874f-44c9e322a9dd.png)
![mpv-shot0002](https://user-images.githubusercontent.com/748856/142353744-6bcb0a01-9f45-4188-bc73-b3ed61b4efb5.png)

In cave-story-md, it's not possible because the enemy doesn't jump high enough.

**Comment by andwn** [comment]
I swear it was possible before. Maybe I broke something...
