### ISSUE TITLE
SMD extension

### ISSUE THREAD

**Issue by xmha97** [andwn/cave-story-md#350]
https://fileinfo.com/extension/smd#sega_mega_drive_rom_info
Please publish this game with SMD extension (instead of BIN)
![image](https://user-images.githubusercontent.com/23485114/155120991-b46e1519-9a3e-4e6c-9564-87605d6870e7.png)

**Comment by clebercasali** [comment]
SMD is a different file format. There are free tools to convert.

**Comment by andwn** [comment]
Nah
