### ISSUE TITLE
Can't seem to enter Santa's House

### ISSUE THREAD

**Issue by ualaa1** [andwn/cave-story-md#353]
Played on version 0.8.0 on Kega Fusion
I've already given the key to Santa already, but I still can't enter the house.
Savestate:
[Cavestory (2).zip](https://github.com/andwn/cave-story-md/files/8722807/Cavestory.2.zip)

Edit: For some reason, I had to talk to Chaco first to enter Santa's house

**Comment by segaplayer-rgb** [comment]
> Played on version 0.8.0 on Kega Fusion I've already given the key to Santa already, but I still can't enter the house. Savestate: [Cavestory (2).zip](https://github.com/andwn/cave-story-md/files/8722807/Cavestory.2.zip)
> 
> Edit: For some reason, I had to talk to Chaco first to enter Santa's house

I have the same problem. But I have a temporary solution - if you teleport to another location, and return back to Santa's door, the door will open. I hope this problem will be fixed

**Comment by andwn** [comment]
This is fixed in master now, but could be a while before another release. Have to fix other stuff.

**Comment by andwn** [comment]
Forgot to tag: eaf9bc3963679a25bcc5e2c1700db4335eb39c8c

Posted this in another issue, should have this fix as well: https://github.com/andwn/cave-story-md/files/9793500/doukutsu-all.zip
