### ISSUE TITLE
Egg Observation Room Terminals

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#36]
The terminals for eggs 1 and 6 (on the bottom floor) should be red on activation. At the moment they are blue like all of the other terminals.

Example:
http://i214.photobucket.com/albums/cc164/andwhyisit/eggobservationterminals_zps9t7cg8ua.gif

**Comment by andwn** [comment]
I was curious when looking at this where the red frames were
https://github.com/libretro/nxengine-libretro/blob/master/nxengine/ai/sym/sym.cpp#L720

Maybe it's because NXEngine always treats the option 2 flag as facing right, and the right facing frames are red? I'll try checking for the flag before animating and see if that works.

**Comment by andwn** [comment]
yep it was option 2

![image](https://my.mixtape.moe/ifplxs.png)

**Comment by andwhyisit** [comment]
Two other issues while I am in the same room:

1. The flower sprite from Arthur's house seems to be displaying over the bed, whereas it doesn't in the original.
2. The lift seems to go Top>Bottom>Middle>Top, whereas the original went Top>Middle>Bottom>Middle>Top.

Comparison image:
http://i214.photobucket.com/albums/cc164/andwhyisit/eggcomp_zpsc9d5rqyv.gif

**Comment by andwn** [comment]
There are 4 NPCs in the table described as "red flowers" which i gave the same sprite (I was too lazy to figure out the specific one that was in Aurthur's House). Looks like the one in this particular room wants the red part only. I'll have to check the ID in cave editor to find the right one.

Maybe I can add a debugging feature that will pop up the number of the type/event/id of the object, like press/hold X to toggle. Could make it less work to figure out this stuff.
