### ISSUE TITLE
Kazuma Keeps Saying "Hey!"

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#37]
After you inspect the shelter door in Grasstown Kazuma starts saying "Hey!" from the crack. This is normal. However Kazuma keeps saying "Hey!" over and over again whereas the original only does this once.

Not only that, but every time I interact with the door the "Hey!" sprite and entity moves up 8 or so pixels. Effectively I can no longer interact with the "Hey!" entity after interacting with the door more than once.

The bug in action:
http://i214.photobucket.com/albums/cc164/andwhyisit/hey_zpsos3bgxkv.gif

**Comment by andwn** [comment]
I was trying to add they hey bubble a long time ago, and was never able to get it to show up.

What did you do?

**Comment by andwhyisit** [comment]
I interacted with the door using a build I compiled 5 hours ago. Maybe your egg terminal fix fixed this as well?

**Comment by andwn** [comment]
So what I was doing wrong, was that I didn't talk to the door before talking to the crack in the wall. Should be good now, but possibly in the wrong spot.

**Comment by andwhyisit** [comment]
The hey bubble is showing once now, however I still have that issue where the hey bubble moves upwards 8 pixels every subsequent time I interact with the door. If I interact with the door at least twice then I can no longer interact with the "Kazuma wall crack" entity.

http://i214.photobucket.com/albums/cc164/andwhyisit/heyfromuphere_zpshv1mcing.gif

**Comment by andwn** [comment]
I think the script is replacing (<CNP) the entity to communicate with kazuma with the hey bubble, which would explain why it appears too low initially, and why my adjustment pushes it up more than just the one time. Changed it to use the display box rather than the actual position so it should stay in place now.

**Comment by andwhyisit** [comment]
Seems to be working fine.
