### ISSUE TITLE
Cant get through door as soon as you give santa the key

### ISSUE THREAD

**Issue by JoshuaPettus** [andwn/cave-story-md#376]
**What happened**
Please try to describe the issue in the **title**.
What were you doing when the issue happened? How can others reproduce the problem?

I gave santa the key, santa went in the door to the house, but the game wouldnt let me in till i left the grasslands in the teleporter and then came back.

**Expected behavior**
What did you expect to happen instead?
That I could enter the house as soon as a I gave santa the key.

**Environment**
What console (and flash cart) or emulator are you using?

Mega Everdrive Pro (latest model) Genesis model 2
Any addons or weird settings?
No
Which language ROM were you playing?
English

**Comment by andwn** [comment]
This bug is a duplicate and has been fixed in the current development snapshot. Look in the 0.8.1 milestone list.

**Comment by JoshuaPettus** [comment]
Apologies, totally missed that.   I'll close this one
