### ISSUE TITLE
Game crashes Out of Memory after First Jenka Dialogue

### ISSUE THREAD

**Issue by mastercheff** [andwn/cave-story-md#378]
**What happened**
2023-01-06 build , can't progress further 

**Expected behavior**
smooth sailing

**Screenshots**
as follows
![IMG_0019](https://user-images.githubusercontent.com/60203533/212569789-66586c64-fbe6-4c89-836f-dbfa13d9bb0c.JPG)
![IMG_0020](https://user-images.githubusercontent.com/60203533/212569798-eb4e0160-1fe1-4150-83b3-4fe5940c4dac.JPG)
![IMG_0021](https://user-images.githubusercontent.com/60203533/212569812-e1bf8f65-8d9f-46d7-b028-d182b25969bd.JPG)

**Version**
2023-01-06 en

**Environment**
What are you using to play the game?
VA 6.5 model 1 Pal > 60hz jumper on

attached .srm save file 
[doukutsu-en-202301062000.zip](https://github.com/andwn/cave-story-md/files/10421386/doukutsu-en-202301062000.zip)

**Comment by mastercheff** [comment]
As of 14.4.23 test build, issue is fixed :)

**Comment by JoshuaPettus** [comment]
where is this test build located?  I looked at https://tenshi.skychase.zone/cs/ and it doesn't seem to be listed

**Comment by JoshuaPettus** [comment]
Thank you! Much appreciated!

**Comment by mastercheff** [comment]
It saves normally with compatible devices. glitchy balrog bubble is one known bug, another is a softlock in last cave (hidden)
