### ISSUE TITLE
Curly's Under Garments Question

### ISSUE THREAD

**Issue by EmeraldTuxedo56** [andwn/cave-story-md#381]
So I Picked Up Curly's Underwear And When I press A While Hovered Over It, It Switches Into A Different Item. Is This Intended Or Is This An Easter Egg? And What Is The Purpose Of This As Well?

**Comment by andwn** [comment]
The A button thing is a debug feature I forgot to turn off I guess. That applies to every item though and only happens in the auto/nightly builds. You noticed it on the panties specifically by coincidence.

**Comment by EmeraldTuxedo56** [comment]
Thanks
