### ISSUE TITLE
Game does not save correctly.

### ISSUE THREAD

**Issue by RubidiumDev** [andwn/cave-story-md#395]
When I was playing all to Sand Zone, I turned off the console
and all of my save data was missing, I saved frequently though.

When I saved in starting point, my data was there
and when I saved again with the polar star,
it had the save data of starting point.

Version 0.8.0

Sega Genesis Model 2, Mega Everdrive v5

**Comment by andwn** [comment]
Sounds like it's time to replace the battery on your Everdrive. It doesn't write saves to the SD until you load the game from the menu again, so if you power off for longer than a few minutes with a dead battery it'll be gone or load something older. I had to replace mine recently after losing a Monster World 4 save.

From the user manual:

For games that utilize battery-backed saves, a file will be created on the microsd card. (please note that this file isn’t created until the next time a game is loaded, it is temporarily held in the battery backup memory, unless you use the toolbox / Game Ram to SD feature)

**Comment by mastercheff** [comment]
I do highly recommend latest dev builds of the game , by the way .  Lots of improvements compared to 0.8 , plus Your  own playthrough testing may come in handy for the future of the project .

**Comment by RubidiumDev** [comment]
OK, and i just got the everdrive
