### ISSUE TITLE
Cheat codes?

### ISSUE THREAD

**Issue by Sonikkun98** [andwn/cave-story-md#398]
Can you make cheat codes? Whether they are game genie or action replay? XD

**Comment by mastercheff** [comment]
Cheats
Stage Select: up, down, left, right, A + Start. Like Sonic.
Infinite health/ammo: up, up, down, down, left, right, left, right, A + Start.

It's in the readme

**Comment by Sonikkun98** [comment]
It wasn't what I was referring to, but hey, something is something.
