### ISSUE TITLE
NPC number in NPC test is not redrawn properly

### ISSUE THREAD

**Issue by sikthehedgehog** [andwn/cave-story-md#4]
Yes I know it's a debug thing but it still irks me =P

The NPC No. field is not redrawn properly, i.e. if it draws a number with more digits, then a number with less digits, there will be trailing digits which result in the "wrong" number being displayed.

Suggested fix: clear those three tiles before drawing the number. (or even two, since the first digit will always be drawn and will never need clearing)

**Comment by andwn** [comment]
Gonna close some of these that I know are fixed cause I don't like having them still sitting around and spanning multiple pages
