### ISSUE TITLE
Rendering Bug on Exiting Sound Test

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#40]
Open the sound test from the main menu and then exit back out again. The Sega logo will reappear and will have weird white boxes underneath it.

http://i214.photobucket.com/albums/cc164/andwhyisit/segggggaaaaaaaaaaaaaaaaaaaaa_zpsvtetqdlh.gif

**Comment by andwn** [comment]
That's weird especially since I clear the screen. Just going to put a hard reset at the end of sound test and dig up this can of worms later.
