### ISSUE TITLE
Cronjob: Nightly Builds

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#42]
Well I finally have this cronjob working. It updates the nightly build download at 5:45am your time.

Getting crontab to populate the correct environment variables and run under the correct user and permissions was waaaaayyyy more painful then it needed to be, but it is holding up well.

Here's the url:
http://www.cavestory.org/md/nightly.zip

**Comment by andwn** [comment]
I didn't know you were an admin of that site! Most of the modding docs I used to write the engine were there.

Will toss this into the readme. Was there something in Gendev/SGDK/CS that particularly made it difficult or is it more so how cron deals with paths? Maybe there is something we can do to make it easier for others to set up automated builds for genesis roms.

**Comment by AmbientMalice** [comment]
Coolbeans.

**Comment by andwhyisit** [comment]
I think there is no real point in leaving this open, so I'll close this one.
