### ISSUE TITLE
Physical edition

### ISSUE THREAD

**Issue by rakulnas** [andwn/cave-story-md#43]
Hello;
  A friend told me about your project, looks really interesting. I would like to ask is you have editor for Megadrive/Genesis cart release. I may do for you. If you are interested, please, contact me in info@nosolovintage.com 

Greeting and nice work :)

.: Felipe :.

**Comment by sikthehedgehog** [comment]
How do you do that without Pixel's authorization?

**Comment by rakulnas** [comment]
Hello;
    Im asking here because i don´t know who is the right person to contact to. :) Of course, all with authorization. May you help me who to contact to?

thanks a lot

**Comment by rakulnas** [comment]
just asking, I won´t do nothing

**Comment by AmbientMalice** [comment]
IMO, that's pretty risky territory. Since the game got remastered, and remade for the 3DS, there haven't been any "authorized" free ports. The last one was the PSP port, and that was years ago. Making a cartridge version is asking for trouble.

Anyhow, this project is far too early to be even contemplating such things.

**Comment by rakulnas** [comment]
thanks anyways, just giving an option. I design Megadrive/Genesis games and i love to have them in the shelf. I love physical editions. Pretty good job and go on!!!

**Comment by andwn** [comment]
I am not the original creator of Cave Story. I don't think he even knows my port exists.

https://github.com/andwn/cave-story-md/blob/master/README.md#will-there-be-a-physical-release-of-this

**Comment by rakulnas** [comment]
Sorry, Didn´t notice that entry. Don´t disturb you anymore! great job guys!! Would love to play It

**Comment by andwn** [comment]
No worries. I do understand the appeal but don't want to risk burning 8 months of my free time over a DMCA notice.
