### ISSUE TITLE
Undeclared constant in Dragon Zombie entry

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#44]
Trying to compile causes this error:
```
src/db/npc.c:221:37: error: ‘onspawn_deaddragon’ undeclared here (not in a function)
  { &SPR_BabyDragon,NOSHEET,PAL3,2, &onspawn_deaddragon, &ai_null, &ai_null }, // Dragon Zombie (Dead)
                                     ^
```
The function is defined in the source file, but *not* in the header file.
aigen.py seems to not detect this function, so it's not in the header file.

**Comment by andwn** [comment]
The header won't be regenerated if it already exists. Did you run "make clean"?

**Comment by andwn** [comment]
I'm going to look into having the Makefile run the script every time. Probably everyone else who tries pulling will have this issue.

**Comment by andwn** [comment]
391d32174fd10b6c816690e922233a69ba2ee2c6 - forgot to tag issue

**Comment by Leo40Git** [comment]
I forgot to run "make clean", meaning running aigen.py didn't change anything. Whoops!
