### ISSUE TITLE
HUD overlaps text box when on the top

### ISSUE THREAD

**Issue by sikthehedgehog** [andwn/cave-story-md#46]
If the text box is at the top of the screen (e.g. when checking the terminals at the bottom of the terminal room in Egg Corridor), the HUD will appear on top of it, obscuring part of the text.

Obvious fix would be to just hide the HUD while such a text box is visible (it'd have been completely covered by the box anyway)

**Comment by andwn** [comment]
This is what happens when I add engine features then don't test anything before sand zone. Fix should be easy though.

**Comment by andwhyisit** [comment]
Confirmed as working.

**Comment by sikthehedgehog** [comment]
Yeah it works so I guess I'll close it...
