### ISSUE TITLE
Gap in inventory

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#47]
In the original CS the item list would always collapse when an item was added or removed so that there were no empty slots.

However in the MD version something weird is going on:
http://i214.photobucket.com/albums/cc164/andwhyisit/gapitem_zpsnrdifjl0.gif

You can also see this in your finalcave_good save.

**Comment by andwn** [comment]
It's just not sorted. Do you know if the original maintains a certain order, or just removes the gaps?

**Comment by andwn** [comment]
This shouldn't happen anymore in new saves, but loading an existing one won't remove a gap that is already there.

Consuming an item in the menu might glitch if there are items after it. Will test that out later.

**Comment by andwhyisit** [comment]
To answer your question the game will a remove the gap and maintain the original order, and order is always the order the items were received.

Example time:
Say you have an inventory of items A, B, and C in that order. Adding item D to that list makes it A, B, C, D, because new items are always added to the end. Now if we remove item B the item slot assignments will shift to close the gap, making it A, C, D. Now if we reobtain item B later on the list would then become A, C, D, B.

**Comment by andwhyisit** [comment]
Consuming an item in the menu seems to update item slot associations for item names and text, it just doesn't update the item images. Of course once the inventory screen is closed and reopened everything is fine again.

Obligatory animated gif:
http://i214.photobucket.com/albums/cc164/andwhyisit/liferope_zpsgjwcpc7c.gif

**Comment by andwn** [comment]
Should be good now. I'll have to replace the save files that already have gaps later on.

**Comment by andwhyisit** [comment]
Confirmed as working.
