### ISSUE TITLE
Machine Gun Issues

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#48]
You shouldn't be able to fly with the Lv1 or Lv2 machine gun, only the Lv3 machine gun.

Also it should be noted that the machine gun in the MD version currently has no lift, it just holds your current y position.

I heard that the Lv3 machine gun in the original CS taps into the fan logic for lift, so it has a quirk where holding the jump button while shooting down grants you more lift. I figured it was worth noting if it helps any, since you do have working fan logic.

**Comment by andwn** [comment]
This one will probably take me a while to get right. I have the position locked now because before you would go really really high if you jumped and shot down at the same time.

**Comment by andwhyisit** [comment]
Uhh... if you are talking about going higher if you hold the jump button while firing downwards, I just explained that the original game did that. Seriously man, open the original game and try flying with the machine gun while holding the jump button.

**Comment by andwn** [comment]
I saw. I'm taking clip through the ceiling fast, so I have to fix that.

**Comment by andwhyisit** [comment]
Some more bugs:
1. If I am falling downwards and use the machine gun in the original it stops my descent in around a single tile, whereas it takes around 10 tiles to do the same in the MD version.
2. In the original it should be noted that you can use the booster 2.0 sideways while employing the machine gun for upwards lift (by moving sideways while shooting down, then hitting jump to fire the booster), however this isn't currently possible in the MD version.

**Comment by andwn** [comment]
For 1 probably need to apply more force when the player is falling vs going up.

2 might effect all weapons actually. Just have to move it around so up/down is checked before left/right.

Also aiming up is supposed to push you down but that doesn't happen yet. There is a skippable spot in waterway that looks good to test once I add it though.

**Comment by andwn** [comment]
I think I misunderstood 2. Something about the booster is blocking out firing weapons.

**Comment by andwhyisit** [comment]
Holding the jump button while flying with the machine gun (without the booster equipped mind you) in the MD version doesn't seem to affect the rate of acceleration, whereas it does in the original.

Here's an example from the original without the jump button held down:
http://i214.photobucket.com/albums/cc164/andwhyisit/withoutjumpbutton_zpscp1igrnm.gif

...compared with one where it is:
http://i214.photobucket.com/albums/cc164/andwhyisit/withholdingbutton_zpsql3dnx1g.gif

**Comment by andwhyisit** [comment]
Looking good. I'll mark this down as done.
