### ISSUE TITLE
Crashes when killing enemies

### ISSUE THREAD

**Issue by sikthehedgehog** [andwn/cave-story-md#5]
Sometimes killing an enemy resullts in the game crashing. Some of the big green flying guys in the egg corridor are prone to doing it, as well as the enemies at the beginning of Grasstown. Doesn't happen 100% of the time (sometimes it won't crash) but does happen quite often.

**Comment by sikthehedgehog** [comment]
Welp, the 2016-07-02 build turns out to fix this after all. Go figure.

**Comment by sikthehedgehog** [comment]
OK it seems the bug still exists in Egg Corridor at least.

**Comment by andwn** [comment]
Closing this along with #11. There will likely be more crashes in the future due to me messing up the enemy AI code but that can be handled case-by-case.
