### ISSUE TITLE
Behemoth drags player

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#50]
Well while I can tell that the Behemoth (the elephant in the Egg Corridor) AI is a work in progress, and I won't go into all of that because I don't fully understand the Behemoth AI myself (I have yet to figure out the exact conditions to trigger his enraged state). However I instead want to go into matters of collision.

When I approach the back of this enemy weird stuff happens:
http://i214.photobucket.com/albums/cc164/andwhyisit/hejustwantsahug_zpshnrnusdh.gif

But in the original the player is stopped like he hit a solid tile:
http://i214.photobucket.com/albums/cc164/andwhyisit/behemoth_zpsjcxlrh0b.gif

**Comment by andwn** [comment]
I think I got the push direction backwards for smushy solid objects, might depend on the direction the character & enemy are facing.

**Comment by andwn** [comment]
Yeah that was a pretty stupid mistake, whoops.

The enraged state is missing currently. Judging by what I see in the original, they seem to do it as soon as they are shot.

**Comment by sikthehedgehog** [comment]
I noticed you can also ride the flying bugs in Egg Corridor, is this related?

**Comment by andwn** [comment]
Part of the speedrun involves riding a bug past the cutscene where Igor takes Sue, so that's supposed to happen.

**Comment by andwhyisit** [comment]
I think the enraged state is meant to be if you shoot it twice in a row, but I can only seem to trigger it half of the time, so I think I'm missing some detail about how it all works.

**Comment by andwn** [comment]
Here is what NXEngine does at least: When you hit Behemoth it stops and shakes. If it shakes a specific amount longer than usual, that means you kept shooting and it charges. So if you shoot it twice really fast, it won't charge, but if you shoot twice more slowly (or keep shooting), it will.

I can check the real game later when home.

**Comment by andwhyisit** [comment]
Yep. I can confirm that the logic you specified is in the original game.

**Comment by andwhyisit** [comment]
Charge logic seems to be working fine. Although Behemoth seems to be using the charge sprite for the shake state.
