### ISSUE TITLE
VRAM issue with Missiles in Egg Corridor

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#51]
Firing a level 1 or level 2 Missile upwards in Egg Corridor draws the missile with the save point sign's tiles instead of the correct tiles.
![Screenshot](http://i.imgur.com/FqC0kux.gif)

**Comment by andwn** [comment]
This is my favorite bug. Better than the mimigas turning into Curly.

**Comment by Leo40Git** [comment]
In my opinion, this missile is much better than the old one.
