### ISSUE TITLE
Booster on Overdrive

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#52]
In the original game repeatedly pressing the jump button with the booster instead of holding it down allows you to get anywhere up to a two tile advantage, but it is slower, whereas in the MD version this can almost double your boosting height at regular boosting speed.

As for holding down the jump button, I seem to be getting one tile in extra height.

MD version:
http://i214.photobucket.com/albums/cc164/andwhyisit/mdboost_zpsgolk1ngh.gif

Original:
http://i214.photobucket.com/albums/cc164/andwhyisit/pcboost_zpswsiacevt.gif

First part of both gifs is holding down while the second part is button spamming.

**Comment by andwn** [comment]
This is the 2.0 right? The initial launch speed could be wrong. I'll mess with it until it clears the same distance in that Sand Zone section.

**Comment by andwhyisit** [comment]
Ah, yes. This is the 2.0.

**Comment by andwn** [comment]
Looks like this is what I'm missing. The player should slow down when the Booster 2.0 stops.

https://github.com/libretro/nxengine-libretro/blob/0b36ae33e2a789036eb836b581296e1d7d5d7fa6/nxengine/player.cpp#L931

**Comment by andwn** [comment]
Better now. Pressing the button around the speed you did gives the expected amount of height, mashing it goes even higher. I downloaded a save file and tried that in the real game and the mashing height was the same.
