### ISSUE TITLE
Item Equipping Glitches

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#53]
I've noticed two bugs related to the yes/no equip message for the booster on the item screen.

The first is that selecting the "no" option makes the hud disappear:
http://i214.photobucket.com/albums/cc164/andwhyisit/notohuds_zps8t6xmoif.gif

The second is that if I close the item screen while the "dequipped booster 2.0" message is shown then press jump it will trigger the whimsical star message:
http://i214.photobucket.com/albums/cc164/andwhyisit/whimsicalbooster_zpspkx8vold.gif

**Comment by andwhyisit** [comment]
Here's another one when exiting dduring or before the yes/no prompt:
http://i214.photobucket.com/albums/cc164/andwhyisit/whatamiagreeingto_zpskaxn0kx7.gif

Oh, and I had some fun while I was there:
http://i214.photobucket.com/albums/cc164/andwhyisit/imontheyessideimonthenoside_zpsvpwhfxjp.gif

**Comment by andwn** [comment]
My routine was only checking the start button but should have also made sure no script was running. The HUD is forcefully reshown after closing the menu now too.

Tested with the Life Pot, saying No and trying to unpause during the prompt.
