### ISSUE TITLE
Outer Wall segments

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#55]
The moon background seems to be segmented in an unusual manner.

Obligatory animated gif:
http://i214.photobucket.com/albums/cc164/andwhyisit/alrightwhocutthemooninhalf_zpslmplijv9.gif

**Comment by andwn** [comment]
It works fine for me but I've only been entering from the top. I might be forgetting to force vertical scroll to 0.

**Comment by andwn** [comment]
Yep that's it. If you just load from the room with Itoh the background is correct, but if you go into plantation then back out into outer wall it's wrong.

**Comment by andwn** [comment]
Opinion time. Which looks better? Before:
![2016-10-23-002509](https://cloud.githubusercontent.com/assets/8164394/19629633/03ee43ac-9947-11e6-9635-e89f705f7cf7.png)

After:
![2016-10-23-172203](https://cloud.githubusercontent.com/assets/8164394/19629641/10838064-9947-11e6-893c-b824a15f3363.png)

If I try to make that backmost cloud have any less contrast it goes full gray... so the genesis can't represent any colors inbetween.

**Comment by andwhyisit** [comment]
After. Definitely after.
