### ISSUE TITLE
Spike vs Dragon

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#60]
The falling spike at egg 8 in the egg corridor doesn't kill the dragon it lands on.

MD version:
http://i214.photobucket.com/albums/cc164/andwhyisit/dratimissed_zpsfuj9bzme.gif

Original version:
http://i214.photobucket.com/albums/cc164/andwhyisit/onthemark_zpsxuunuibq.gif

**Comment by andwn** [comment]
The spike kills the dragon zombie now but I need to manually add that -127 it seems. Also just noticed while comparing, it should be shootable after it lands.

**Comment by andwhyisit** [comment]
Actually all of those large spikes need to be shootable after they land.

The spike killing the dragon is confirmed as working.

**Comment by andwn** [comment]
I made it so they are all shootable after they land, but when testing they didn't make any kind of noise or shake while doing so.

**Comment by andwhyisit** [comment]
Ah, right. Can confirm. Shake is part of a larger issue, so I'll mark this as closed.

**Comment by andwhyisit** [comment]
Reopening this because I noticed a strange bug. After picking up whatever item the newly slain dragon leaves behind (health/ammo/exp) the -127 sign reappears.
