### ISSUE TITLE
Monster X issues

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#63]
I've found 2 issues with Monster X:
1. The idle and fight sprites are swapped around:

![](http://i.imgur.com/QR3REtl.gif)

![](http://i.imgur.com/bDNt0FD.gif)
1. In the MD version, the green thingies fire bullets simultaneously, while in the original version, they fire one after another in an order (top left -> top right -> bottom right -> bottom left).

**Comment by andwn** [comment]
The eye should be good now. The missiles' initial angle had an issue too.
