### ISSUE TITLE
First Cave background flickers on entering

### ISSUE THREAD

**Issue by sikthehedgehog** [andwn/cave-story-md#65]
Well, when crossing the first door. The background flashes white while the level is fading in.

**Comment by andwn** [comment]
I can't reproduce this on BlastEm or Gens, but I remember when I was in the middle of refactoring scrolling it did for a bit (like a month ago).

**Comment by sikthehedgehog** [comment]
I get it to happen always, maybe it's a NTSC-only thing?

**Comment by andwn** [comment]
I don't test the game on PAL :x 
been procrastinating on that.

You are running the nightly? Like you can see the weapon icons & stats in the menu?

**Comment by andwn** [comment]
Also PAL will be too slow if you don't `make pal`. It expands to 320x240 but a bunch of things probably draw wrong. Emulators are also running it as NTSC. No idea if there is something in the header I have to change.

**Comment by sikthehedgehog** [comment]
Downloaded the nightly earlier today (ROM was last modified on Nov 4th) so yeah.

**Comment by andwn** [comment]
So do you want to hear some bullshit?

The nightly is built with GCC 4.9.2 - screen flickers

I build the same exact code with GCC 6.2.0 - no flicker

Figure 65.1: Me right now
![screenshot from 2016-10-27 21-28-36](https://cloud.githubusercontent.com/assets/8164394/20033795/c62bc646-a37f-11e6-9f0d-25f01fc9f42f.png)

**Comment by sikthehedgehog** [comment]
Probably still worth looking into it since that could mean some undefined behavior going on that could become problematic later (or is it a different SGDK version too?)

**Comment by andwhyisit** [comment]
You can mark this one as fixed.
