### ISSUE TITLE
Pause menu cursor error when switching from first to last

### ISSUE THREAD

**Issue by sikthehedgehog** [andwn/cave-story-md#66]
In the pause menu, if you have selected the first slot then press ←, the cursor will be drawn one row above the one it should. (no other case seems to be broken)

**Comment by andwn** [comment]
Oh this is because I reduced the max items to 24, but apparently I have 32 hard coded into the cursor code somewhere.

**Comment by sikthehedgehog** [comment]
Should probably close it (since it's fixed).
