### ISSUE TITLE
[Save/Load] Divide By Zero exception when continuing game from Grasstown

### ISSUE THREAD

**Issue by EvilTelephone** [andwn/cave-story-md#7]
I think I was at the save point where you learn about Jellyfish Juice from Chaco. I likely had the Juice item in my inventory.

![cave-story-md000](https://cloud.githubusercontent.com/assets/539616/16629466/c3411aa0-4383-11e6-924e-14c92fa70266.png)

.

**Comment by sikthehedgehog** [comment]
Looks like that could be #3 actually, if the game doesn't have SRAM then it'll crash on loading as it tries to read garbage. You can edit the header as a workaround meanwhile.

Also yes, this means you never saved the game :O)

**Comment by EvilTelephone** [comment]
Interestingly, I could continue from the save game after a soft reset. Only after closing the emulator and reopening it later could I not.

**Comment by sikthehedgehog** [comment]
That sounds like the emulator didn't save the SRAM data when quitting... do you have the SRAM file around for testing?

**Comment by EvilTelephone** [comment]
Ah, you're totally right. It isn't writing an SRAM file for this game.

**Comment by andwn** [comment]
When there isn't any save the game is supposed to start over even if you hit "continue". The routine just checks if there is zeroes where the timestamp should be but this is the wrong approach. When I'm home next week and fix the header I'll change it to check for a specific pattern instead.
