### ISSUE TITLE
Drain Curly and she drowns anyway

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#70]
http://i214.photobucket.com/albums/cc164/andwhyisit/wifeborechild_zps6dzcrdeo.gif

**Comment by andwn** [comment]
I was messing with the TSC module because the game would freeze when she dies. There must be something special about <FLJ1444:0000 I don't understand. I made a jump to event 0 just stop executing scripts but maybe it should be ignored instead.

Gonna be lazy and look at how Noxid did it.

**Comment by andwn** [comment]
I did something stupid and the call to event 0000 didn't stop the script like it should of. Hopefully that didn't mess up the flags while in the cabin, I recopied waterway.gens.srm to test.
