### ISSUE TITLE
[Musics] New "Eyes of Flame" and "Gestation"

### ISSUE THREAD

**Issue by DavisOlivier** [andwn/cave-story-md#71]
I recently found out about this project, and i love it ^^
I noticed theres some music problems in the game, as seen in the todo list, and since i remade Eyes of Flame and Gestation on Deflemask some time ago, i thought they may be better than the ones inside the game, so if you think they are better, you can add them in the game if you wish ^^

These are the .GEN roms for you to test: https://www.dropbox.com/s/d3a2kf9l2qkum0q/Music.zip?dl=0

**Comment by andwn** [comment]
Hello! Yeah I'm not exactly a musician so a lot of my converted tracks are bad or mediocre, and Eyes of Flame was the first one I did. I like to think the more recent ones sound decent though.

How would you prefer to be credited if I use these? I was eventually going to create a document in the repository that lists off some people and what I use from them.

**Comment by David8989** [comment]
Just add my name wherever youre putting the others, its fine.
I compiled the rom myself with the ones i made and found playback problems, so i corrected them.
I also tweaked some of the ones you made, (Cave Story, Fanfare 1/2/3, Access) and i can change some others too if you wish.

All the files in the attachments

[bgm.zip](https://github.com/andwn/cave-story-md/files/601619/bgm.zip)

**Comment by andwn** [comment]
Finally getting around to throwing these in. Would you happen to have the dmf files, at least for the tweaked ones so I can include those in the source directory?

**Comment by DavisOlivier** [comment]
Sadly, no. My HD was totally formatted and i lost all the .dmf files, including the ones i made. I can try to redo the tweaks on yours since they are little, but i think i wont make the ones i made again

**Comment by andwn** [comment]
Eh don't worry about it then. The old ones are still in the version history if there is ever a dire need to change something.

**Comment by DavisOlivier** [comment]
I noticed that for some reason the sample channel stops playing at the middle of the Eyes of flame song. It sucks because i remember it played correctly in deflemask and the rom i compiled myself. And without the .dmf files nothing much can be done but to remake it from scratch -_-
Fml

**Comment by andwn** [comment]
I actually haven't checked if the VGM itself is missing that part or the converter/in-game sound driver is messing it up. If the later is the case there may be hope for eyes of flame.

**Comment by andwn** [comment]
Welp tried in VGMPlay and it's still missing. Oh well, the other tracks are fine.

**Comment by DavisOlivier** [comment]
Sorry for the late reply.
Yes, the problem is in the VGM itself. I already remade it using yours as base, as well as some others too. I will send the files as soon as i get into my computer again.

**Comment by DavisOlivier** [comment]
[caves.zip](https://github.com/andwn/cave-story-md/files/812775/tmp_22314-caves716486673.zip)
There are the files.
Meltdown2.dmf is missing due to the formatting thing, and all of them were made using yours as base.

**Comment by andwn** [comment]
Oh hey, thanks for making these. Gotta sleep so I just tossed them in for now :eyes:.

**Comment by DavisOlivier** [comment]
Np! I might improve others later when i have the time, until then let's close the issue.
