### ISSUE TITLE
Ironhead direction of facing

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#72]
Log time no bug test.

Ironhead should always face right regardless of his direction of travel, same for his projectiles, however he seems to switch his direction of facing in the MD version.

**Comment by andwn** [comment]
At least the fix will be easy. Got some stuff going on and will look into these later this week.

**Comment by andwn** [comment]
forgot to tag 410e83af4f2bfb16544967c92e5c4fee7c03d4f3
