### ISSUE TITLE
Bad ending issues

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#74]
Obligatory animated gif:
http://i214.photobucket.com/albums/cc164/andwhyisit/everyoneknowsdragonscantfly_zpsgnleldvn.gif

**Comment by andwn** [comment]
forgot to tag this one too 12efe958d0b8a9ce5c76079fdaac20f3b9d8e8ab

**Comment by andwhyisit** [comment]
Turns out there is still one problem left over with this one:
http://i214.photobucket.com/albums/cc164/andwhyisit/madskills_zpsdohenrni.gif

**Comment by andwn** [comment]
This dragon does not like me, but it should be good now.
