### ISSUE TITLE
Crash on Fusion in First Cave with door

### ISSUE THREAD

**Issue by r3muxd** [andwn/cave-story-md#75]
When you exit the door to first cave, repeatedly tap the down button. You'll enter the door multiple times and the game will freeze on a black screen. Have not tested on other emulators or real hardware. Savestate: http://www.filedropper.com/nightly Gfycat: https://gfycat.com/IndolentBigheartedIndianpangolin

**Comment by andwn** [comment]
I can't reproduce on BlastEm or hardware at least.

What version of Fusion?

This happened to someone a while ago on Genesis Plus GX but I was never able to reproduce then either. Maybe there is some special detail like forcing PAL?

**Comment by r3muxd** [comment]
Fusion 3.64, Windows. You can test by loading the savestate and tapping down repeatedly.
