### ISSUE TITLE
Corrupt screen lock on Hell

### ISSUE THREAD

**Issue by r3muxd** [andwn/cave-story-md#77]
Near the end of B1 the game will y lock the screen. I'm on mobile so can't send gsx but am using 0.3.0 on Kega Fusion.

**Comment by andwn** [comment]
How did you even get to hell? The undead core isn't defeatable yet.

**Comment by PIXgedgie** [comment]
Andy, prof2sram, maybe?

**Comment by r3muxd** [comment]
prof2sram. The spikes are also invisible, but I just assumed the graphics are slightly different and haven't been added. It's not really B1 (it's the start, don't know what it's called), but I thought this would be helpful as the level still seems to be past below the screen (albeit without objects), but the screen seems locked. I'm guessing this is because of invalid coordinates for the level.

**Comment by andwhyisit** [comment]
This one can be marked as fixed.

**Comment by andwn** [comment]
The object the camera is supposed to be following is reused from the ending in the Balcony 2 map, which was not implemented at the time.
