### ISSUE TITLE
[Cutscene] First Balrog cutscene can be repeated, leads to sprite glitch.

### ISSUE THREAD

**Issue by EvilTelephone** [andwn/cave-story-md#8]
In the shack where you fight Balrog the first time, the first cutscene and fight are normal.

After the fight (or if you choose not to fight), you can still talk to Toroko, which will cause the battle cutscene to repeat, but this time without any enemy sprites.

If you choose to fight, the battle music will start, but there's no Balrog. You can't leave the shack until you talk to Toroko a third time and choose not to fight.

**Comment by andwn** [comment]
Toroko is supposed to be carried away in Misery's bubble, but there aren't any routines for the bubble yet. So she just kind of... stays there.

**Comment by andwn** [comment]
Toroko should no longer linger around in this release

https://github.com/andwn/cave-story-md/releases/tag/SNAPSHOT-2016.07.16
