### ISSUE TITLE
3 button controller support

### ISSUE THREAD

**Issue by andwn** [andwn/cave-story-md#80]
Y and Z are used to switch weapons on a 6 button, but when a 3 button controller is inserted use A to cycle through (and B to skip?).

**Comment by sikthehedgehog** [comment]
You can't really switch weapons during a textbox, so it shouldn't interfere with skipping, right?

**Comment by andwn** [comment]
Yeah it just depends which is more annoying if pressed by accident. Shooting or switching.

**Comment by Trimint123** [comment]
I think make it change in menu like original game did.

**Comment by sikthehedgehog** [comment]
You're more likely to be trigger happy with shooting than with switching weapons :P

**Comment by andwn** [comment]
And now the inventory selection has gotta be one of the hackiest things I have written. Don't code like me.
