### ISSUE TITLE
[TODO] Finish the music

### ISSUE THREAD

**Issue by andwn** [andwn/cave-story-md#83]
Music tracks which still need to be created:

- [x] Way Back Home (credits)
- [x] Running Hell
- [x] Seal Chamber
- [x] Toroko's Theme
- [x] King's Theme

**Comment by Trimint123** [comment]
Hm... I think you need someones help for other musics. Not just placeholder one.

**Comment by lomas7er** [comment]
Maybe I can help with that? Currently, I rewrote a few CS tracks in the VGM Maker pretty ago. Take a look at this https://www.youtube.com/watch?v=yVB_djFEuNY Except for this, there are Gestation, Last Battle, Scorching Back and Fanfare1 tracks. They're about the same quality as Grasstown.
If you don't mind, I could create the rest of them.

**Comment by andwn** [comment]
Will worry about the last 2 tracks after a compression scheme that doesn't break everything is in

**Comment by SkyTheLeafeon** [comment]
The whole soundtrack might need to be touched up, as a matter of fact (emphasis on might)

**Comment by andwn** [comment]
It's all done, next release will have every track
