### ISSUE TITLE
Booster 2.0 Boost is too long and/or far (EDIT: Was a mistake)

### ISSUE THREAD

**Issue by Trimint123** [andwn/cave-story-md#86]
http://s214.photobucket.com/user/andwhyisit/media/pcboost_zpswsiacevt.gif.html?sort=3&o=28 Original Game
http://s214.photobucket.com/user/andwhyisit/media/mdboost_zpsgolk1ngh.gif.html?sort=3&o=27 The Homebrew

**Comment by andwn** [comment]
I fixed this in October, see #52. What version are you playing?

**Comment by Trimint123** [comment]
Oh, really? Man, I'm stupid. How to delete this post?

**Comment by Trimint123** [comment]
Closed it
