### ISSUE TITLE
Problems with presses

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#87]
If you destroy a block under a certain type of press (the ones that fall when affected by gravity, as opposed to those that fall only when you stand under them) it will fall and land on the block below it, but when you destroy that block below it... nothing happens. It just hovers in midair.

http://i214.photobucket.com/albums/cc164/andwhyisit/whyaminotdead_zpsjwuivfsc.gif

**Comment by andwn** [comment]
Just tried in the same area. Should be good now.

I might need to adjust the collision box though... if you walk up to the block under the press and shoot, it crushes you standing next to it.
