### ISSUE TITLE
Door error when rescuing Kazuma

### ISSUE THREAD

**Issue by sikthehedgehog** [andwn/cave-story-md#9]
The cutscene when you rescue Kazuma in Grasstown is bugged up. That in itself I assume is just unfinished, but the real problem is that the trigger for the door is higher than the door sprite (so you have to jump and press down in mid-air to get through). This is also easy to miss so you're bound to get stuck if you don't figure it out.

The cutscene in itself needs to be finished but that one issue is actually critical compared to all the other bugginess.

**Comment by EvilTelephone** [comment]
From what I gather, that's as far as we're supposed to be able to get yet. The rest of the game beyond that isn't finished enough to be playable, as I understand it. The dev notes do comment that "getting to the labyrinth is technically possible", but I'm going to assume that would be with the help of a cheat code or some other modification.

**Comment by sikthehedgehog** [comment]
"technically possible" means without cheating, otherwise I'd assume every place would count :P The game resumes as normal after that.

**Comment by andwn** [comment]
It's possible without cheating but increasingly unintuitive and buggy as it goes on. Some enemies in Sand Zone don't even have sprites!

**Comment by sikthehedgehog** [comment]
There's already one of those invisible enemies in Grasstown :P (I keep forgetting they're there >_<)

**Comment by andwn** [comment]
oh yeah the frog. soon(tm)

**Comment by andwn** [comment]
I think I figured out the real reason. There is a separate "busted doorway" npc different from a normal door. Still gotta test it later

**Comment by andwn** [comment]
Welp, it's not even a door. Option 2 flag pushes it down.

![image1](https://my.mixtape.moe/ztvlon.png)

![image2](https://my.mixtape.moe/tesxoh.png)
