### ISSUE TITLE
Player doesn't stay facing back

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#90]
This is more of an enhancement than a genuine issue, but...
In the original game, pressing down to inspect something causes the player to stay facing away from the screen until the left/right/up/jump key is pressed.
In this version, the player faces away from the screen until you release the down key.

**Comment by andwn** [comment]
Added a "lookingBack" flag into the logic to make it stick until you jump or press another direction. During this process I tried to fix Quote not looking back when interacting with some objects. All that's missing is the question mark.
