### ISSUE TITLE
Odd title screen bug on Fusion

### ISSUE THREAD

**Issue by Leo40Git** [andwn/cave-story-md#91]
For no reason in particular, the game decided to use Sue as the title screen cursor and Safety as the title song.
I'm guessing this effect is supposed to be for the Hell time trial, but for some reason I got it before even stepping foot outside of First Cave.
Here's a save state: [SueTitleScreen.zip](https://github.com/andwn/cave-story-md/files/771495/SueTitleScreen.zip)

**Comment by andwn** [comment]
Can you send the SRAM file? Judging by the state filename this is Genesis Plus GX?

**Comment by Leo40Git** [comment]
The state file was made in Fusion because Fusion decided not to create an SRAM file.

I'm currently retracing my steps in Gens Plus, I'll get back to you when I have it.

**Comment by Leo40Git** [comment]
...huh, that's odd. I just tried it again in Gens Plus, and it didn't work.
Well, what I did was get the Life Capsule, get the Polar Star, grind the Polar Star up to level 3 by entering and exiting, and defeat the evil door.
Could this be a Fusion only glitch?

**Comment by andwn** [comment]
Why is it always Fusion....

I'll have to try it out later. Their website has been down for months, and the latest version on Sega Retro is from 2010.

**Comment by Leo40Git** [comment]
...okay, the Sue title screen is apparently triggered by _saving the game_.

I managed to persuade Fusion into saving SRAM, so here it is: [doukutsu.zip](https://github.com/andwn/cave-story-md/files/771562/doukutsu.zip)
[doukutsu.zip](https://github.com/andwn/cave-story-md/files/771560/doukutsu.zip)

**Comment by sikthehedgehog** [comment]
Guys, can't we just call it a feature? :P

**Comment by Leo40Git** [comment]
Ironically, this _is_ supposed to be a feature.

**Comment by andwn** [comment]
A feature I never tested since Hell isn't done :^)

I think it's because of how unwritten bytes are saved (0xFF). If so this will happen every time on Fusion until you beat Hell. Guess I should be clearing those bytes during the blank SRAM test anyway.

**Comment by andwn** [comment]
(to clarify, the clock is supposed to be permanent, so saving the game skips over that part)

**Comment by andwn** [comment]
This should work, probably, but required deleting the srm file and starting anew.

[doukutsu-fix91.zip](https://github.com/andwn/cave-story-md/files/771670/doukutsu-fix91.zip)

**Comment by Leo40Git** [comment]
Fix confirmed as working.
