### ISSUE TITLE
Monster X weirdness

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#93]
The fish missiles don't seem to point in the direction of their path of travel.

The fish missiles can't be destroyed, same for the Core's projectiles.

Also if you defeat Monster X while standing on its leg then you will hover in midair.

**Comment by andwhyisit** [comment]
The right facing sprite for the fish missiles seems to be wrong. Also while the fish missiles do seem to be shootable, they seem to have too much hp (it should be 1hp).

The hovering is still an issue though, as are the core's projectiles (though maybe I should make a separate issue for that).

Everything else seems fine.

**Comment by andwhyisit** [comment]
Hovering still seems to be an issue.

Obligatory gif:
![](http://i214.photobucket.com/albums/cc164/andwhyisit/hoverx_zpss8y5bpzj.gif)

**Comment by andwhyisit** [comment]
Oh, and the right pointing fish sprite is still an issue:
http://i214.photobucket.com/albums/cc164/andwhyisit/whatthefish_zps9axvlq57.gif

**Comment by andwn** [comment]
Why are the bright green parts transparent did that happen in the actual game or is that just the gif?

**Comment by andwhyisit** [comment]
I think I might be the gif. I cannot reproduce it.
