### ISSUE TITLE
The Littles

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#95]
Mr Little will announce that he is home when he isn't in your inventory. He also lacks a sprite in the cemetery.

The Little house is a black screen with no interactable entities.

**Comment by andwn** [comment]
Confession: I've never done this sidequest, though I have tried entering the house. 

Something could be wrong with the converted TSC, I recall the screen never faded in and the game just locked up.

**Comment by andwhyisit** [comment]
Actually it doesn't lock up (at least last time I tested), you can still move around the map.

**Comment by andwn** [comment]
The reason for this one is incredibly stupid. So the first byte of each of my converted TSC files is supposed to be the number of events in the script... but for some bizarre reason, the Littles map had this as 0. Now the TSC interpreter, having no idea what to do, just continues executing the Outer Wall script, which writes the "I'm hoome!!" text. Once finished, it leaves you in the new map with no script and you are stuck.

I didn't count how many hours it took me to figure this out but at least I can confidently say it was in the single digits.

![pbs_twimg_com_media_ckhjvvxweaaw](https://cloud.githubusercontent.com/assets/8164394/23337388/a3382552-fbb9-11e6-91f0-83db04de0124.jpg)


I guess there is still the sprites to take care of.

**Comment by andwhyisit** [comment]
One of the ceiling slopes outside the Littles' house makes it  near impossible to exit the area.

**Comment by andwn** [comment]
Where is the sprite sheet for this even?

**Comment by andwhyisit** [comment]
I thought it was in NpcRegu or NpcGuest? Sorry, I can't check until tomorrow night because I won't have my computer in front of me until then.

**Comment by andwn** [comment]
Well apparently it's in the lower left of ItemImage.pbm. Weird place for it.

**Comment by andwhyisit** [comment]
Mr. Little's sprite in the Cemetery is still missing.

The Littles also don't pace about the room. This is especially important for Mr. Little, otherwise you wouldn't notice him in the Cemetery.

**Comment by andwn** [comment]
It must be great trying to look at where these tiny sprites are on a CRT.
