### ISSUE TITLE
Fading Issues

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#98]
Whenever a fade is accompanied with text (or maybe it is just more noticeable that way), and there is a sprite with pure white in it, then those white pixels will show despite the fade.

Examples of this are the bubble during the Waterway to Ironhead transition (i.e. "something's coming"), or the rocket in the Plantation Hideout while resting in bed.

**Comment by sikthehedgehog** [comment]
They're using the same color entry (and will happen when *anything* else using that color is on screen). Only workaround would be to remove sprites during fading... which in itself brings up a different problem (sprites disappear while fading! d'oh)

The only other workaround is to just make the text fade out as well.

**Comment by andwhyisit** [comment]
Maybe hide all sprites directly after a fade out and show all sprites directly before a fade in? The Waterway to Ironhead transition looks really dodgy as it stands.

The fade animation is short enough that you wouldn't notice it for anything other than a fade with text.

**Comment by andwn** [comment]
Should be doable. The fade in after sleeping may look weird, bits of sprites will appear white immediately but better than nothing.
