### ISSUE TITLE
Door Layering

### ISSUE THREAD

**Issue by andwhyisit** [andwn/cave-story-md#99]
Doors sometimes appear on top of other sprites such as enemies (Midorin, the green enemy from the Plantation, is a good example of this) or Jenka's dogs when you carry them on your back.

**Comment by andwhyisit** [comment]
Sadly now that Kanpachi can finally walk this issue rears its ugly head.

**Comment by andwn** [comment]
There are times when the door has to be above objects too (King and Jack after Egg Corridor) so I may have to handle this case by case.

**Comment by andwn** [comment]
The examples you mention should be good now, but I have not tested the puppy yet.

It's still case by case, but now I can just put `moveMeToFront = TRUE;` in the AI routine when the ordering is wrong.

**Comment by andwhyisit** [comment]
The puppy seems to be working, as with the rest.

**Comment by andwhyisit** [comment]
I am getting this again with Gaudi in the Labyrinth and the large frenzied Mimiga on the Balcony. If there some way to blanket apply this to enemies?

**Comment by andwn** [comment]
The problem is it's not set it and forget it. Every time the door goes off screen and back again, it's re-inserted to the front of the list. So objects that need to be in front of the doors have to signal the engine every so often to move to the front.

**Comment by andwhyisit** [comment]
What about on enemy to door collision? It could be added to the door ai?

**Comment by andwhyisit** [comment]
Grasstown bats can be added to the list.
